{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/collisionseverity\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/collisionseverity\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/CollisionSeverity\/unknown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"unknown severity collision."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"CollisionSeverity.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity@FairmaticCollisionSeverityUnknown","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/CollisionSeverity"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/CollisionSeverity/unknown":{"role":"symbol","title":"CollisionSeverity.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"unknown severity collision."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/CollisionSeverity\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity\/unknown"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/CollisionSeverity":{"role":"symbol","title":"CollisionSeverity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollisionSeverity"}],"abstract":[{"type":"text","text":"Collision severity of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/CollisionSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollisionSeverity"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticCollisionSeverityUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1CollisionSeverity~1unknown\/title","value":"FairmaticCollisionSeverityUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1CollisionSeverity~1unknown\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1CollisionSeverity\/title","value":"FairmaticCollisionSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1CollisionSeverity\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}