{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyAlias"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeyalias"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeyalias"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyAlias","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Key for driver alias returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyAlias"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"driverAttributesKeyAlias","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributesKeys(cpy)driverAttributesKeyAlias","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyAlias"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/asJson()":{"role":"symbol","title":"asJson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns driver attributes as a json string. Empty string if json serialization"},{"type":"text","text":" "},{"type":"text","text":"fails."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"asJson"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/asjson()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys":{"role":"symbol","title":"DriverAttributesKeys","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributesKeys"}],"abstract":[{"type":"text","text":"Keys for various properties returned by toJson method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriverAttributesKeys"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/driverAttributesKeyAlias":{"role":"symbol","title":"driverAttributesKeyAlias","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyAlias"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for driver alias returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyAlias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyAlias"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeyalias"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"driverAttributesKeyAlias"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyAlias"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"driverAttributesKeyAlias"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/title","value":"asJson"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asJson"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys\/title","value":"FairmaticDriverAttributesKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributesKeys"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyAlias\/title","value":"driverAttributesKeyAlias"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyAlias\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyAlias"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}