{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDriveDetectionMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode","text":"DriveDetectionMode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to get the current "},{"type":"codeVoice","code":"DriveDetectionMode"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/getdrivedetectionmode()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/getdrivedetectionmode()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getDriveDetectionMode()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The drive detection mode controls how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getDriveDetectionMode"}],"role":"symbol","title":"getDriveDetectionMode()","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDriveDetectionMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)Fairmatic(cm)getDriveDetectionMode","modules":[{"name":"FairmaticSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode":{"role":"symbol","title":"DriveDetectionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveDetectionMode"}],"abstract":[{"type":"text","text":"Dictates the functioning of Fairmatic’s drive detection."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/getDriveDetectionMode()":{"role":"symbol","title":"getDriveDetectionMode()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDriveDetectionMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"abstract":[{"type":"text","text":"The drive detection mode controls how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getDriveDetectionMode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDriveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/getdrivedetectionmode()"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getDriveDetectionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDriveDetectionMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode","text":"FairmaticDriveDetectionMode"},{"kind":"text","text":") "},{"kind":"identifier","text":"getDriveDetectionMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/title","value":"FairmaticDriveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getDriveDetectionMode()\/title","value":"getDriveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getDriveDetectionMode()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDriveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}