{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"trackingId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional identifier which allows identifying this drive uniquely. If this value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the SDK will supply a default trackingId with value "},{"type":"codeVoice","code":"com.fairmatic.sdk.internal"},{"type":"text","text":" ."},{"type":"text","text":" "},{"type":"text","text":"It may not be an empty string. It will be truncated to 64 characters if it is longer than 64 characters. Passing invalid "},{"type":"codeVoice","code":"trackingId"},{"type":"text","text":" is an error. Please use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)"},{"type":"text","text":" to validate the trackingId."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block object to be executed when the task finishes."},{"type":"text","text":" "},{"type":"text","text":"This block has no return value and two arguments:"},{"type":"text","text":" "},{"type":"codeVoice","code":"success"},{"type":"text","text":":  A boolean that suggests if drive is started successfully"},{"type":"text","text":" "},{"type":"codeVoice","code":"error"},{"type":"text","text":": A valid "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError"},{"type":"text","text":" is returned in case of a failure."},{"type":"text","text":" "},{"type":"text","text":"Possible error codes returned: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError\/notSetup"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError\/invalidTrackingId"},{"type":"text","text":" "},{"type":"text","text":"Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError"},{"type":"text","text":" for more details on the errors."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoking this method forces the start of a drive. If this API is"},{"type":"text","text":" "},{"type":"text","text":"used then it is application’s responsibility to terminate the drive by"},{"type":"text","text":" "},{"type":"text","text":"invoking "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)"},{"type":"text","text":" method. If an auto-detected drive is in progress, that drive"},{"type":"text","text":" "},{"type":"text","text":"is stopped and a new drive is started."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These methods should be used only by applications which have explicit"},{"type":"text","text":" "},{"type":"text","text":"knowledge of start and end of drives and want to attribute drive data to"},{"type":"text","text":" "},{"type":"text","text":"specific trackingIds."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling it without having initialized the Fairmatic framework"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)"},{"type":"text","text":" is a no-op."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" with the same trackingId without calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)"},{"type":"text","text":" in between"},{"type":"text","text":" "},{"type":"text","text":"is a no-op. Calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" with a different trackingId: with implicitly call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)"},{"type":"text","text":" before starting a new drive."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an asynchronous method, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)"},{"type":"text","text":" "},{"type":"text","text":"is triggered once this finishes with basic information about the drive. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo"},{"type":"text","text":" will return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" until "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)"},{"type":"text","text":" is called"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)"},{"type":"text","text":" to stop drive data collection."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)Fairmatic(cm)startManualDriveWithTrackingId:completionHandler:","modules":[{"name":"FairmaticSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod2:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod2:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 2 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod2:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/isValidInputParameter(_:)":{"role":"symbol","title":"isValidInputParameter(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidInputParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this method to check whether the parameter string passed"},{"type":"text","text":" "},{"type":"text","text":"to the SDK is valid."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isValidInputParameter:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/isvalidinputparameter(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticError/notSetup":{"role":"symbol","title":"FairmaticError.notSetup","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"abstract":[{"type":"text","text":"Fairmatic SDK is not setup. This error is also returned in case SDK setup has started but completion handler for setup is not called yet."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError\/notSetup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorNotSetup"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/notsetup"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod3:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod3:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod3"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 3 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod3:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setup(with:delegate:completionHandler:)":{"role":"symbol","title":"setup(with:delegate:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDelegate","preciseIdentifier":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Initializes the Fairmatic SDK to automatically detect driving and collect"},{"type":"text","text":" "},{"type":"text","text":"data. Client code should call this method before anything else in the Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setup(with:delegate:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/activeDriveInfo":{"role":"symbol","title":"activeDriveInfo","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeDriveInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActiveDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get info on the currently active drive. If sdk is not setup or if"},{"type":"text","text":" "},{"type":"text","text":"no drive is in progress, nil is returned."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activeDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/activedriveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/stopManualDrive(completionHandler:)":{"role":"symbol","title":"stopManualDrive(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This should be called to indicate the end of a drive started by invoking"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopManualDriveWithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/stopmanualdrive(completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticError":{"role":"symbol","title":"FairmaticError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticError"}],"abstract":[{"type":"text","text":"Error returned as code of "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" public APIs in case of"},{"type":"text","text":" "},{"type":"text","text":"failures."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticError/invalidTrackingId":{"role":"symbol","title":"FairmaticError.invalidTrackingId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTrackingId"}],"abstract":[{"type":"text","text":"Invalid "},{"type":"codeVoice","code":"trackingId"},{"type":"text","text":" passed for new drive. This error may be returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticError\/invalidTrackingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInvalidTrackingId"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/invalidtrackingid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processStart(ofDrive:)":{"role":"symbol","title":"processStart(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveStartInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a potential"},{"type":"text","text":" "},{"type":"text","text":"start of a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processStartOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processstart(ofdrive:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startManualDriveWithTrackingId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"trackingId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool, NSError *)","preciseIdentifier":"c:BFv(#b#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod2:completionHandler:)\/title","value":"startDriveWithPeriod2:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod2:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/title","value":"isValidInputParameter:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isValidInputParameter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticError~1notSetup\/title","value":"FairmaticErrorNotSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticError~1notSetup\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorNotSetup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/title","value":"startDriveWithPeriod3:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/title","value":"setupWith:delegate:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1activeDriveInfo\/title","value":"activeDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1activeDriveInfo\/fragments","value":[{"kind":"identifier","text":"activeDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopManualDrive(completionHandler:)\/title","value":"stopManualDriveWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopManualDrive(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopManualDriveWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticError\/title","value":"FairmaticError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticError\/fragments","value":[{"kind":"identifier","text":"FairmaticError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticError~1invalidTrackingId\/title","value":"FairmaticErrorInvalidTrackingId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticError~1invalidTrackingId\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInvalidTrackingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processStart(ofDrive:)\/title","value":"processStartOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processStart(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processStartOfDrive:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}