{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek","text":"FairmaticDayOfWeek"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shifttime\/dayofweek"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shifttime\/dayofweek"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/dayOfWeek","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the day of the week, range: [1-7]"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek"}],"title":"dayOfWeek","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime(py)dayOfWeek","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"dayOfWeek"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime/dayOfWeek":{"role":"symbol","title":"dayOfWeek","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek"}],"abstract":[{"type":"text","text":"Represents the day of the week, range: [1-7]"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/dayOfWeek","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dayOfWeek"}],"url":"\/documentation\/fairmaticsdk\/shifttime\/dayofweek"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime":{"role":"symbol","title":"ShiftTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftTime"}],"abstract":[{"type":"text","text":"Represents a particular day and time in a weekly schedule, The shift time is represented in 24 hour time format."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftTime"}],"url":"\/documentation\/fairmaticsdk\/shifttime"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDayOfWeek":{"role":"symbol","title":"FairmaticDayOfWeek","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDayOfWeek"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDayOfWeek"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdayofweek"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dayOfWeek"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dayOfWeek"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek","text":"FairmaticDayOfWeek"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayOfWeek"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1dayOfWeek\/title","value":"dayOfWeek"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1dayOfWeek\/fragments","value":[{"kind":"identifier","text":"dayOfWeek"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/title","value":"FairmaticShiftTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek\/title","value":"FairmaticDayOfWeek"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek\/fragments","value":[{"kind":"identifier","text":"FairmaticDayOfWeek"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}