{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek","text":"FairmaticDayOfWeek"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"codeListing","syntax":"swift","code":["let shiftTime = ShiftTime(dayOfWeek: .sunday, hour: 11, minute: 40)"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shifttime\/init(dayofweek:hour:minute:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shifttime\/init(dayofweek:hour:minute:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/init(dayOfWeek:hour:minute:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"initializes the "},{"type":"codeVoice","code":"ShiftTime"},{"type":"text","text":" object."},{"type":"text","text":" "},{"type":"text","text":"Example"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(dayOfWeek:hour:minute:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime(im)initWithDayOfWeek:hour:minute:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDayOfWeek:hour:minute:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime/init(dayOfWeek:hour:minute:)":{"role":"symbol","title":"init(dayOfWeek:hour:minute:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"initializes the "},{"type":"codeVoice","code":"ShiftTime"},{"type":"text","text":" object."},{"type":"text","text":" "},{"type":"text","text":"Example"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/init(dayOfWeek:hour:minute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDayOfWeek:hour:minute:"}],"url":"\/documentation\/fairmaticsdk\/shifttime\/init(dayofweek:hour:minute:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime":{"role":"symbol","title":"ShiftTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftTime"}],"abstract":[{"type":"text","text":"Represents a particular day and time in a weekly schedule, The shift time is represented in 24 hour time format."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftTime"}],"url":"\/documentation\/fairmaticsdk\/shifttime"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDayOfWeek":{"role":"symbol","title":"FairmaticDayOfWeek","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDayOfWeek"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDayOfWeek"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdayofweek"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDayOfWeek:hour:minute:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDayOfWeek:hour:minute:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDayOfWeek:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek","text":"FairmaticDayOfWeek"},{"kind":"text","text":")"},{"kind":"internalParam","text":"dayOfWeek"},{"kind":"text","text":" "},{"kind":"identifier","text":"hour:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hour"},{"kind":"text","text":" "},{"kind":"identifier","text":"minute:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minute"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1init(dayOfWeek:hour:minute:)\/title","value":"initWithDayOfWeek:hour:minute:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1init(dayOfWeek:hour:minute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDayOfWeek:hour:minute:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/title","value":"FairmaticShiftTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek\/title","value":"FairmaticDayOfWeek"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek\/fragments","value":[{"kind":"identifier","text":"FairmaticDayOfWeek"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}