{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"accidentInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo","text":"AccidentInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accidentInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Info about accident."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This callback is fired on the main thread when an accident is detected by"},{"type":"text","text":" "},{"type":"text","text":"the SDK during a drive. Any ongoing auto-detected\/manual drives will be stopped"},{"type":"text","text":" "},{"type":"text","text":"after this point."}],"kind":"symbol","metadata":{"modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"processAccidentDetected:"}],"role":"symbol","title":"processAccidentDetected(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate(im)processAccidentDetected:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processAccidentDetected(_:)":{"navigatorTitle":[{"kind":"identifier","text":"processAccidentDetected:"}],"role":"symbol","title":"processAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is fired on the main thread when an accident is detected by"},{"type":"text","text":" "},{"type":"text","text":"the SDK during a drive. Any ongoing auto-detected\/manual drives will be stopped"},{"type":"text","text":" "},{"type":"text","text":"after this point."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo":{"role":"symbol","title":"AccidentInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to an accident detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentInfo"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"processAccidentDetected:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAccidentDetected:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"processAccidentDetected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo","text":"FairmaticAccidentInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accidentInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/title","value":"processAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/title","value":"FairmaticAccidentInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}