{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processResume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resumeInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo","text":"DriveResumeInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"resumeInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Info about drive resume. Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo"},{"type":"text","text":" for further details."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The gap in drive recording may occur due to an application restart by the OS,"},{"type":"text","text":" "},{"type":"text","text":"application kill and restart by a user, an application crash or other reasons."},{"type":"text","text":" "},{"type":"text","text":"Drives started by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" are always resumed and they"},{"type":"text","text":" "},{"type":"text","text":"will not end until "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)"},{"type":"text","text":" is called."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processresume(ofdrive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processresume(ofdrive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processResume(ofDrive:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK resumes a"},{"type":"text","text":" "},{"type":"text","text":"drive after a gap."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"processResumeOfDrive:"}],"role":"symbol","title":"processResume(ofDrive:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processResume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveResumeInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate(im)processResumeOfDrive:","modules":[{"name":"FairmaticSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/stopManualDrive(completionHandler:)":{"role":"symbol","title":"stopManualDrive(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This should be called to indicate the end of a drive started by invoking"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopManualDriveWithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/stopmanualdrive(completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveResumeInfo":{"role":"symbol","title":"DriveResumeInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveResumeInfo"}],"abstract":[{"type":"text","text":"Information about a drive that was resumed in the "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveResumeInfo"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processResume(ofDrive:)":{"role":"symbol","title":"processResume(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processResume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveResumeInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK resumes a"},{"type":"text","text":" "},{"type":"text","text":"drive after a gap."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processResume(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processResumeOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processresume(ofdrive:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"processResumeOfDrive:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processResumeOfDrive:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"processResumeOfDrive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo","text":"FairmaticDriveResumeInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"resumeInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopManualDrive(completionHandler:)\/title","value":"stopManualDriveWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopManualDrive(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopManualDriveWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveResumeInfo\/title","value":"FairmaticDriveResumeInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveResumeInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveResumeInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processResume(ofDrive:)\/title","value":"processResumeOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processResume(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processResumeOfDrive:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}