{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint","text":"LocationPoint"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This array contains a series of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" which"},{"type":"text","text":" "},{"type":"text","text":"approximate the path taken by the driver. This is not the detailed location"},{"type":"text","text":" "},{"type":"text","text":"data but rather a sample representing route geometry."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array might be empty if no accurate gps location is determined till"},{"type":"text","text":" "},{"type":"codeVoice","code":"FairmaticDelegate.processStart(ofDrive:)"},{"type":"text","text":" call."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivestartinfo\/waypoints"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/drivestartinfo\/waypoints"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/waypoints","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]?"}],"title":"waypoints","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo(py)waypoints","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"waypoints"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo":{"role":"symbol","title":"DriveStartInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveStartInfo"}],"abstract":[{"type":"text","text":"Information about start of a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveStartInfo"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/LocationPoint":{"role":"symbol","title":"LocationPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationPoint"}],"abstract":[{"type":"text","text":"Represents a geographical coordinate."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationPoint"}],"url":"\/documentation\/fairmaticsdk\/locationpoint"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/waypoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waypoints"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/waypoints"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"waypoints"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"waypoints"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<FairmaticLocationPoint *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"waypoints"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo\/title","value":"FairmaticDriveStartInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveStartInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/title","value":"FairmaticLocationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/fragments","value":[{"kind":"identifier","text":"FairmaticLocationPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1waypoints\/title","value":"waypoints"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1waypoints\/fragments","value":[{"kind":"identifier","text":"waypoints"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}