{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period3"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod\/period3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod\/period3"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period3","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Drives undertaken with insurance period 3 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period3"}],"title":"InsurancePeriod.period3","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod@FairmaticInsurancePeriodPeriod3","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod":{"role":"symbol","title":"InsurancePeriod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InsurancePeriod"}],"abstract":[{"type":"text","text":"The types of insurance period in "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InsurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/period3":{"role":"symbol","title":"InsurancePeriod.period3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period3"}],"abstract":[{"type":"text","text":"Drives undertaken with insurance period 3 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/period3"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod3:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod3:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod3"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 3 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod3:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticInsurancePeriodPeriod3"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod\/title","value":"FairmaticInsurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period3\/title","value":"FairmaticInsurancePeriodPeriod3"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period3\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/title","value":"startDriveWithPeriod3:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}