{"variants":[{"paths":["\/documentation\/fairmaticsdk\/eventseverity\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventSeverity\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventSeverity\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"FairmaticSDK"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventSeverity"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventSeverity":{"role":"symbol","title":"eventSeverity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticEventSeverity"}],"abstract":[{"type":"text","text":"The severity of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventSeverity"}],"url":"\/documentation\/fairmaticsdk\/event\/eventseverity"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventSeverity":{"role":"symbol","title":"EventSeverity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventSeverity"}],"abstract":[{"type":"text","text":"This is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventSeverity"},{"type":"text","text":", it represents the"},{"type":"text","text":" "},{"type":"text","text":"severity of event if application for that event type."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventSeverity"}],"url":"\/documentation\/fairmaticsdk\/eventseverity"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventSeverity/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventSeverity\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventseverity\/!=(_:_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventSeverity\/title","value":"eventSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventSeverity\/fragments","value":[{"kind":"identifier","text":"eventSeverity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventSeverity\/title","value":"FairmaticEventSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventSeverity\/fragments","value":[{"kind":"identifier","text":"FairmaticEventSeverity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}