{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driverattributes\/asjson()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driverattributes\/asjson()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns driver attributes as a json string. Empty string if json serialization"},{"type":"text","text":" "},{"type":"text","text":"fails."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"asJson()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes(im)asJson","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"asJson"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriverAttributes/asJson()":{"role":"symbol","title":"asJson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns driver attributes as a json string. Empty string if json serialization"},{"type":"text","text":" "},{"type":"text","text":"fails."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"asJson"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/asjson()"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriverAttributes":{"role":"symbol","title":"DriverAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributes"}],"abstract":[{"type":"text","text":"Additional attributes of a "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" driver."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriverAttributes"}],"url":"\/documentation\/fairmaticsdk\/driverattributes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"asJson"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asJson"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/title","value":"asJson"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asJson"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes\/title","value":"FairmaticDriverAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}