{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPausedReason"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticPausedReason","text":"PausedReason"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason"},{"type":"text","text":" encapsulating "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason"},{"type":"text","text":" with values: - "},{"type":"codeVoice","code":"user"},{"type":"text","text":": The SDK is paused manually by user. "},{"type":"codeVoice","code":"businessHours"},{"type":"text","text":": The SDK is paused automatically due to business hours. "},{"type":"codeVoice","code":".notPaused"},{"type":"text","text":": The SDK is not paused."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"type":"codeListing","syntax":null,"code":["do {","let pausedReason = try Fairmatic.getPausedReason()","switch (pausedReason.pausedReason) {","","} catch {"," \/\/ handle error.","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/getpausedreason()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/getPausedReason()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the reason for the SDK being paused."},{"type":"text","text":" "},{"type":"text","text":"throws: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notSetup"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPausedReason"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"PausedReason","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticPausedReason"}],"title":"getPausedReason()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:12FairmaticSDK0A0C15getPausedReasonAA0dE0CyKFZ","modules":[{"name":"FairmaticSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/PausedReason":{"role":"symbol","title":"PausedReason","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PausedReason"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PausedReason"}],"url":"\/documentation\/fairmaticsdk\/pausedreason"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/getPausedReason()":{"role":"symbol","title":"getPausedReason()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPausedReason"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"PausedReason","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticPausedReason"}],"abstract":[{"type":"text","text":"Returns the reason for the SDK being paused."},{"type":"text","text":" "},{"type":"text","text":"throws: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notSetup"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/getPausedReason()","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmatic\/getpausedreason()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/notSetup":{"role":"symbol","title":"FairmaticError.notSetup","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"abstract":[{"type":"text","text":"Fairmatic SDK is not setup. This error is also returned in case SDK setup"},{"type":"text","text":" "},{"type":"text","text":"has started but completion handler for setup is not called yet."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notSetup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorNotSetup"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/notsetup"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason":{"role":"symbol","title":"FairmaticPauseReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticPauseReason"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReason"}],"url":"\/documentation\/fairmaticsdk\/fairmaticpausereason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1PausedReason\/title","value":"FairmaticPausedReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1PausedReason\/fragments","value":[{"kind":"identifier","text":"FairmaticPausedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1notSetup\/title","value":"FairmaticErrorNotSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1notSetup\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorNotSetup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason\/title","value":"FairmaticPauseReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}