{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAssociatedVehicles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo","text":"VehicleInfo"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"- The list of associated vehicles if sdk is setup, else nil."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getassociatedvehicles()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getassociatedvehicles()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getAssociatedVehicles()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAssociatedVehicles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo"},{"kind":"text","text":"]?"}],"title":"getAssociatedVehicles()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleTagging(cm)getAssociatedVehicles","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getAssociatedVehicles"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo":{"role":"symbol","title":"VehicleInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getAssociatedVehicles()":{"role":"symbol","title":"getAssociatedVehicles()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAssociatedVehicles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getAssociatedVehicles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAssociatedVehicles"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getassociatedvehicles()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getAssociatedVehicles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAssociatedVehicles"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<FairmaticVehicleInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getAssociatedVehicles"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/title","value":"FairmaticVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getAssociatedVehicles()\/title","value":"getAssociatedVehicles"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getAssociatedVehicles()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAssociatedVehicles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}