{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/directionofimpact\/rear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/directionofimpact\/rear"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/rear","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates a rear direction of impact"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"title":"DirectionOfImpact.rear","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact@FairmaticDirectionOfImpactRear","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact":{"role":"symbol","title":"DirectionOfImpact","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"abstract":[{"type":"text","text":"Direction of impact detected by SDK at the time of the accident"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/rear":{"role":"symbol","title":"DirectionOfImpact.rear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"abstract":[{"type":"text","text":"Indicates a rear direction of impact"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/rear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/rear"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDirectionOfImpactRear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/title","value":"FairmaticDirectionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1rear\/title","value":"FairmaticDirectionOfImpactRear"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1rear\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}