{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeDriveInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo","text":"ActiveDriveInfo"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The currently active drive information."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/activedriveinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/activedriveinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get info on the currently active drive. If sdk is not setup or if"},{"type":"text","text":" "},{"type":"text","text":"no drive is in progress, nil is returned."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeDriveInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActiveDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo"},{"kind":"text","text":"?"}],"title":"activeDriveInfo","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)Fairmatic(cpy)activeDriveInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"activeDriveInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/activeDriveInfo":{"role":"symbol","title":"activeDriveInfo","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeDriveInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActiveDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get info on the currently active drive. If sdk is not setup or if"},{"type":"text","text":" "},{"type":"text","text":"no drive is in progress, nil is returned."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activeDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/activedriveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo":{"role":"symbol","title":"ActiveDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveDriveInfo"}],"abstract":[{"type":"text","text":"Information about the active drive if any."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"activeDriveInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"activeDriveInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo","text":"FairmaticActiveDriveInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"activeDriveInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1activeDriveInfo\/title","value":"activeDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1activeDriveInfo\/fragments","value":[{"kind":"identifier","text":"activeDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo\/title","value":"FairmaticActiveDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticActiveDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}