{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/uploadalldebugdataandlogs()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmatic\/uploadalldebugdataandlogs()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/uploadAllDebugDataAndLogs()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Send a debug report of the current driver to Fairmatic."},{"type":"text","text":" "},{"type":"text","text":"The Fairmatic SDK will create a background task to ensure the"},{"type":"text","text":" "},{"type":"text","text":"completion of this upload task."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"},{"kind":"text","text":"()"}],"title":"uploadAllDebugDataAndLogs()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)Fairmatic(cm)uploadAllDebugDataAndLogs","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"uploadAllDebugDataAndLogs"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/uploadAllDebugDataAndLogs()":{"role":"symbol","title":"uploadAllDebugDataAndLogs()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Send a debug report of the current driver to Fairmatic."},{"type":"text","text":" "},{"type":"text","text":"The Fairmatic SDK will create a background task to ensure the"},{"type":"text","text":" "},{"type":"text","text":"completion of this upload task."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/uploadAllDebugDataAndLogs()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uploadAllDebugDataAndLogs"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/uploadalldebugdataandlogs()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"uploadAllDebugDataAndLogs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1uploadAllDebugDataAndLogs()\/title","value":"uploadAllDebugDataAndLogs"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1uploadAllDebugDataAndLogs()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}