{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentconfidence\/high"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentconfidence\/high"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Accident was detected with a high confidence. The application might inform"},{"type":"text","text":" "},{"type":"text","text":"emergency services directly after waiting for some time for user feedback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"title":"AccidentConfidence.high","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence@FairmaticAccidentConfidenceHigh","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/high":{"role":"symbol","title":"AccidentConfidence.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"Accident was detected with a high confidence. The application might inform"},{"type":"text","text":" "},{"type":"text","text":"emergency services directly after waiting for some time for user feedback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence\/high"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticAccidentConfidenceHigh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1high\/title","value":"FairmaticAccidentConfidenceHigh"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1high\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}