{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedLimitMPS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/speedingdata\/speedlimitmps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/speedingdata\/speedlimitmps"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/speedLimitMPS","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The speed limit in metres per second."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedLimitMPS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"speedLimitMPS","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticSpeedingData(py)speedLimitMPS","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"speedLimitMPS"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType/overSpeeding":{"role":"symbol","title":"EventType.overSpeeding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overSpeeding"}],"abstract":[{"type":"text","text":"This denotes the aggressive behavior of speeding more than allowed."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" in this case."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/overspeeding"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SpeedingData/speedLimitMPS":{"role":"symbol","title":"speedLimitMPS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedLimitMPS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The speed limit in metres per second."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/speedLimitMPS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speedLimitMPS"}],"url":"\/documentation\/fairmaticsdk\/speedingdata\/speedlimitmps"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SpeedingData":{"role":"symbol","title":"SpeedingData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpeedingData"}],"abstract":[{"type":"text","text":"A valid object of this class is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" "},{"type":"text","text":"whenever "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is equal to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpeedingData"}],"url":"\/documentation\/fairmaticsdk\/speedingdata"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/speedingData":{"role":"symbol","title":"speedingData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedingData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpeedingData","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSpeedingData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional data in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":", will be nil otherwise."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speedingData"}],"url":"\/documentation\/fairmaticsdk\/event\/speedingdata"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventType":{"role":"symbol","title":"eventType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"}],"abstract":[{"type":"text","text":"The type of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventType"}],"url":"\/documentation\/fairmaticsdk\/event\/eventtype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"speedLimitMPS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speedLimitMPS"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedLimitMPS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/title","value":"FairmaticventTypeOverSpeeding"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1speedLimitMPS\/title","value":"speedLimitMPS"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1speedLimitMPS\/fragments","value":[{"kind":"identifier","text":"speedLimitMPS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData\/title","value":"FairmaticSpeedingData"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData\/fragments","value":[{"kind":"identifier","text":"FairmaticSpeedingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/title","value":"speedingData"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/fragments","value":[{"kind":"identifier","text":"speedingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/title","value":"eventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/fragments","value":[{"kind":"identifier","text":"eventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}