{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fairmaticConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration","text":"Configuration"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/state\/fairmaticconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/state\/fairmaticconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State\/fairmaticConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The current configuration of the SDK."},{"type":"text","text":" "},{"type":"text","text":"Refer to "},{"type":"codeVoice","code":"Configuration"},{"type":"text","text":" for further details."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fairmaticConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration"},{"kind":"text","text":"!"}],"title":"fairmaticConfiguration","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticState(py)fairmaticConfiguration","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fairmaticConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/State/fairmaticConfiguration":{"role":"symbol","title":"fairmaticConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fairmaticConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The current configuration of the SDK."},{"type":"text","text":" "},{"type":"text","text":"Refer to "},{"type":"codeVoice","code":"Configuration"},{"type":"text","text":" for further details."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State\/fairmaticConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fairmaticConfiguration"}],"url":"\/documentation\/fairmaticsdk\/state\/fairmaticconfiguration"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/fairmaticsdk\/configuration"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/State":{"role":"symbol","title":"State","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"abstract":[{"type":"text","text":"Represents the current state of the Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"State"}],"url":"\/documentation\/fairmaticsdk\/state"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fairmaticConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fairmaticConfiguration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration","text":"FairmaticConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fairmaticConfiguration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State~1fairmaticConfiguration\/title","value":"fairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State~1fairmaticConfiguration\/fragments","value":[{"kind":"identifier","text":"fairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State\/title","value":"FairmaticState"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State\/fragments","value":[{"kind":"identifier","text":"FairmaticState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}