{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail","text":"ShiftDetail"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/state\/shiftdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/state\/shiftdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State\/shiftDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current value of businessHour."},{"type":"text","text":" "},{"type":"text","text":"businessHour is set when the SDK detects a change in the business hours set by the fleet manager and the current"},{"type":"text","text":" "},{"type":"text","text":"business hours applied on the SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftDetail","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail"},{"kind":"text","text":"?"}],"title":"shiftDetails","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticState(py)shiftDetails","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"shiftDetails"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/State":{"role":"symbol","title":"State","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"abstract":[{"type":"text","text":"Represents the current state of the Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"State"}],"url":"\/documentation\/fairmaticsdk\/state"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail":{"role":"symbol","title":"ShiftDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftDetail"}],"abstract":[{"type":"text","text":"Represents a shift comprising of shift intervals over the week."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftDetail"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/State/shiftDetails":{"role":"symbol","title":"shiftDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftDetail","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Current value of businessHour."},{"type":"text","text":" "},{"type":"text","text":"businessHour is set when the SDK detects a change in the business hours set by the fleet manager and the current"},{"type":"text","text":" "},{"type":"text","text":"business hours applied on the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/State\/shiftDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shiftDetails"}],"url":"\/documentation\/fairmaticsdk\/state\/shiftdetails"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shiftDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shiftDetails"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail","text":"FairmaticShiftDetail"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shiftDetails"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State\/title","value":"FairmaticState"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State\/fragments","value":[{"kind":"identifier","text":"FairmaticState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/title","value":"FairmaticShiftDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftDetail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State~1shiftDetails\/title","value":"shiftDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1State~1shiftDetails\/fragments","value":[{"kind":"identifier","text":"shiftDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}