{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/unknownerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/unknownerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/unknownError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An unknown error occured in the Vehicle Tagging APIs. Please get in touch your contact at Fairmatic for further assistance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"title":"FairmaticVehicleTaggingError.unknownError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticVehicleTaggingError@FairmaticVehicleTaggingErrorUnknownError","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorUnknownError"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticVehicleTaggingError":{"role":"symbol","title":"FairmaticVehicleTaggingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"abstract":[{"type":"text","text":"Error returned as code to "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"},{"type":"text","text":" public APIs in case of failures."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticVehicleTaggingError/unknownError":{"role":"symbol","title":"FairmaticVehicleTaggingError.unknownError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"abstract":[{"type":"text","text":"An unknown error occured in the Vehicle Tagging APIs. Please get in touch your contact at Fairmatic for further assistance."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/unknownError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorUnknownError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/unknownerror"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticVehicleTaggingErrorUnknownError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorUnknownError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorUnknownError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/title","value":"FairmaticVehicleTaggingError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1unknownError\/title","value":"FairmaticVehicleTaggingErrorUnknownError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1unknownError\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorUnknownError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}