{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityPermissionNotAuthorized"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"if the current drive detection is "},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON"},{"type":"text","text":", this"},{"type":"text","text":" "},{"type":"text","text":"error will not be thrown."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/settingserrortype\/activitypermissionnotauthorized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/settingserrortype\/activitypermissionnotauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SettingsErrorType\/activityPermissionNotAuthorized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The activity authorization status is determined but the user has "},{"type":"strong","inlineContent":[{"type":"text","text":"not authorized"}]},{"type":"text","text":" application to"},{"type":"text","text":" "},{"type":"text","text":"access the motion and fitness data. This error will only be thrown if activity based trip detection"},{"type":"text","text":" "},{"type":"text","text":"is enabled for the application."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityPermissionNotAuthorized"}],"title":"SettingsErrorType.activityPermissionNotAuthorized","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticSettingsErrorType@FairmaticSettingsErrorTypeActivityPermissionNotAuthorized","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SettingsErrorType"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SettingsError":{"role":"symbol","title":"SettingsError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsError"}],"abstract":[{"type":"text","text":"This class represent an error in device or application settings that is affecting"},{"type":"text","text":" "},{"type":"text","text":"the ability of the SDK to detect trips."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SettingsError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsError"}],"url":"\/documentation\/fairmaticsdk\/settingserror"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SettingsErrorType/activityPermissionNotAuthorized":{"role":"symbol","title":"SettingsErrorType.activityPermissionNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityPermissionNotAuthorized"}],"abstract":[{"type":"text","text":"The activity authorization status is determined but the user has "},{"type":"strong","inlineContent":[{"type":"text","text":"not authorized"}]},{"type":"text","text":" application to"},{"type":"text","text":" "},{"type":"text","text":"access the motion and fitness data. This error will only be thrown if activity based trip detection"},{"type":"text","text":" "},{"type":"text","text":"is enabled for the application."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SettingsErrorType\/activityPermissionNotAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype\/activitypermissionnotauthorized"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/autoON":{"role":"symbol","title":"DriveDetectionMode.autoON","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoON"}],"abstract":[{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK will automatically track drives in background in"},{"type":"text","text":" "},{"type":"text","text":"this mode once the SDK is setup. At the same time, the application can invoke"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" to explicitly start recording a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoON"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/autoon"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SettingsErrorType":{"role":"symbol","title":"SettingsErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsErrorType"}],"abstract":[{"type":"text","text":"Error type for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SettingsError"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SettingsErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsErrorType"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SettingsError\/title","value":"FairmaticSettingsError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SettingsError\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SettingsErrorType~1activityPermissionNotAuthorized\/title","value":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SettingsErrorType~1activityPermissionNotAuthorized\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoON\/title","value":"FairmaticDriveDetectionModeAutoON"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoON\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoON"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SettingsErrorType\/title","value":"FairmaticSettingsErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SettingsErrorType\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}