{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType","text":"DriveType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A drive callback will be sent even for falsely detected drives or for non"},{"type":"text","text":" "},{"type":"text","text":"automobile trips (Eg. biking, public transport)."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/drivetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/drivetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"title":"driveType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveInfo(py)driveType","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"driveType"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType":{"role":"symbol","title":"DriveType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveType"}],"abstract":[{"type":"text","text":"The type of the drive returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveType"}],"url":"\/documentation\/fairmaticsdk\/drivetype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"driveType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType","text":"FairmaticDriveType"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType\/title","value":"FairmaticDriveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}