{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"AccidentConfidence"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"confidence","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any value from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence"},{"type":"text","text":" enum."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"While invoking this method on a simulator, make sure your are simulating"},{"type":"text","text":" "},{"type":"text","text":"location (In Simulator menu bar, select Features->Location->Apple)."}]}],"type":"aside","name":"Warning"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in"},{"type":"text","text":" "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" mode, disabled in "},{"type":"codeVoice","code":"RELEASE"},{"type":"text","text":" mode."},{"type":"text","text":" "},{"type":"text","text":"On invoking this method, you will get an accident callback finalId on your"},{"type":"text","text":" "},{"type":"text","text":"delegate after 5 seconds. You can look at console logs for debugging in case you"},{"type":"text","text":" "},{"type":"text","text":"do not receive the callback. If issue persists, reach out to your contact at Fairmatic."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"raiseMockAccident:"}],"role":"symbol","title":"raiseMockAccident(_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticTest(cm)raiseMockAccident:","modules":[{"name":"FairmaticSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(_:)":{"role":"symbol","title":"raiseMockAccident(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in"},{"type":"text","text":" "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" mode, disabled in "},{"type":"codeVoice","code":"RELEASE"},{"type":"text","text":" mode."},{"type":"text","text":" "},{"type":"text","text":"On invoking this method, you will get an accident callback finalId on your"},{"type":"text","text":" "},{"type":"text","text":"delegate after 5 seconds. You can look at console logs for debugging in case you"},{"type":"text","text":" "},{"type":"text","text":"do not receive the callback. If issue persists, reach out to your contact at Fairmatic."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccident:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticTest":{"role":"symbol","title":"FairmaticTest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticTest"}],"abstract":[{"type":"text","text":"This class contains methods that mock Fairmatic’s functionality for testing purposes."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticTest"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"raiseMockAccident:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccident:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"raiseMockAccident:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"FairmaticAccidentConfidence"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(_:)\/title","value":"raiseMockAccident:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccident:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest\/title","value":"FairmaticTest"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest\/fragments","value":[{"kind":"identifier","text":"FairmaticTest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}