{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mount"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/phoneposition\/mount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/phoneposition\/mount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition\/mount","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The case when "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was able to determine confidently that the phone was on mount during a trip."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mount"}],"title":"PhonePosition.mount","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticPhonePosition@FairmaticPhonePositionMount","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticPhonePositionMount"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/PhonePosition/mount":{"role":"symbol","title":"PhonePosition.mount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mount"}],"abstract":[{"type":"text","text":"The case when "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was able to determine confidently that the phone was on mount during a trip."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition\/mount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPhonePositionMount"}],"url":"\/documentation\/fairmaticsdk\/phoneposition\/mount"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/PhonePosition":{"role":"symbol","title":"PhonePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhonePosition"}],"abstract":[{"type":"text","text":"The types of phone positions during a trip."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhonePosition"}],"url":"\/documentation\/fairmaticsdk\/phoneposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticPhonePositionMount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticPhonePositionMount"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticPhonePositionMount"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition~1mount\/title","value":"FairmaticPhonePositionMount"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition~1mount\/fragments","value":[{"kind":"identifier","text":"FairmaticPhonePositionMount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition\/title","value":"FairmaticPhonePosition"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition\/fragments","value":[{"kind":"identifier","text":"FairmaticPhonePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}