{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"? = nil) -> "},{"kind":"keyword","text":"Any"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/copy(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/copy(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/copy(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a copy of Fairmatic "},{"type":"codeVoice","code":"MockAccidentConfig"},{"type":"text","text":" object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"title":"copy(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig(im)copyWithZone:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Creates a copy of Fairmatic "},{"type":"codeVoice","code":"MockAccidentConfig"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/copy(with:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig":{"role":"symbol","title":"MockAccidentConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(using:)":{"role":"symbol","title":"raiseMockAccident(using:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockAccidentConfig","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" mode,"},{"type":"text","text":" "},{"type":"text","text":"disabled in "},{"type":"codeVoice","code":"RELEASE"},{"type":"text","text":" mode."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccidentUsing:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(using:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"copyWithZone:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/title","value":"raiseMockAccidentUsing:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccidentUsing:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}