{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact","text":"DirectionOfImpact"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default value is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/unknown"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/directionofimpact"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/directionofimpact"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/directionOfImpact","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This field specifies the direction of impact at the time of potential accident callback and final accident callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact"}],"title":"directionOfImpact","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig(py)directionOfImpact","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"directionOfImpact"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig/directionOfImpact":{"role":"symbol","title":"directionOfImpact","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact"}],"abstract":[{"type":"text","text":"This field specifies the direction of impact at the time of potential accident callback and final accident callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/directionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"directionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/directionofimpact"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig":{"role":"symbol","title":"MockAccidentConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact":{"role":"symbol","title":"DirectionOfImpact","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"abstract":[{"type":"text","text":"Direction of impact detected by SDK at the time of the accident"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/unknown":{"role":"symbol","title":"DirectionOfImpact.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Indicates an unknown direction of impact"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactUnknown"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/unknown"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(using:)":{"role":"symbol","title":"raiseMockAccident(using:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockAccidentConfig","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" mode,"},{"type":"text","text":" "},{"type":"text","text":"disabled in "},{"type":"codeVoice","code":"RELEASE"},{"type":"text","text":" mode."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccidentUsing:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(using:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"directionOfImpact"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"directionOfImpact"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact","text":"FairmaticDirectionOfImpact"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionOfImpact"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1directionOfImpact\/title","value":"directionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1directionOfImpact\/fragments","value":[{"kind":"identifier","text":"directionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/title","value":"FairmaticDirectionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1unknown\/title","value":"FairmaticDirectionOfImpactUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1unknown\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/title","value":"raiseMockAccidentUsing:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccidentUsing:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}