{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalAccidentConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"AccidentConfidence"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default value is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/finalaccidentconfidence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/finalaccidentconfidence"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This field specifies the confidence for the final accident callback - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalAccidentConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"}],"title":"finalAccidentConfidence","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig(py)finalAccidentConfidence","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"finalAccidentConfidence"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig":{"role":"symbol","title":"MockAccidentConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/high":{"role":"symbol","title":"AccidentConfidence.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"Accident was detected with a high confidence. The application might inform"},{"type":"text","text":" "},{"type":"text","text":"emergency services directly after waiting for some time for user feedback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence\/high"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processAccidentDetected(_:)":{"navigatorTitle":[{"kind":"identifier","text":"processAccidentDetected:"}],"role":"symbol","title":"processAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is fired on the main thread when an accident is detected by"},{"type":"text","text":" "},{"type":"text","text":"the SDK during a drive. Any ongoing auto-detected\/manual drives will be stopped"},{"type":"text","text":" "},{"type":"text","text":"after this point."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(using:)":{"role":"symbol","title":"raiseMockAccident(using:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockAccidentConfig","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" mode,"},{"type":"text","text":" "},{"type":"text","text":"disabled in "},{"type":"codeVoice","code":"RELEASE"},{"type":"text","text":" mode."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccidentUsing:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(using:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig/finalAccidentConfidence":{"role":"symbol","title":"finalAccidentConfidence","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalAccidentConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"}],"abstract":[{"type":"text","text":"This field specifies the confidence for the final accident callback - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalAccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/finalaccidentconfidence"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"finalAccidentConfidence"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"finalAccidentConfidence"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"FairmaticAccidentConfidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalAccidentConfidence"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1high\/title","value":"FairmaticAccidentConfidenceHigh"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1high\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/title","value":"processAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/title","value":"raiseMockAccidentUsing:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccidentUsing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1finalAccidentConfidence\/title","value":"finalAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1finalAccidentConfidence\/fragments","value":[{"kind":"identifier","text":"finalAccidentConfidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}