{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateFinalCallback"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Invalidating final callbacks have confidence number as 0 and confidence as "},{"type":"codeVoice","code":"AccidentConfidence.invalid"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"signifying that the accident send out via the potential accident callback on further analysis has been reclassified as "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" being an accident."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/invalidatefinalcallback()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/invalidatefinalcallback()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method causes the final callback to invalidate the potential callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateFinalCallback"},{"kind":"text","text":"()"}],"title":"invalidateFinalCallback()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig(im)invalidateFinalCallback","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"invalidateFinalCallback"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(using:)":{"role":"symbol","title":"raiseMockAccident(using:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockAccidentConfig","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" mode,"},{"type":"text","text":" "},{"type":"text","text":"disabled in "},{"type":"codeVoice","code":"RELEASE"},{"type":"text","text":" mode."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccidentUsing:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(using:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig/invalidateFinalCallback()":{"role":"symbol","title":"invalidateFinalCallback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateFinalCallback"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method causes the final callback to invalidate the potential callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateFinalCallback"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/invalidatefinalcallback()"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig":{"role":"symbol","title":"MockAccidentConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"invalidateFinalCallback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateFinalCallback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"invalidateFinalCallback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/title","value":"raiseMockAccidentUsing:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccidentUsing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1invalidateFinalCallback()\/title","value":"invalidateFinalCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1invalidateFinalCallback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateFinalCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}