{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPeriod"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod\/noperiod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod\/noperiod"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod\/noPeriod","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Applications that do not use insurance APIs will have drives with"},{"type":"text","text":" "},{"type":"text","text":"this value for insurance period"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPeriod"}],"title":"InsurancePeriod.noPeriod","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod@FairmaticInsurancePeriodNoPeriod","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/InsurancePeriod":{"role":"symbol","title":"InsurancePeriod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InsurancePeriod"}],"abstract":[{"type":"text","text":"The types of insurance period in "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InsurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/InsurancePeriod/noPeriod":{"role":"symbol","title":"InsurancePeriod.noPeriod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPeriod"}],"abstract":[{"type":"text","text":"Applications that do not use insurance APIs will have drives with"},{"type":"text","text":" "},{"type":"text","text":"this value for insurance period"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod\/noPeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/noperiod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticInsurancePeriodNoPeriod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod\/title","value":"FairmaticInsurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod~1noPeriod\/title","value":"FairmaticInsurancePeriodNoPeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod~1noPeriod\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}