{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period1"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod\/period1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod\/period1"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod\/period1","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Drives detected in insurance period 1 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod1:)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period1"}],"title":"InsurancePeriod.period1","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod@FairmaticInsurancePeriodPeriod1","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticInsurance/startDrive(withPeriod1:)":{"role":"symbol","title":"startDrive(withPeriod1:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 1 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod1:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod1:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticinsurance\/startdrive(withperiod1:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/InsurancePeriod/period1":{"role":"symbol","title":"InsurancePeriod.period1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period1"}],"abstract":[{"type":"text","text":"Drives detected in insurance period 1 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod1:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod\/period1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/period1"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/InsurancePeriod":{"role":"symbol","title":"InsurancePeriod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InsurancePeriod"}],"abstract":[{"type":"text","text":"The types of insurance period in "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/InsurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InsurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticInsurancePeriodPeriod1"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod1:)\/title","value":"startDriveWithPeriod1:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod1:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod1:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod~1period1\/title","value":"FairmaticInsurancePeriodPeriod1"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod~1period1\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod\/title","value":"FairmaticInsurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1InsurancePeriod\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}