{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/collisionseverity\/low"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/collisionseverity\/low"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/low","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Low severity collision"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"title":"CollisionSeverity.low","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity@FairmaticCollisionSeverityLow","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity":{"role":"symbol","title":"CollisionSeverity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollisionSeverity"}],"abstract":[{"type":"text","text":"Collision severity of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollisionSeverity"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/low":{"role":"symbol","title":"CollisionSeverity.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[{"type":"text","text":"Low severity collision"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity\/low"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticCollisionSeverityLow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity\/title","value":"FairmaticCollisionSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1low\/title","value":"FairmaticCollisionSeverityLow"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1low\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}