{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime","text":"ShiftTime"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shiftinterval\/starttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shiftinterval\/starttime"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/startTime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Start time of the shift interval, indicates when the shift interval starts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime"}],"title":"startTime","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval(py)startTime","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"startTime"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval":{"role":"symbol","title":"ShiftInterval","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftInterval"}],"abstract":[{"type":"text","text":"Wrapper for a single business hour interval."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftInterval"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval/startTime":{"role":"symbol","title":"startTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime"}],"abstract":[{"type":"text","text":"Start time of the shift interval, indicates when the shift interval starts."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/startTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval\/starttime"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime":{"role":"symbol","title":"ShiftTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftTime"}],"abstract":[{"type":"text","text":"Represents a particular day and time in a weekly schedule, The shift time is represented in 24 hour time format."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftTime"}],"url":"\/documentation\/fairmaticsdk\/shifttime"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"startTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"startTime"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime","text":"FairmaticShiftTime"},{"kind":"text","text":" * "},{"kind":"identifier","text":"startTime"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/title","value":"FairmaticShiftInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1startTime\/title","value":"startTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1startTime\/fragments","value":[{"kind":"identifier","text":"startTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/title","value":"FairmaticShiftTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftTime"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}