{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/scannedbeaconinfo\/accuracy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/scannedbeaconinfo\/accuracy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/accuracy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The accuracy of the proximity value, measured in meters from the beacon."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"}],"title":"accuracy","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo(py)accuracy","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"accuracy"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/accuracy":{"role":"symbol","title":"accuracy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"}],"abstract":[{"type":"text","text":"The accuracy of the proximity value, measured in meters from the beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/accuracy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accuracy"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/accuracy"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getNearbyBeacons(uuid:major:minor:completionHandler:)":{"role":"symbol","title":"getNearbyBeacons(uuid:major:minor:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNearbyBeacons"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scannedBeacons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScannedBeaconInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get all the beacons which are in the device’s range."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getnearbybeacons(uuid:major:minor:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo":{"role":"symbol","title":"ScannedBeaconInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScannedBeaconInfo"}],"abstract":[{"type":"text","text":"Wrapper for beacons scanned using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScannedBeaconInfo"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accuracy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accuracy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1accuracy\/title","value":"accuracy"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1accuracy\/fragments","value":[{"kind":"identifier","text":"accuracy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/title","value":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo\/title","value":"FairmaticScannedBeaconInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticScannedBeaconInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}