{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticBluetoothDevice) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothDevice"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/bluetoothdevice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/bluetoothdevice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrapper to describe a bluetooth device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothDevice"}],"title":"BluetoothDevice","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticBluetoothDevice","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"BluetoothDevice"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice\/identifier","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice\/name"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/BluetoothDevice/identifier":{"role":"symbol","title":"identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The mac address of the bluetooth device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice\/identifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"url":"\/documentation\/fairmaticsdk\/bluetoothdevice\/identifier"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/BluetoothDevice":{"role":"symbol","title":"BluetoothDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothDevice"}],"abstract":[{"type":"text","text":"Wrapper to describe a bluetooth device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BluetoothDevice"}],"url":"\/documentation\/fairmaticsdk\/bluetoothdevice"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/BluetoothDevice/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The name of the bluetooth device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/fairmaticsdk\/bluetoothdevice\/name"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticBluetoothDevice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticBluetoothDevice"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticBluetoothDevice"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice\/identifier","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice\/name"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticBluetoothDevice"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice\/title","value":"FairmaticBluetoothDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice\/fragments","value":[{"kind":"identifier","text":"FairmaticBluetoothDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice~1name\/fragments","value":[{"kind":"identifier","text":"name"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}