{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriverAttributes) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributes"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The application can specify both predefined and custom attributes for a driver."},{"type":"text","text":" "},{"type":"text","text":"These attributes are associated with a SDK "},{"type":"codeVoice","code":"driverId"},{"type":"text","text":" at SDK initialization time."},{"type":"text","text":" "},{"type":"text","text":"In addition to predefined special attributes, up to 4 custom key value attributes"},{"type":"text","text":" "},{"type":"text","text":"can be associated with a driver using the Fairmatic SDK."}]},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"All attribute keys can be atmost 64 characters in length."}]}],"type":"aside","name":"Warning"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"All attribute values can be atmost 1024 characters in length."}]}],"type":"aside","name":"Warning"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driverattributes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driverattributes"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Additional attributes of a "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" driver."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributes"}],"title":"DriverAttributes","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriverAttributes"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/init()"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asDictionary()","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setAlias(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setCustomAttribute(_:forKey:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setEmailId(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setGroup(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setPhoneNumber(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setServiceLevel(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setAlias(_:)":{"role":"symbol","title":"setAlias(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAlias"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Alias is a string placeholder offered as a convenience"},{"type":"text","text":" "},{"type":"text","text":"for developers to create a reference for a driver"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setAlias(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAlias:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setalias(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/asDictionary()":{"role":"symbol","title":"asDictionary()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asDictionary"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns the driver attributes as a dictionary."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asDictionary()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"asDictionary"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/asdictionary()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setCustomAttribute(_:forKey:)":{"role":"symbol","title":"setCustomAttribute(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomAttribute"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the custom attribute of the user."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setCustomAttribute(_:forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCustomAttribute:forKey:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setcustomattribute(_:forkey:)"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setGroup(_:)":{"role":"symbol","title":"setGroup(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGroup"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A unique id that associates the current user to a group. This groupId will"},{"type":"text","text":" "},{"type":"text","text":"be made available as a query parameter to filter users in the reports and API that"},{"type":"text","text":" "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" provides."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setGroup(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setGroup:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setgroup(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setPhoneNumber(_:)":{"role":"symbol","title":"setPhoneNumber(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPhoneNumber"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set the phone number for the current driver"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setPhoneNumber(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPhoneNumber:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setphonenumber(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setServiceLevel(_:)":{"role":"symbol","title":"setServiceLevel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setServiceLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ServiceLevel","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticServiceLevel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"The service level of a driver. This is useful for applications where "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" supports"},{"type":"text","text":" "},{"type":"text","text":"different service levels for different drivers. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel"},{"type":"text","text":" "},{"type":"text","text":"for more information about this attribute."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setServiceLevel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setServiceLevel:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setservicelevel(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Creates a "},{"type":"codeVoice","code":"DriverAttributes"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/init()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleType/car":{"role":"symbol","title":"VehicleType.car","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"car"}],"abstract":[{"type":"text","text":"Indicates a car vehicle type."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleType\/car","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTypeCar"}],"url":"\/documentation\/fairmaticsdk\/vehicletype\/car"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel":{"role":"symbol","title":"ServiceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceLevel"}],"abstract":[{"type":"text","text":"Enumeration for different service levels supported by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" for a driver."},{"type":"text","text":" "},{"type":"text","text":"By default, drivers will be assigned to the default service level - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceLevel"}],"url":"\/documentation\/fairmaticsdk\/servicelevel"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setVehicleType(_:)":{"role":"symbol","title":"setVehicleType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVehicleType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the vehicle type for the driver."},{"type":"text","text":" "},{"type":"text","text":"To enable the feature for any vehicle type other than "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleType\/car"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"please reach out to your contact at Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVehicleType:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setvehicletype(_:)"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes":{"role":"symbol","title":"DriverAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributes"}],"abstract":[{"type":"text","text":"Additional attributes of a "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" driver."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriverAttributes"}],"url":"\/documentation\/fairmaticsdk\/driverattributes"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/setEmailId(_:)":{"role":"symbol","title":"setEmailId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmailId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set the email for the current driver"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setEmailId(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setEmailId:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setemailid(_:)"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/asJson()":{"role":"symbol","title":"asJson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns driver attributes as a json string. Empty string if json serialization"},{"type":"text","text":" "},{"type":"text","text":"fails."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"asJson"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/asjson()"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriverAttributes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributes"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriverAttributes"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asDictionary()","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/init()","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setAlias(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setCustomAttribute(_:forKey:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setEmailId(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setGroup(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setPhoneNumber(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setServiceLevel(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriverAttributes"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setAlias(_:)\/title","value":"setAlias:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setAlias(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAlias:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asDictionary()\/title","value":"asDictionary"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asDictionary()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setCustomAttribute(_:forKey:)\/title","value":"setCustomAttribute:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setCustomAttribute(_:forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomAttribute:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setGroup(_:)\/title","value":"setGroup:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setGroup(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setGroup:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setPhoneNumber(_:)\/title","value":"setPhoneNumber:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setPhoneNumber(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPhoneNumber:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setServiceLevel(_:)\/title","value":"setServiceLevel:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setServiceLevel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setServiceLevel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleType~1car\/title","value":"FairmaticVehicleTypeCar"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleType~1car\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTypeCar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/title","value":"FairmaticServiceLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setVehicleType(_:)\/title","value":"setVehicleType:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setVehicleType(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVehicleType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes\/title","value":"FairmaticDriverAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setEmailId(_:)\/title","value":"setEmailId:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1setEmailId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEmailId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/title","value":"asJson"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asJson"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}