{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriverAttributesKeys) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributesKeys"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driverattributeskeys"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driverattributeskeys"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Keys for various properties returned by toJson method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributesKeys"}],"title":"DriverAttributesKeys","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributesKeys","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriverAttributesKeys"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyAlias","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyEmail","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyGroup","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyPhone","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyPriority"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/driverAttributesKeyGroup":{"role":"symbol","title":"driverAttributesKeyGroup","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for groupId returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyGroup"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeygroup"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/driverAttributesKeyEmail":{"role":"symbol","title":"driverAttributesKeyEmail","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for driver email returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyEmail"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeyemail"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys":{"role":"symbol","title":"DriverAttributesKeys","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributesKeys"}],"abstract":[{"type":"text","text":"Keys for various properties returned by toJson method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriverAttributesKeys"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/driverAttributesKeyPhone":{"role":"symbol","title":"driverAttributesKeyPhone","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyPhone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for driver phone returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyPhone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyPhone"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeyphone"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/driverAttributesKeyAlias":{"role":"symbol","title":"driverAttributesKeyAlias","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyAlias"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for driver alias returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyAlias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyAlias"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeyalias"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/init"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributesKeys/driverAttributesKeyPriority":{"role":"symbol","title":"driverAttributesKeyPriority","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributesKeyPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for ServiceLevel returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributesKeyPriority"}],"url":"\/documentation\/fairmaticsdk\/driverattributeskeys\/driverattributeskeypriority"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriverAttributes/asJson()":{"role":"symbol","title":"asJson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns driver attributes as a json string. Empty string if json serialization"},{"type":"text","text":" "},{"type":"text","text":"fails."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/asJson()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"asJson"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/asjson()"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriverAttributesKeys"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributesKeys"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriverAttributesKeys"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyAlias","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyEmail","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyGroup","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyPhone","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributesKeys\/driverAttributesKeyPriority"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriverAttributesKeys"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyGroup\/title","value":"driverAttributesKeyGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyGroup\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyEmail\/title","value":"driverAttributesKeyEmail"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyEmail\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys\/title","value":"FairmaticDriverAttributesKeys"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributesKeys"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyPhone\/title","value":"driverAttributesKeyPhone"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyPhone\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyPhone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyAlias\/title","value":"driverAttributesKeyAlias"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyAlias\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyAlias"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyPriority\/title","value":"driverAttributesKeyPriority"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributesKeys~1driverAttributesKeyPriority\/fragments","value":[{"kind":"identifier","text":"driverAttributesKeyPriority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/title","value":"asJson"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriverAttributes~1asJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asJson"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}