{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticError) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticError"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In case you are using Objective-C, the errors would be returned as "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" objects. In that case, you can use the "},{"type":"codeVoice","code":"code"},{"type":"text","text":" of the "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" to get the appropriate "},{"type":"codeVoice","code":"FairmaticError"}]},{"type":"codeListing","syntax":"objc","code":["\/\/ Considering that the name of the variable is `nsError`,","\/\/ you can check the proper error code","\/\/ using the following format:","long code = (long) nsError.code","NSString *errorDescription = nsError.localizedDescription","NSLog(errorDescription)","","if (errorCode == FairmaticErrorNotSetup) {","    NSLog(@\"Fairmatic SDK is not setup\");","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also cast the "},{"type":"codeVoice","code":"code"},{"type":"text","text":" of the error to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError"},{"type":"text","text":" enum to get the enum value like:"}]},{"type":"codeListing","syntax":"objc","code":["FairmaticError errorCode = (FairmaticError) nsError.code","switch (fmError) {","    case FairmaticErrorNotSetup:","        NSLog(@\"Fairmatic SDK is not setup\");","        break;","    default:","        break;","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/10Foundation14LocalizedErrorP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/s5ErrorP","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY","doc:\/\/com.fairmatic.Fairmatic\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error returned as code of "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" public APIs in case of"},{"type":"text","text":" "},{"type":"text","text":"failures."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticError"}],"title":"FairmaticError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticError","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticError"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/beaconNotFound","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/deviceUnsupported","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/expiredPausedTillTimestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/insurancePeriodSame","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/internalFailure","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidBeaconUUID","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidParams","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidRegion","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidSDKKeyString","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidTrackingId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/ioError","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/maxBeaconLimitReached","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/networkUnreachable","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notSetup","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notTornDown","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursFeatureNotEnabled","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursNetworkNotAvailable","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursTimeout","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/regionUnsupported","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/sdkNotEnabled","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unauthorizedRegionSwitch","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unsupportedOSVersion","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unsupportedVehicleType","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/userDeprovisioned"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/Error-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/LocalizedError-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/refreshBusinessHoursTimeout":{"role":"symbol","title":"FairmaticError.refreshBusinessHoursTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshBusinessHoursTimeout"}],"abstract":[{"type":"text","text":"This error is thrown when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/refreshBusinessHours(completionHandler:)"},{"type":"text","text":" is timed out."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorRefreshBusinessHoursTimeout"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/refreshbusinesshourstimeout"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/expiredPausedTillTimestamp":{"role":"symbol","title":"FairmaticError.expiredPausedTillTimestamp","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiredPausedTillTimestamp"}],"abstract":[{"type":"codeVoice","code":"pausedTillTimestamp"},{"type":"text","text":" parameter passed to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/pauseAutoTracking(_:completion:)"},{"type":"text","text":" API must be in future"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/expiredPausedTillTimestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorExpiredPausedTillTimestamp"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/expiredpausedtilltimestamp"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticInsurance/startDrive(withPeriod2:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod2:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 2 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod2:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticinsurance\/startdrive(withperiod2:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError":{"role":"symbol","title":"FairmaticError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticError"}],"abstract":[{"type":"text","text":"Error returned as code of "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" public APIs in case of"},{"type":"text","text":" "},{"type":"text","text":"failures."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/beaconNotFound":{"role":"symbol","title":"FairmaticError.beaconNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"beaconNotFound"}],"abstract":[{"type":"text","text":"Failed to remove beacon as beacon was not found."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/beaconNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorBeaconNotFound"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/beaconnotfound"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/invalidTrackingId":{"role":"symbol","title":"FairmaticError.invalidTrackingId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTrackingId"}],"abstract":[{"type":"text","text":"Invalid "},{"type":"codeVoice","code":"trackingId"},{"type":"text","text":" passed for new drive. This error may be returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod2:completionHandler:)"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod3:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidTrackingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInvalidTrackingId"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/invalidtrackingid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticerror\/localizederror-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/invalidSDKKeyString":{"role":"symbol","title":"FairmaticError.invalidSDKKeyString","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSDKKeyString"}],"abstract":[{"type":"text","text":"SDK Key used in setup is invalid"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidSDKKeyString","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInvalidSDKKeyString"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/invalidsdkkeystring"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/invalidBeaconUUID":{"role":"symbol","title":"FairmaticError.invalidBeaconUUID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidBeaconUUID"}],"abstract":[{"type":"text","text":"Failed to register beacon due to invalid UUID string."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidBeaconUUID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInvalidBeaconUUID"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/invalidbeaconuuid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/notSetup":{"role":"symbol","title":"FairmaticError.notSetup","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"abstract":[{"type":"text","text":"Fairmatic SDK is not setup. This error is also returned in case SDK setup"},{"type":"text","text":" "},{"type":"text","text":"has started but completion handler for setup is not called yet."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notSetup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorNotSetup"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/notsetup"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s5ErrorP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/maxBeaconLimitReached":{"role":"symbol","title":"FairmaticError.maxBeaconLimitReached","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBeaconLimitReached"}],"abstract":[{"type":"text","text":"maximum number of beacons registered for a given user has been reached."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/maxBeaconLimitReached","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorMaxBeaconLimitReached"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/maxbeaconlimitreached"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticInsurance/startDrive(withPeriod1:)":{"role":"symbol","title":"startDrive(withPeriod1:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 1 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod1:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod1:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticinsurance\/startdrive(withperiod1:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/invalidParams":{"role":"symbol","title":"FairmaticError.invalidParams","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidParams"}],"abstract":[{"type":"text","text":"Invalid parameter was passed to the API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInvalidParams"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/invalidparams"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/sdkNotEnabled":{"role":"symbol","title":"FairmaticError.sdkNotEnabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkNotEnabled"}],"abstract":[{"type":"text","text":"This error is thrown when the Fairmatic SDK is not enabled for the current customer. Please get in touch with your contact at Fairmatic to get it enabled and then retry the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)"},{"type":"text","text":" API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/sdkNotEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorSdkNotEnabled"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/sdknotenabled"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticerror\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/regionUnsupported":{"role":"symbol","title":"FairmaticError.regionUnsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionUnsupported"}],"abstract":[{"type":"text","text":"Operation Failed because provided "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region"},{"type":"text","text":" is not supported for this application."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/regionUnsupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorRegionUnsupported"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/regionunsupported"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/unsupportedVehicleType":{"role":"symbol","title":"FairmaticError.unsupportedVehicleType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedVehicleType"}],"abstract":[{"type":"text","text":"Operation failed because the set vehicle type feature is disabled in the config."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unsupportedVehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorUnsupportedVehicleType"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/unsupportedvehicletype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/invalidRegion":{"role":"symbol","title":"FairmaticError.invalidRegion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidRegion"}],"abstract":[{"type":"text","text":"Operation failed because "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region"},{"type":"text","text":" provided was invalid."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidRegion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInvalidRegion"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/invalidregion"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticerror\/error-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/refreshBusinessHoursNetworkNotAvailable":{"role":"symbol","title":"FairmaticError.refreshBusinessHoursNetworkNotAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshBusinessHoursNetworkNotAvailable"}],"abstract":[{"type":"text","text":"this error is thrown in case of network unavailability when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/refreshBusinessHours(completionHandler:)"},{"type":"text","text":" is called."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursNetworkNotAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorRefreshBusinessHoursNetworkNotAvailable"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/refreshbusinesshoursnetworknotavailable"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/pauseAutoTracking(_:completion:)":{"role":"symbol","title":"pauseAutoTracking(_:completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAutoTracking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"After success of this method request, automatic trip detection by the SDK will be paused till "},{"type":"codeVoice","code":"pausedTillTimestamp"},{"type":"text","text":" which will be provided as part of the parameter."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/pauseAutoTracking(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pauseAutoTracking:completion:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/pauseautotracking(_:completion:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/notTornDown":{"role":"symbol","title":"FairmaticError.notTornDown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notTornDown"}],"abstract":[{"type":"text","text":"Fairmatic SDK is not torn down. This error is returned if the requested operation cannot"},{"type":"text","text":" "},{"type":"text","text":"be completed while the SDK is running like the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)"},{"type":"text","text":" API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notTornDown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorNotTornDown"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/nottorndown"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/internalFailure":{"role":"symbol","title":"FairmaticError.internalFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"}],"abstract":[{"type":"text","text":"Internal error."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/internalFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInternalFailure"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/internalfailure"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/networkUnreachable":{"role":"symbol","title":"FairmaticError.networkUnreachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkUnreachable"}],"abstract":[{"type":"text","text":"Network not reachable, Fairmatic.setup sometimes needs network call"},{"type":"text","text":" "},{"type":"text","text":"for authentication and to update SDK configuration to work. This error"},{"type":"text","text":" "},{"type":"text","text":"is returned whenever network is not available in these scenarios."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/networkUnreachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorNetworkUnreachable"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/networkunreachable"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticerror\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/unauthorizedRegionSwitch":{"role":"symbol","title":"FairmaticError.unauthorizedRegionSwitch","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthorizedRegionSwitch"}],"abstract":[{"type":"text","text":"Changing region post setup is NOT allowed, until "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)"},{"type":"text","text":" is called."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unauthorizedRegionSwitch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorUnauthorizedRegionSwitch"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/unauthorizedregionswitch"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/ioError":{"role":"symbol","title":"FairmaticError.ioError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ioError"}],"abstract":[{"type":"text","text":"Some IO error occured while doing the operation. Refer to error description for more info."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/ioError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorIoError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/ioerror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticInsurance/startDrive(withPeriod3:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod3:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod3"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 3 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod3:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticinsurance\/startdrive(withperiod3:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/insurancePeriodSame":{"role":"symbol","title":"FairmaticError.insurancePeriodSame","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insurancePeriodSame"}],"abstract":[{"type":"text","text":"Insurance Period hasn’t changed from the previously active period, action ignored."},{"type":"text","text":" "},{"type":"text","text":"This error may be returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod1:)"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod2:completionHandler:)"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticInsurance\/startDrive(withPeriod3:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/insurancePeriodSame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorInsurancePeriodSame"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/insuranceperiodsame"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/deviceUnsupported":{"role":"symbol","title":"FairmaticError.deviceUnsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceUnsupported"}],"abstract":[{"type":"text","text":"Fairmatic SDK does not support the device type."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/deviceUnsupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorDeviceUnsupported"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/deviceunsupported"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/refreshBusinessHoursFeatureNotEnabled":{"role":"symbol","title":"FairmaticError.refreshBusinessHoursFeatureNotEnabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshBusinessHoursFeatureNotEnabled"}],"abstract":[{"type":"text","text":"this error is thrown when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/refreshBusinessHours(completionHandler:)"},{"type":"text","text":" is called but business hours feature is not enabled."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursFeatureNotEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorRefreshBusinessHoursFeatureNotEnabled"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/refreshbusinesshoursfeaturenotenabled"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/userDeprovisioned":{"role":"symbol","title":"FairmaticError.userDeprovisioned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDeprovisioned"}],"abstract":[{"type":"text","text":"User is not authorized to use this application."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/userDeprovisioned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorUserDeprovisioned"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/userdeprovisioned"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/setup(with:delegate:completionHandler:)":{"role":"symbol","title":"setup(with:delegate:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDelegate","preciseIdentifier":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Initializes the Fairmatic SDK to automatically detect driving and collect"},{"type":"text","text":" "},{"type":"text","text":"data. Client code should call this method before anything else in the Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setup(with:delegate:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/wipeOut(completion:)":{"role":"symbol","title":"wipeOut(completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wipeOut"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Wipe out all the data that Fairmatic keeps locally on the device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wipeOutWithCompletion:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/wipeout(completion:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/unsupportedOSVersion":{"role":"symbol","title":"FairmaticError.unsupportedOSVersion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedOSVersion"}],"abstract":[{"type":"text","text":"Fairmatic SDK does not support the OS version of the device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unsupportedOSVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticErrorUnsupportedOSVersion"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror\/unsupportedosversion"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/refreshBusinessHours(completionHandler:)":{"role":"symbol","title":"refreshBusinessHours(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshBusinessHours"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"businessHours"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftDetail","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantly Refreshes the business hours, the SDK makes an API call to the backend to fetch the latest business hours."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/refreshBusinessHours(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshBusinessHoursWithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/refreshbusinesshours(completionhandler:)"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticerror\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Region":{"role":"symbol","title":"Region","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Region"}],"abstract":[{"type":"text","text":"Dictates the region where user’s data will reside."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Region"}],"url":"\/documentation\/fairmaticsdk\/region"},"doc://com.fairmatic.Fairmatic/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.fairmatic.Fairmatic\/10Foundation14LocalizedErrorP"},"doc://com.fairmatic.Fairmatic/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/beaconNotFound","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/deviceUnsupported","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/expiredPausedTillTimestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/insurancePeriodSame","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/internalFailure","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidBeaconUUID","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidParams","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidRegion","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidSDKKeyString","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/invalidTrackingId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/ioError","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/maxBeaconLimitReached","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/networkUnreachable","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notSetup","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/notTornDown","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursFeatureNotEnabled","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursNetworkNotAvailable","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/refreshBusinessHoursTimeout","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/regionUnsupported","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/sdkNotEnabled","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unauthorizedRegionSwitch","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unsupportedOSVersion","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/unsupportedVehicleType","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/userDeprovisioned"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1refreshBusinessHoursTimeout\/title","value":"FairmaticErrorRefreshBusinessHoursTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1refreshBusinessHoursTimeout\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorRefreshBusinessHoursTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1expiredPausedTillTimestamp\/title","value":"FairmaticErrorExpiredPausedTillTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1expiredPausedTillTimestamp\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorExpiredPausedTillTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod2:completionHandler:)\/title","value":"startDriveWithPeriod2:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod2:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError\/title","value":"FairmaticError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError\/fragments","value":[{"kind":"identifier","text":"FairmaticError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1beaconNotFound\/title","value":"FairmaticErrorBeaconNotFound"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1beaconNotFound\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorBeaconNotFound"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidTrackingId\/title","value":"FairmaticErrorInvalidTrackingId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidTrackingId\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInvalidTrackingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidSDKKeyString\/title","value":"FairmaticErrorInvalidSDKKeyString"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidSDKKeyString\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInvalidSDKKeyString"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidBeaconUUID\/title","value":"FairmaticErrorInvalidBeaconUUID"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidBeaconUUID\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInvalidBeaconUUID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1notSetup\/title","value":"FairmaticErrorNotSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1notSetup\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorNotSetup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1maxBeaconLimitReached\/title","value":"FairmaticErrorMaxBeaconLimitReached"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1maxBeaconLimitReached\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorMaxBeaconLimitReached"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod1:)\/title","value":"startDriveWithPeriod1:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod1:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod1:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidParams\/title","value":"FairmaticErrorInvalidParams"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidParams\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInvalidParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1sdkNotEnabled\/title","value":"FairmaticErrorSdkNotEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1sdkNotEnabled\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorSdkNotEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1regionUnsupported\/title","value":"FairmaticErrorRegionUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1regionUnsupported\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorRegionUnsupported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1unsupportedVehicleType\/title","value":"FairmaticErrorUnsupportedVehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1unsupportedVehicleType\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorUnsupportedVehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidRegion\/title","value":"FairmaticErrorInvalidRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1invalidRegion\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInvalidRegion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1refreshBusinessHoursNetworkNotAvailable\/title","value":"FairmaticErrorRefreshBusinessHoursNetworkNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1refreshBusinessHoursNetworkNotAvailable\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorRefreshBusinessHoursNetworkNotAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1pauseAutoTracking(_:completion:)\/title","value":"pauseAutoTracking:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1pauseAutoTracking(_:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pauseAutoTracking:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1notTornDown\/title","value":"FairmaticErrorNotTornDown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1notTornDown\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorNotTornDown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1internalFailure\/title","value":"FairmaticErrorInternalFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1internalFailure\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInternalFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1networkUnreachable\/title","value":"FairmaticErrorNetworkUnreachable"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1networkUnreachable\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorNetworkUnreachable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1unauthorizedRegionSwitch\/title","value":"FairmaticErrorUnauthorizedRegionSwitch"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1unauthorizedRegionSwitch\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorUnauthorizedRegionSwitch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1ioError\/title","value":"FairmaticErrorIoError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1ioError\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorIoError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod3:completionHandler:)\/title","value":"startDriveWithPeriod3:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticInsurance~1startDrive(withPeriod3:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1insurancePeriodSame\/title","value":"FairmaticErrorInsurancePeriodSame"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1insurancePeriodSame\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorInsurancePeriodSame"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1deviceUnsupported\/title","value":"FairmaticErrorDeviceUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1deviceUnsupported\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorDeviceUnsupported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1refreshBusinessHoursFeatureNotEnabled\/title","value":"FairmaticErrorRefreshBusinessHoursFeatureNotEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1refreshBusinessHoursFeatureNotEnabled\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorRefreshBusinessHoursFeatureNotEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1userDeprovisioned\/title","value":"FairmaticErrorUserDeprovisioned"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1userDeprovisioned\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorUserDeprovisioned"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/title","value":"setupWith:delegate:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1wipeOut(completion:)\/title","value":"wipeOutWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1wipeOut(completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"wipeOutWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1unsupportedOSVersion\/title","value":"FairmaticErrorUnsupportedOSVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError~1unsupportedOSVersion\/fragments","value":[{"kind":"identifier","text":"FairmaticErrorUnsupportedOSVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1refreshBusinessHours(completionHandler:)\/title","value":"refreshBusinessHoursWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1refreshBusinessHours(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"refreshBusinessHoursWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Region\/title","value":"FairmaticRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Region\/fragments","value":[{"kind":"identifier","text":"FairmaticRegion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}