{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticMockAccidentConfig) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSCopying","doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"title":"MockAccidentConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/collisionSeverity","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/delayBetweenCallbacks","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/directionOfImpact","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidence","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidenceNumber","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/potentialAccidentConfidence","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/potentialAccidentConfidenceNumber","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/vehicleType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/copy(with:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()"]}],"references":{"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/potentialAccidentConfidence":{"role":"symbol","title":"potentialAccidentConfidence","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"potentialAccidentConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"}],"abstract":[{"type":"text","text":"This field specifies the confidence for the potential accident callback -  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processPotentialAccidentDetected(_:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/potentialAccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"potentialAccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/potentialaccidentconfidence"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processAccidentDetected(_:)":{"role":"symbol","title":"processAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is fired on the main thread when an accident is detected by"},{"type":"text","text":" "},{"type":"text","text":"the SDK during a drive. Any ongoing auto-detected\/manual drives will be stopped"},{"type":"text","text":" "},{"type":"text","text":"after this point."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAccidentDetected:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Creates a Fairmatic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/init()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(using:)":{"role":"symbol","title":"raiseMockAccident(using:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockAccidentConfig","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in DEBUG mode,"},{"type":"text","text":" "},{"type":"text","text":"disabled in RELEASE mode."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccidentUsing:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(using:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/finalAccidentConfidenceNumber":{"role":"symbol","title":"finalAccidentConfidenceNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalAccidentConfidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This field specifies the confidence number for the final accident callback - - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidenceNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalAccidentConfidenceNumber"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/finalaccidentconfidencenumber"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/finalAccidentConfidence":{"role":"symbol","title":"finalAccidentConfidence","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalAccidentConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"}],"abstract":[{"type":"text","text":"This field specifies the confidence for the final accident callback - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalAccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/finalaccidentconfidence"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/vehicleType":{"role":"symbol","title":"vehicleType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"}],"abstract":[{"type":"text","text":"This field specifies the vehicle type at the time of potential accident callback and final accident callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/vehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicleType"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/vehicletype"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Creates a copy of Fairmatic "},{"type":"codeVoice","code":"MockAccidentConfig"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/copy(with:)"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/invalidateFinalCallback()":{"role":"symbol","title":"invalidateFinalCallback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateFinalCallback"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method causes the final callback to invalidate the potential callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateFinalCallback"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/invalidatefinalcallback()"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processPotentialAccidentDetected(_:)":{"role":"symbol","title":"processPotentialAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processPotentialAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"[Disabled by default]"},{"type":"text","text":" "},{"type":"text","text":"This callback is fired on the main thread when a potential accident is detected by the SDK during a drive."},{"type":"text","text":" "},{"type":"text","text":"This is a preliminary callback of a potential collision. This collision is confirmed or invalidated by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processPotentialAccidentDetected(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processPotentialAccidentDetected:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processpotentialaccidentdetected(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/directionOfImpact":{"role":"symbol","title":"directionOfImpact","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact"}],"abstract":[{"type":"text","text":"This field specifies the direction of impact at the time of potential accident callback and final accident callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/directionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"directionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/directionofimpact"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/delayBetweenCallbacks":{"role":"symbol","title":"delayBetweenCallbacks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delayBetweenCallbacks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This field specifies the callback delay (in seconds) between the potential and final accident callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/delayBetweenCallbacks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delayBetweenCallbacks"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/delaybetweencallbacks"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig":{"role":"symbol","title":"MockAccidentConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/collisionSeverity":{"role":"symbol","title":"collisionSeverity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collisionSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollisionSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity"}],"abstract":[{"type":"text","text":"This field specifies the collision severity at the time of potential accident callback and final accident callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/collisionSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collisionSeverity"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/collisionseverity"},"doc://com.fairmatic.Fairmatic/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSCopying"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/potentialAccidentConfidenceNumber":{"role":"symbol","title":"potentialAccidentConfidenceNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"potentialAccidentConfidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This field specifies the confidence for the potential accident callback - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processPotentialAccidentDetected(_:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/potentialAccidentConfidenceNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"potentialAccidentConfidenceNumber"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/potentialaccidentconfidencenumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/collisionSeverity","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/delayBetweenCallbacks","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/directionOfImpact","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidence","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/finalAccidentConfidenceNumber","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/potentialAccidentConfidence","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/potentialAccidentConfidenceNumber","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/vehicleType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/copy(with:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/init()","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticMockAccidentConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1potentialAccidentConfidence\/title","value":"potentialAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1potentialAccidentConfidence\/fragments","value":[{"kind":"identifier","text":"potentialAccidentConfidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/title","value":"processAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/title","value":"raiseMockAccidentUsing:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccidentUsing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1finalAccidentConfidenceNumber\/title","value":"finalAccidentConfidenceNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1finalAccidentConfidenceNumber\/fragments","value":[{"kind":"identifier","text":"finalAccidentConfidenceNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1finalAccidentConfidence\/title","value":"finalAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1finalAccidentConfidence\/fragments","value":[{"kind":"identifier","text":"finalAccidentConfidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1vehicleType\/title","value":"vehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1vehicleType\/fragments","value":[{"kind":"identifier","text":"vehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1invalidateFinalCallback()\/title","value":"invalidateFinalCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1invalidateFinalCallback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateFinalCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processPotentialAccidentDetected(_:)\/title","value":"processPotentialAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processPotentialAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processPotentialAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1directionOfImpact\/title","value":"directionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1directionOfImpact\/fragments","value":[{"kind":"identifier","text":"directionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1delayBetweenCallbacks\/title","value":"delayBetweenCallbacks"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1delayBetweenCallbacks\/fragments","value":[{"kind":"identifier","text":"delayBetweenCallbacks"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1collisionSeverity\/title","value":"collisionSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1collisionSeverity\/fragments","value":[{"kind":"identifier","text":"collisionSeverity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1potentialAccidentConfidenceNumber\/title","value":"potentialAccidentConfidenceNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1potentialAccidentConfidenceNumber\/fragments","value":[{"kind":"identifier","text":"potentialAccidentConfidenceNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}