{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticScannedBeaconInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScannedBeaconInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/scannedbeaconinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/scannedbeaconinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrapper for beacons scanned using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScannedBeaconInfo"}],"title":"ScannedBeaconInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ScannedBeaconInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(clBeacon:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/accuracy","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/major","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/minor","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/proximity","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/rssi","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/timestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/uuid"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/timestamp":{"role":"symbol","title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The timestamp representing when the beacon was observed."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/timestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/timestamp"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/minor":{"role":"symbol","title":"minor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The minor of the scanned beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/minor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minor"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/minor"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getNearbyBeacons(uuid:major:minor:completionHandler:)":{"role":"symbol","title":"getNearbyBeacons(uuid:major:minor:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNearbyBeacons"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scannedBeacons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScannedBeaconInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get all the beacons which are in the device’s range."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getnearbybeacons(uuid:major:minor:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/major":{"role":"symbol","title":"major","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The major of the scanned beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/major","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"major"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/major"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/uuid":{"role":"symbol","title":"uuid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The UUID of the scanned beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/uuid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uuid"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/uuid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/init(clBeacon:)":{"role":"symbol","title":"init(clBeacon:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clBeacon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLBeacon","preciseIdentifier":"c:objc(cs)CLBeacon"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize the beacon with a "},{"type":"codeVoice","code":"CLBeacon"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(clBeacon:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithClBeacon:"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/init(clbeacon:)"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/proximity":{"role":"symbol","title":"proximity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"proximity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLProximity","preciseIdentifier":"c:@E@CLProximity"}],"abstract":[{"type":"text","text":"Constants that reflect the relative distance to a beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/proximity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"proximity"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/proximity"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/accuracy":{"role":"symbol","title":"accuracy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"}],"abstract":[{"type":"text","text":"The accuracy of the proximity value, measured in meters from the beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/accuracy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accuracy"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/accuracy"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/init(uuid:major:minor:)":{"role":"symbol","title":"init(uuid:major:minor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize the beacon with UUID, major, minor."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUuid:major:minor:"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/init(uuid:major:minor:)"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo":{"role":"symbol","title":"ScannedBeaconInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScannedBeaconInfo"}],"abstract":[{"type":"text","text":"Wrapper for beacons scanned using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScannedBeaconInfo"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)":{"role":"symbol","title":"init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rssi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proximity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLProximity","preciseIdentifier":"c:@E@CLProximity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationAccuracy","preciseIdentifier":"c:@T@CLLocationAccuracy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with UUID, major, minor, RSSI, proximity, accuracy."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUuid:major:minor:rssi:proximity:accuracy:timestamp:"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/rssi":{"role":"symbol","title":"rssi","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rssi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The RSSI of the scanned beacon."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/rssi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rssi"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/rssi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticScannedBeaconInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticScannedBeaconInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticScannedBeaconInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/accuracy","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/major","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/minor","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/proximity","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/rssi","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/timestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/uuid"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(clBeacon:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticScannedBeaconInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1minor\/title","value":"minor"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1minor\/fragments","value":[{"kind":"identifier","text":"minor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/title","value":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1major\/title","value":"major"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1major\/fragments","value":[{"kind":"identifier","text":"major"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1uuid\/title","value":"uuid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1uuid\/fragments","value":[{"kind":"identifier","text":"uuid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(clBeacon:)\/title","value":"initWithClBeacon:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(clBeacon:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithClBeacon:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1proximity\/title","value":"proximity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1proximity\/fragments","value":[{"kind":"identifier","text":"proximity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1accuracy\/title","value":"accuracy"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1accuracy\/fragments","value":[{"kind":"identifier","text":"accuracy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(uuid:major:minor:)\/title","value":"initWithUuid:major:minor:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(uuid:major:minor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUuid:major:minor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo\/title","value":"FairmaticScannedBeaconInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticScannedBeaconInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)\/title","value":"initWithUuid:major:minor:rssi:proximity:accuracy:timestamp:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(uuid:major:minor:rssi:proximity:accuracy:timestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUuid:major:minor:rssi:proximity:accuracy:timestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1rssi\/title","value":"rssi"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1rssi\/fragments","value":[{"kind":"identifier","text":"rssi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}