{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticSDKHealthReason) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKHealthReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/sdkhealthreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/sdkhealthreason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Dictates the reason for is logging SDK Health"},{"type":"text","text":" "},{"type":"text","text":"The SDK health will be recorded when there is any update in permission from last recorded SDK health."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKHealthReason"}],"title":"SDKHealthReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticSDKHealthReason","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SDKHealthReason"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/backgroundProcessing","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/silentPushNotification","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason/backgroundProcessing":{"role":"symbol","title":"SDKHealthReason.backgroundProcessing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundProcessing"}],"abstract":[{"type":"text","text":"Indicates the SDK health will recorded due to background processing"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/backgroundProcessing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/backgroundprocessing"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason/silentPushNotification":{"role":"symbol","title":"SDKHealthReason.silentPushNotification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentPushNotification"}],"abstract":[{"type":"text","text":"Indicates the SDK health will recorded due to silent push notification"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/silentPushNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/silentpushnotification"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason":{"role":"symbol","title":"SDKHealthReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKHealthReason"}],"abstract":[{"type":"text","text":"Dictates the reason for is logging SDK Health"},{"type":"text","text":" "},{"type":"text","text":"The SDK health will be recorded when there is any update in permission from last recorded SDK health."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKHealthReason"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason/unknown":{"role":"symbol","title":"SDKHealthReason.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Indicates the reason  is unknown."},{"type":"text","text":" "},{"type":"text","text":"This is the default value."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonUnknown"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/unknown"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SDKHealthReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSDKHealthReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticSDKHealthReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/backgroundProcessing","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/silentPushNotification","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SDKHealthReason\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticSDKHealthReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason~1backgroundProcessing\/title","value":"FairmaticSDKHealthReasonBackgroundProcessing"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason~1backgroundProcessing\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason~1silentPushNotification\/title","value":"FairmaticSDKHealthReasonSilentPushNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason~1silentPushNotification\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason\/title","value":"FairmaticSDKHealthReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason~1unknown\/title","value":"FairmaticSDKHealthReasonUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SDKHealthReason~1unknown\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonUnknown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}