{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticServiceLevel) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceLevel"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is useful for applications which need special modes in the Fairmatic SDK for different"},{"type":"text","text":" "},{"type":"text","text":"drivers - e.g default mode for free users and a advanced mode for paid users."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default, multiple service levels are not enabled for an application."},{"type":"text","text":" "},{"type":"text","text":"To be able to use different modes for your application, you should reach out to your Fairmatic contact"},{"type":"text","text":" "},{"type":"text","text":"with your requirements and get that enabled for your application."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, if this is not enabled for your application, all drivers get mapped to"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"},{"type":"text","text":" irrespective of the service level specified."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/servicelevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/servicelevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enumeration for different service levels supported by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" for a driver."},{"type":"text","text":" "},{"type":"text","text":"By default, drivers will be assigned to the default service level - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceLevel"}],"title":"ServiceLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticServiceLevel","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ServiceLevel"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/level1","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/servicelevel\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel":{"role":"symbol","title":"ServiceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceLevel"}],"abstract":[{"type":"text","text":"Enumeration for different service levels supported by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" for a driver."},{"type":"text","text":" "},{"type":"text","text":"By default, drivers will be assigned to the default service level - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceLevel"}],"url":"\/documentation\/fairmaticsdk\/servicelevel"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/servicelevel\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/level1":{"role":"symbol","title":"ServiceLevel.level1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"level1"}],"abstract":[{"type":"text","text":"Special service level 1 that is enabled for a particular application."},{"type":"text","text":" "},{"type":"text","text":"Reach out to your Fairmatic contact with your requirements to get this enabled for your application."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/level1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}],"url":"\/documentation\/fairmaticsdk\/servicelevel\/level1"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/servicelevel\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/levelDefault":{"role":"symbol","title":"ServiceLevel.levelDefault","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"levelDefault"}],"abstract":[{"type":"text","text":"Default service level. This is most common level required by most of the applications"},{"type":"text","text":" "},{"type":"text","text":"that use "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticServiceLevelLevelDefault"}],"url":"\/documentation\/fairmaticsdk\/servicelevel\/leveldefault"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticServiceLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticServiceLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/level1","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticServiceLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/title","value":"FairmaticServiceLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1level1\/title","value":"FairmaticServiceLevelLevel1"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1level1\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1levelDefault\/title","value":"FairmaticServiceLevelLevelDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1levelDefault\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevelLevelDefault"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}