{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticSettingsErrorType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsErrorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/settingserrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/settingserrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error type for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsError"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsErrorType"}],"title":"SettingsErrorType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticSettingsErrorType","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsErrorType"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/activityPermissionNotAuthorized","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationAccuracyAuthorizationReduced","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationPermissionNotAuthorized","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationServiceOff"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/locationPermissionNotAuthorized":{"role":"symbol","title":"SettingsErrorType.locationPermissionNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationPermissionNotAuthorized"}],"abstract":[{"type":"text","text":"The location authorization status is determined but the user hasn’t granted"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"strong","inlineContent":[{"type":"text","text":"Always"}]},{"type":"text","text":" location authorization to the application."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationPermissionNotAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationPermissionNotAuthorized"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype\/locationpermissionnotauthorized"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/locationAccuracyAuthorizationReduced":{"role":"symbol","title":"SettingsErrorType.locationAccuracyAuthorizationReduced","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationAccuracyAuthorizationReduced"}],"abstract":[{"type":"text","text":"The location authorization is "},{"type":"strong","inlineContent":[{"type":"text","text":"Always"}]},{"type":"text","text":" but location accuracy authorization"},{"type":"text","text":" "},{"type":"text","text":"is "},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" "},{"type":"codeVoice","code":"CLAccuracyAuthorizationFullAccuracy"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationAccuracyAuthorizationReduced","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationAccuracyAuthorizationReduced"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype\/locationaccuracyauthorizationreduced"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsError":{"role":"symbol","title":"SettingsError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsError"}],"abstract":[{"type":"text","text":"This class represent an error in device or application settings that is affecting"},{"type":"text","text":" "},{"type":"text","text":"the ability of the SDK to detect trips."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsError"}],"url":"\/documentation\/fairmaticsdk\/settingserror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/locationServiceOff":{"role":"symbol","title":"SettingsErrorType.locationServiceOff","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationServiceOff"}],"abstract":[{"type":"text","text":"The location service is turned off."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationServiceOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype\/locationserviceoff"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/settingserrortype\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/settingserrortype\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType":{"role":"symbol","title":"SettingsErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsErrorType"}],"abstract":[{"type":"text","text":"Error type for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsError"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsErrorType"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/activityPermissionNotAuthorized":{"role":"symbol","title":"SettingsErrorType.activityPermissionNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityPermissionNotAuthorized"}],"abstract":[{"type":"text","text":"The activity authorization status is determined but the user has "},{"type":"strong","inlineContent":[{"type":"text","text":"not authorized"}]},{"type":"text","text":" application to"},{"type":"text","text":" "},{"type":"text","text":"access the motion and fitness data. This error will only be thrown if activity based trip detection"},{"type":"text","text":" "},{"type":"text","text":"is enabled for the application."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/activityPermissionNotAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype\/activitypermissionnotauthorized"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/settingserrortype\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSettingsErrorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticSettingsErrorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/activityPermissionNotAuthorized","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationAccuracyAuthorizationReduced","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationPermissionNotAuthorized","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationServiceOff"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticSettingsErrorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationPermissionNotAuthorized\/title","value":"FairmaticSettingsErrorTypeLocationPermissionNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationPermissionNotAuthorized\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationPermissionNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationAccuracyAuthorizationReduced\/title","value":"FairmaticSettingsErrorTypeLocationAccuracyAuthorizationReduced"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationAccuracyAuthorizationReduced\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationAccuracyAuthorizationReduced"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsError\/title","value":"FairmaticSettingsError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsError\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationServiceOff\/title","value":"FairmaticSettingsErrorTypeLocationServiceOff"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationServiceOff\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType\/title","value":"FairmaticSettingsErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1activityPermissionNotAuthorized\/title","value":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1activityPermissionNotAuthorized\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeActivityPermissionNotAuthorized"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}