{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticShiftInterval) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftInterval"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shiftinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shiftinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrapper for a single business hour interval."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftInterval"}],"title":"ShiftInterval","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ShiftInterval"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/init(startTime:endTime:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/endTime","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/startTime"]}],"references":{"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval/init(startTime:endTime:)":{"role":"symbol","title":"init(startTime:endTime:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize the shift interval object with start time and end time."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/init(startTime:endTime:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStartTime:endTime:"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval\/init(starttime:endtime:)"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval/startTime":{"role":"symbol","title":"startTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime"}],"abstract":[{"type":"text","text":"Start time of the shift interval, indicates when the shift interval starts."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/startTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval\/starttime"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval":{"role":"symbol","title":"ShiftInterval","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftInterval"}],"abstract":[{"type":"text","text":"Wrapper for a single business hour interval."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftInterval"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval/endTime":{"role":"symbol","title":"endTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShiftTime","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime"}],"abstract":[{"type":"text","text":"End time of the shift interval, indicates when the shift interval ends."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/endTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endTime"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval\/endtime"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticShiftInterval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftInterval"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticShiftInterval"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/endTime","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/startTime"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval\/init(startTime:endTime:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticShiftInterval"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1init(startTime:endTime:)\/title","value":"initWithStartTime:endTime:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1init(startTime:endTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStartTime:endTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1startTime\/title","value":"startTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1startTime\/fragments","value":[{"kind":"identifier","text":"startTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/title","value":"FairmaticShiftInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1endTime\/title","value":"endTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval~1endTime\/fragments","value":[{"kind":"identifier","text":"endTime"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}