{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticShiftTime) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftTime"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shifttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shifttime"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a particular day and time in a weekly schedule, The shift time is represented in 24 hour time format."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftTime"}],"title":"ShiftTime","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftTime","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ShiftTime"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/init(dayOfWeek:hour:minute:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/dayOfWeek","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/hour","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/minute"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime/init(dayOfWeek:hour:minute:)":{"role":"symbol","title":"init(dayOfWeek:hour:minute:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"initializes the "},{"type":"codeVoice","code":"ShiftTime"},{"type":"text","text":" object."},{"type":"text","text":" "},{"type":"text","text":"Example"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/init(dayOfWeek:hour:minute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDayOfWeek:hour:minute:"}],"url":"\/documentation\/fairmaticsdk\/shifttime\/init(dayofweek:hour:minute:)"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime":{"role":"symbol","title":"ShiftTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftTime"}],"abstract":[{"type":"text","text":"Represents a particular day and time in a weekly schedule, The shift time is represented in 24 hour time format."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftTime"}],"url":"\/documentation\/fairmaticsdk\/shifttime"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime/dayOfWeek":{"role":"symbol","title":"dayOfWeek","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayOfWeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDayOfWeek","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek"}],"abstract":[{"type":"text","text":"Represents the day of the week, range: [1-7]"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/dayOfWeek","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dayOfWeek"}],"url":"\/documentation\/fairmaticsdk\/shifttime\/dayofweek"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime/minute":{"role":"symbol","title":"minute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Represents the minute of the hour. range: [0-59]."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/minute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minute"}],"url":"\/documentation\/fairmaticsdk\/shifttime\/minute"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftTime/hour":{"role":"symbol","title":"hour","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hour"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Represents the hour of the day. range: [0-23]."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/hour","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hour"}],"url":"\/documentation\/fairmaticsdk\/shifttime\/hour"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticShiftTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftTime"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticShiftTime"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/dayOfWeek","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/hour","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/minute"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftTime\/init(dayOfWeek:hour:minute:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticShiftTime"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1init(dayOfWeek:hour:minute:)\/title","value":"initWithDayOfWeek:hour:minute:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1init(dayOfWeek:hour:minute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDayOfWeek:hour:minute:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/title","value":"FairmaticShiftTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1dayOfWeek\/title","value":"dayOfWeek"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1dayOfWeek\/fragments","value":[{"kind":"identifier","text":"dayOfWeek"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1minute\/title","value":"minute"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1minute\/fragments","value":[{"kind":"identifier","text":"minute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1hour\/title","value":"hour"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftTime~1hour\/fragments","value":[{"kind":"identifier","text":"hour"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}