{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticVehicleTaggingDetails) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleTaggingDetails"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/vehicletaggingdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/vehicletaggingdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrapper for vehicle tagging details for a drive."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleTaggingDetails"}],"title":"VehicleTaggingDetails","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleTaggingDetails","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"VehicleTaggingDetails"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBeacon","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBluetoothStereo","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/vehicleId"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initializer for "},{"type":"codeVoice","code":"VehicleTaggingDetails"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails\/init()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails/vehicleId":{"role":"symbol","title":"vehicleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The vehicleId of the tagged vehicle"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/vehicleId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicleId"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails\/vehicleid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails/isTaggedByBluetoothStereo":{"role":"symbol","title":"isTaggedByBluetoothStereo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTaggedByBluetoothStereo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This flag determines if vehicle is tagged using bluetooth stereo"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBluetoothStereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isTaggedByBluetoothStereo"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails\/istaggedbybluetoothstereo"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails":{"role":"symbol","title":"VehicleTaggingDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleTaggingDetails"}],"abstract":[{"type":"text","text":"Wrapper for vehicle tagging details for a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleTaggingDetails"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails/isTaggedByBeacon":{"role":"symbol","title":"isTaggedByBeacon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTaggedByBeacon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This flag determines if vehicle is tagged using beacon"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBeacon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isTaggedByBeacon"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails\/istaggedbybeacon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticVehicleTaggingDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingDetails"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingDetails"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBeacon","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBluetoothStereo","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/vehicleId"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1vehicleId\/title","value":"vehicleId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1vehicleId\/fragments","value":[{"kind":"identifier","text":"vehicleId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1isTaggedByBluetoothStereo\/title","value":"isTaggedByBluetoothStereo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1isTaggedByBluetoothStereo\/fragments","value":[{"kind":"identifier","text":"isTaggedByBluetoothStereo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails\/title","value":"FairmaticVehicleTaggingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1isTaggedByBeacon\/title","value":"isTaggedByBeacon"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1isTaggedByBeacon\/fragments","value":[{"kind":"identifier","text":"isTaggedByBeacon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}