{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/phoneposition\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/phoneposition\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition\/unknown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The case when "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was unable to determine the position of the phone during a trip."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"PhonePosition.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticPhonePosition@FairmaticPhonePositionUnknown","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticPhonePositionUnknown"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/PhonePosition/unknown":{"role":"symbol","title":"PhonePosition.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"The case when "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was unable to determine the position of the phone during a trip."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPhonePositionUnknown"}],"url":"\/documentation\/fairmaticsdk\/phoneposition\/unknown"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/PhonePosition":{"role":"symbol","title":"PhonePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhonePosition"}],"abstract":[{"type":"text","text":"The types of phone positions during a trip."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/PhonePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhonePosition"}],"url":"\/documentation\/fairmaticsdk\/phoneposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticPhonePositionUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticPhonePositionUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticPhonePositionUnknown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition~1unknown\/title","value":"FairmaticPhonePositionUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition~1unknown\/fragments","value":[{"kind":"identifier","text":"FairmaticPhonePositionUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition\/title","value":"FairmaticPhonePosition"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1PhonePosition\/fragments","value":[{"kind":"identifier","text":"FairmaticPhonePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}