{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVehicleInfo"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"It is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/vehicleId"},{"type":"text","text":" is nil or has more than 64 characters."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/vehicleId"},{"type":"text","text":" doesn’t satisfy "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/bluetoothId"},{"type":"text","text":" is not a valid mac address."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/invalidvehicleinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/invalidvehicleinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleInfo","interfaceLanguage":"swift"},"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo"},{"type":"text","text":" object passed to ``FairmaticVehicleTagging\/associateVehicle(_:)`"},{"type":"text","text":" "},{"type":"text","text":"is invalid because of one of the following reasons:-"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVehicleInfo"}],"title":"FairmaticVehicleTaggingError.invalidVehicleInfo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticVehicleTaggingError@FairmaticVehicleTaggingErrorInvalidVehicleInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo/vehicleId":{"role":"symbol","title":"vehicleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The unique identifier for the vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/vehicleId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicleId"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo\/vehicleid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError":{"role":"symbol","title":"FairmaticVehicleTaggingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"abstract":[{"type":"text","text":"Error returned as code to NSError from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"},{"type":"text","text":" public APIs"},{"type":"text","text":" "},{"type":"text","text":"in case of failures."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo":{"role":"symbol","title":"VehicleInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/invalidVehicleInfo":{"role":"symbol","title":"FairmaticVehicleTaggingError.invalidVehicleInfo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVehicleInfo"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo"},{"type":"text","text":" object passed to ``FairmaticVehicleTagging\/associateVehicle(_:)`"},{"type":"text","text":" "},{"type":"text","text":"is invalid because of one of the following reasons:-"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/invalidvehicleinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/isValidInputParameter(_:)":{"role":"symbol","title":"isValidInputParameter(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidInputParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this method to check whether the parameter string passed"},{"type":"text","text":" "},{"type":"text","text":"to the SDK is valid."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isValidInputParameter:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/isvalidinputparameter(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo/bluetoothId":{"role":"symbol","title":"bluetoothId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetoothId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The mac address of vehicles’s bluetooth device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/bluetoothId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bluetoothId"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo\/bluetoothid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo~1vehicleId\/title","value":"vehicleId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo~1vehicleId\/fragments","value":[{"kind":"identifier","text":"vehicleId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/title","value":"FairmaticVehicleTaggingError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/title","value":"FairmaticVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1invalidVehicleInfo\/title","value":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1invalidVehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/title","value":"isValidInputParameter:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isValidInputParameter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo~1bluetoothId\/title","value":"bluetoothId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo~1bluetoothId\/fragments","value":[{"kind":"identifier","text":"bluetoothId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}