{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bluetoothId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"vehicleId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier for the vehicle."}]}]},{"name":"bluetoothId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mac address of vehicle’s bluetooth device."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/vehicleinfo\/init(vehicleid:bluetoothid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/vehicleinfo\/init(vehicleid:bluetoothid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/init(vehicleId:bluetoothId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializer for "},{"type":"codeVoice","code":"VehicleInfo"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bluetoothId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(vehicleId:bluetoothId:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo(im)initWithVehicleId:bluetoothId:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVehicleId:bluetoothId:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo/init(vehicleId:bluetoothId:)":{"role":"symbol","title":"init(vehicleId:bluetoothId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bluetoothId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializer for "},{"type":"codeVoice","code":"VehicleInfo"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo\/init(vehicleId:bluetoothId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVehicleId:bluetoothId:"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo\/init(vehicleid:bluetoothid:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo":{"role":"symbol","title":"VehicleInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVehicleId:bluetoothId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVehicleId:bluetoothId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVehicleId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"vehicleId"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetoothId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bluetoothId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo~1init(vehicleId:bluetoothId:)\/title","value":"initWithVehicleId:bluetoothId:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo~1init(vehicleId:bluetoothId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVehicleId:bluetoothId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/title","value":"FairmaticVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}