{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivecategory\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/drivecategory\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/invalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates that there wasn’t enough movement and this shouldn’t have been"},{"type":"text","text":" "},{"type":"text","text":"detected as a trip"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"title":"DriveCategory.invalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticDriveCategory@FairmaticDriveCategoryInvalid","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/invalid":{"role":"symbol","title":"DriveCategory.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Indicates that there wasn’t enough movement and this shouldn’t have been"},{"type":"text","text":" "},{"type":"text","text":"detected as a trip"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/invalid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory":{"role":"symbol","title":"DriveCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveCategory"}],"abstract":[{"type":"text","text":"The category that best indicates the type of trip"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveCategory"}],"url":"\/documentation\/fairmaticsdk\/drivecategory"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveCategoryInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1invalid\/title","value":"FairmaticDriveCategoryInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory\/title","value":"FairmaticDriveCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}