{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/servicelevel\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:12FairmaticSDK12ServiceLevelO8rawValueACSgSi_tcfc","modules":[{"name":"FairmaticSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/servicelevel\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel":{"role":"symbol","title":"ServiceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceLevel"}],"abstract":[{"type":"text","text":"Enumeration for different service levels supported by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" for a driver."},{"type":"text","text":" "},{"type":"text","text":"By default, drivers will be assigned to the default service level - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceLevel"}],"url":"\/documentation\/fairmaticsdk\/servicelevel"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/levelDefault":{"role":"symbol","title":"ServiceLevel.levelDefault","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"levelDefault"}],"abstract":[{"type":"text","text":"Default service level. This is most common level required by most of the applications"},{"type":"text","text":" "},{"type":"text","text":"that use "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticServiceLevelLevelDefault"}],"url":"\/documentation\/fairmaticsdk\/servicelevel\/leveldefault"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/title","value":"FairmaticServiceLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1levelDefault\/title","value":"FairmaticServiceLevelLevelDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1levelDefault\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevelLevelDefault"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}