{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"level1"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/servicelevel\/level1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/servicelevel\/level1"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/level1","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Special service level 1 that is enabled for a particular application."},{"type":"text","text":" "},{"type":"text","text":"Reach out to your Fairmatic contact with your requirements to get this enabled for your application."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"level1"}],"title":"ServiceLevel.level1","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticServiceLevel@FairmaticServiceLevelLevel1","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/level1":{"role":"symbol","title":"ServiceLevel.level1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"level1"}],"abstract":[{"type":"text","text":"Special service level 1 that is enabled for a particular application."},{"type":"text","text":" "},{"type":"text","text":"Reach out to your Fairmatic contact with your requirements to get this enabled for your application."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/level1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}],"url":"\/documentation\/fairmaticsdk\/servicelevel\/level1"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel/levelDefault":{"role":"symbol","title":"ServiceLevel.levelDefault","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"levelDefault"}],"abstract":[{"type":"text","text":"Default service level. This is most common level required by most of the applications"},{"type":"text","text":" "},{"type":"text","text":"that use "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticServiceLevelLevelDefault"}],"url":"\/documentation\/fairmaticsdk\/servicelevel\/leveldefault"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ServiceLevel":{"role":"symbol","title":"ServiceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceLevel"}],"abstract":[{"type":"text","text":"Enumeration for different service levels supported by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" for a driver."},{"type":"text","text":" "},{"type":"text","text":"By default, drivers will be assigned to the default service level - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel\/levelDefault"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ServiceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceLevel"}],"url":"\/documentation\/fairmaticsdk\/servicelevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticServiceLevelLevel1"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1level1\/title","value":"FairmaticServiceLevelLevel1"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1level1\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevelLevel1"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1levelDefault\/title","value":"FairmaticServiceLevelLevelDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel~1levelDefault\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevelLevelDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/title","value":"FairmaticServiceLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ServiceLevel\/fragments","value":[{"kind":"identifier","text":"FairmaticServiceLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}