{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"saturday"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdayofweek\/saturday"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdayofweek\/saturday"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek\/saturday","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"saturday"}],"title":"FairmaticDayOfWeek.saturday","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticDayOfWeek@FairmaticDayOfWeekSaturday","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticDayOfWeekSaturday"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDayOfWeek/saturday":{"role":"symbol","title":"FairmaticDayOfWeek.saturday","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"saturday"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek\/saturday","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDayOfWeekSaturday"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdayofweek\/saturday"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDayOfWeek":{"role":"symbol","title":"FairmaticDayOfWeek","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDayOfWeek"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDayOfWeek","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDayOfWeek"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdayofweek"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDayOfWeekSaturday"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDayOfWeekSaturday"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticDayOfWeekSaturday"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek~1saturday\/title","value":"FairmaticDayOfWeekSaturday"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek~1saturday\/fragments","value":[{"kind":"identifier","text":"FairmaticDayOfWeekSaturday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek\/title","value":"FairmaticDayOfWeek"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDayOfWeek\/fragments","value":[{"kind":"identifier","text":"FairmaticDayOfWeek"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}