{"variants":[{"paths":["\/documentation\/fairmaticsdk\/usermode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"FairmaticSDK"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/userMode":{"role":"symbol","title":"userMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode"}],"abstract":[{"type":"text","text":"Whether the user was a driver or a passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userMode"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/usermode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/UserMode/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/usermode\/!=(_:_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/UserMode":{"role":"symbol","title":"UserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMode"}],"abstract":[{"type":"text","text":"The value return from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode"},{"type":"text","text":". Indicates whether user"},{"type":"text","text":" "},{"type":"text","text":"was a driver or passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMode"}],"url":"\/documentation\/fairmaticsdk\/usermode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/title","value":"userMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/fragments","value":[{"kind":"identifier","text":"userMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode\/title","value":"FairmaticUserMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode\/fragments","value":[{"kind":"identifier","text":"FairmaticUserMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}