{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passenger"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/usermode\/passenger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/usermode\/passenger"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/passenger","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates that the user was in the passenger seat."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passenger"}],"title":"UserMode.passenger","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticUserMode@FairmaticUserModePassenger","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticUserModePassenger"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/userMode":{"role":"symbol","title":"userMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode"}],"abstract":[{"type":"text","text":"Whether the user was a driver or a passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userMode"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/usermode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/UserMode/passenger":{"role":"symbol","title":"UserMode.passenger","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passenger"}],"abstract":[{"type":"text","text":"Indicates that the user was in the passenger seat."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/passenger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticUserModePassenger"}],"url":"\/documentation\/fairmaticsdk\/usermode\/passenger"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/UserMode":{"role":"symbol","title":"UserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMode"}],"abstract":[{"type":"text","text":"The value return from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode"},{"type":"text","text":". Indicates whether user"},{"type":"text","text":" "},{"type":"text","text":"was a driver or passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMode"}],"url":"\/documentation\/fairmaticsdk\/usermode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticUserModePassenger"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticUserModePassenger"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticUserModePassenger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/title","value":"userMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/fragments","value":[{"kind":"identifier","text":"userMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode~1passenger\/title","value":"FairmaticUserModePassenger"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode~1passenger\/fragments","value":[{"kind":"identifier","text":"FairmaticUserModePassenger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode\/title","value":"FairmaticUserMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode\/fragments","value":[{"kind":"identifier","text":"FairmaticUserMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}