{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/usermode\/unavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/usermode\/unavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/unavailable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates that either "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is not"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was not able to determine user mode."},{"type":"text","text":" "},{"type":"text","text":"All values in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" will be set."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"title":"UserMode.unavailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticUserMode@FairmaticUserModeUnavailable","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/VehicleType":{"role":"symbol","title":"VehicleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleType"}],"abstract":[{"type":"text","text":"Type of vehicle used in the drive recorded by the Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"A default vehicle type can be set using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes"},{"type":"text","text":". The detected type is returned to the application in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType"},{"type":"text","text":" "},{"type":"text","text":"field of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleType"}],"url":"\/documentation\/fairmaticsdk\/vehicletype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/userMode":{"role":"symbol","title":"userMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode"}],"abstract":[{"type":"text","text":"Whether the user was a driver or a passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userMode"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/usermode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/UserMode":{"role":"symbol","title":"UserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMode"}],"abstract":[{"type":"text","text":"The value return from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode"},{"type":"text","text":". Indicates whether user"},{"type":"text","text":" "},{"type":"text","text":"was a driver or passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMode"}],"url":"\/documentation\/fairmaticsdk\/usermode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/UserMode/unavailable":{"role":"symbol","title":"UserMode.unavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"abstract":[{"type":"text","text":"Indicates that either "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is not"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was not able to determine user mode."},{"type":"text","text":" "},{"type":"text","text":"All values in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" will be set."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/UserMode\/unavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}],"url":"\/documentation\/fairmaticsdk\/usermode\/unavailable"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType/drive":{"role":"symbol","title":"DriveType.drive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"drive"}],"abstract":[{"type":"text","text":"This trip was taken in a valid "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/drive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/drive"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticUserModeUnavailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1VehicleType\/title","value":"FairmaticVehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1VehicleType\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/title","value":"userMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/fragments","value":[{"kind":"identifier","text":"userMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode\/title","value":"FairmaticUserMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode\/fragments","value":[{"kind":"identifier","text":"FairmaticUserMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode~1unavailable\/title","value":"FairmaticUserModeUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1UserMode~1unavailable\/fragments","value":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1drive\/title","value":"FairmaticDriveTypeDrive"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1drive\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}