{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"analyzedDriveInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo","text":"AnalyzedDriveInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"analyzedDriveInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Analyzed insights of the drive."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will be called for all the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callbacks"},{"type":"text","text":" "},{"type":"text","text":"with the value of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" not set to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/invalid"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This may contain additional or improved data over the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EstimatedDriveInfo"},{"type":"text","text":" "},{"type":"text","text":"returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Typically this callback will be fired within a few seconds after "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback but in some rare cases this delay can be really large depending on phone network conditions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This callback will be fired in trip occurrence sequence, i.e from oldest trip to"},{"type":"text","text":" "},{"type":"text","text":"the latest trip."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called on the delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK finishes"},{"type":"text","text":" "},{"type":"text","text":"full analysis of all valid drives returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo"},{"kind":"text","text":")"}],"title":"processAnalysis(ofDrive:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate(im)processAnalysisOfDrive:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"processAnalysisOfDrive:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/maxSpeed":{"role":"symbol","title":"maxSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The maximum speed of trip in metres\/second"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxSpeed"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/maxspeed"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/AnalyzedDriveInfo":{"role":"symbol","title":"AnalyzedDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyzedDriveInfo"}],"abstract":[{"type":"text","text":"This contains the fully analyzed results for a drive, this is returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback for all the trips with the value of"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" not set to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/invalid"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnalyzedDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/analyzeddriveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EstimatedDriveInfo":{"role":"symbol","title":"EstimatedDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EstimatedDriveInfo"}],"abstract":[{"type":"text","text":"This contains the best estimated results for a drive, this is returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EstimatedDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EstimatedDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/estimateddriveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/averageSpeed":{"role":"symbol","title":"averageSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The average speed of trip in metres\/second"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"averageSpeed"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/averagespeed"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/events":{"role":"symbol","title":"events","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"events"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEvent"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Event"},{"type":"text","text":" objects for this trip in increasing order of timestamp."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/events","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"events"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/events"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processAnalysis(ofDrive:)":{"role":"symbol","title":"processAnalysis(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK finishes"},{"type":"text","text":" "},{"type":"text","text":"full analysis of all valid drives returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAnalysisOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/score":{"role":"symbol","title":"score","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveScore","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveScore"}],"abstract":[{"type":"text","text":"The driving behaviour score for this trip."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/score","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"score"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/score"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location"},{"type":"text","text":" "},{"type":"text","text":"and last to trip end location."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/waypoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waypoints"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/waypoints"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveType/invalid":{"role":"symbol","title":"DriveType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Sometimes, the SDK detects that a trip is invalid after it has been started."},{"type":"text","text":" "},{"type":"text","text":"In these cases, the values for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/events"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/score"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed"},{"type":"text","text":" "},{"type":"text","text":"will have invalid values."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/invalid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processEnd(ofDrive:)":{"role":"symbol","title":"processEnd(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EstimatedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEstimatedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate on the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a drive to have been completed."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processEndOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processend(ofdrive:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"processAnalysisOfDrive:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAnalysisOfDrive:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"processAnalysisOfDrive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo","text":"FairmaticAnalyzedDriveInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"analyzedDriveInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1maxSpeed\/title","value":"maxSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1maxSpeed\/fragments","value":[{"kind":"identifier","text":"maxSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1AnalyzedDriveInfo\/title","value":"FairmaticAnalyzedDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1AnalyzedDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAnalyzedDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EstimatedDriveInfo\/title","value":"FairmaticEstimatedDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EstimatedDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticEstimatedDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1averageSpeed\/title","value":"averageSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1averageSpeed\/fragments","value":[{"kind":"identifier","text":"averageSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1events\/title","value":"events"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1events\/fragments","value":[{"kind":"identifier","text":"events"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/title","value":"processAnalysisOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAnalysisOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1score\/title","value":"score"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1score\/fragments","value":[{"kind":"identifier","text":"score"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1waypoints\/title","value":"waypoints"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1waypoints\/fragments","value":[{"kind":"identifier","text":"waypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1invalid\/title","value":"FairmaticDriveTypeInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/title","value":"processEndOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processEndOfDrive:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}