{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings","text":"Settings"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This callback is fired on the main thread after SDK setup and whenever"},{"type":"text","text":" "},{"type":"text","text":"location permission or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode"},{"type":"text","text":" changes,"},{"type":"text","text":" "},{"type":"text","text":"provided the location permission is determined."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The recommended flow is to ask for the permissions before SDK is setup"},{"type":"text","text":" "},{"type":"text","text":"because if the location permission is not determined this callback will not be"},{"type":"text","text":" "},{"type":"text","text":"fired."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you receive this callback in the foreground you can show the errors using  any UI"},{"type":"text","text":" "},{"type":"text","text":"constructs like alert controllers, if this callback is received in the background you can"},{"type":"text","text":" "},{"type":"text","text":"use a notification. If you want to add actions to the notification then please don’t"},{"type":"text","text":" "},{"type":"text","text":"rely on errors received at the time of notification as they might have changed by"},{"type":"text","text":" "},{"type":"text","text":"the time the user clicks on the notification. Instead use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/getSettings()"},{"type":"text","text":" "},{"type":"text","text":"to get the latest errors and show appropriate message to the user."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter settings A valid "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Settings"},{"type":"text","text":" object that contains"},{"type":"text","text":" "},{"type":"text","text":"information about errors affecting the Fairmatic SDK."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/settingschanged(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/settingschanged(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/settingsChanged(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This callback gives information about errors in device or application settings that"},{"type":"text","text":" "},{"type":"text","text":"may be affecting Fairmatic SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings"},{"kind":"text","text":")"}],"title":"settingsChanged(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate(im)settingsChanged:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"settingsChanged:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/setDriveDetectionMode(_:completionHandler:)":{"role":"symbol","title":"setDriveDetectionMode(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDriveDetectionMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Change the drive detection mode to control how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details. This will override the mode sent"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setdrivedetectionmode(_:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/settingsChanged(_:)":{"role":"symbol","title":"settingsChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback gives information about errors in device or application settings that"},{"type":"text","text":" "},{"type":"text","text":"may be affecting Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/settingsChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"settingsChanged:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/settingschanged(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/getSettings()":{"role":"symbol","title":"getSettings()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/getSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSettings"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/getsettings()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Configuration/driveDetectionMode":{"role":"symbol","title":"driveDetectionMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"abstract":[{"type":"text","text":"Use this mode to control the SDK’s behaviour for detecting drives"},{"type":"text","text":" "},{"type":"text","text":"automatically. This mode can be changed at a later point using"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/configuration\/drivedetectionmode"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Settings":{"role":"symbol","title":"Settings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Settings"}],"abstract":[{"type":"text","text":"This class surfaces errors in device or application settings that affects trip detection in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Settings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Settings"}],"url":"\/documentation\/fairmaticsdk\/settings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"settingsChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"settingsChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"settingsChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings","text":"FairmaticSettings"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"settings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/title","value":"setDriveDetectionMode:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1settingsChanged(_:)\/title","value":"settingsChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1settingsChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"settingsChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1getSettings()\/title","value":"getSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1getSettings()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration~1driveDetectionMode\/title","value":"driveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration~1driveDetectionMode\/fragments","value":[{"kind":"identifier","text":"driveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Settings\/title","value":"FairmaticSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Settings\/fragments","value":[{"kind":"identifier","text":"FairmaticSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}