{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDriveCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveCategory","text":"DriveCategory"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"driveId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"As returned at the end of drive in "},{"type":"codeVoice","code":"DriveInfo"},{"type":"text","text":"."}]}]},{"name":"driveCategory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The category that best indicates the type of Drive."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticfeedback\/adddrivecategory(driveid:drivecategory:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticfeedback\/adddrivecategory(driveid:drivecategory:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addDriveCategory(driveId:driveCategory:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Help "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" improve by providing feedback for a drive detected by the SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDriveCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveCategory","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveCategory"},{"kind":"text","text":")"}],"title":"addDriveCategory(driveId:driveCategory:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticFeedback(cm)addDriveCategoryWithDriveId:driveCategory:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addDriveCategoryWithDriveId:driveCategory:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback/addDriveCategory(driveId:driveCategory:)":{"role":"symbol","title":"addDriveCategory(driveId:driveCategory:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDriveCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveCategory","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveCategory"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Help "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" improve by providing feedback for a drive detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addDriveCategory(driveId:driveCategory:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDriveCategoryWithDriveId:driveCategory:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback\/adddrivecategory(driveid:drivecategory:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback":{"role":"symbol","title":"FairmaticFeedback","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticFeedback"}],"abstract":[{"type":"text","text":"Class for providing feedback back to "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticFeedback"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory":{"role":"symbol","title":"DriveCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveCategory"}],"abstract":[{"type":"text","text":"The category that best indicates the type of trip"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveCategory"}],"url":"\/documentation\/fairmaticsdk\/drivecategory"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"addDriveCategoryWithDriveId:driveCategory:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addDriveCategoryWithDriveId:driveCategory:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addDriveCategoryWithDriveId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"driveId"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveCategory:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveCategory","text":"FairmaticDriveCategory"},{"kind":"text","text":")"},{"kind":"internalParam","text":"driveCategory"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addDriveCategory(driveId:driveCategory:)\/title","value":"addDriveCategoryWithDriveId:driveCategory:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addDriveCategory(driveId:driveCategory:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addDriveCategoryWithDriveId:driveCategory:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback\/title","value":"FairmaticFeedback"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback\/fragments","value":[{"kind":"identifier","text":"FairmaticFeedback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory\/title","value":"FairmaticDriveCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}