{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/tripwarningtype\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType\/!=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"!=(_:_:)","roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@FairmaticSDK@E@FairmaticTripWarningType","extendedModule":"Swift","modules":[{"name":"FairmaticSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType\/Equatable-Implementations"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarningType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/tripwarningtype\/equatable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarningType":{"role":"symbol","title":"TripWarningType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TripWarningType"}],"abstract":[{"type":"text","text":"The value return from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarning\/tripWarningType"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Enum representing warnings detected for the current drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TripWarningType"}],"url":"\/documentation\/fairmaticsdk\/tripwarningtype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarningType/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/tripwarningtype\/!=(_:_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarning/tripWarningType":{"role":"symbol","title":"tripWarningType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tripWarningType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TripWarningType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticTripWarningType"}],"abstract":[{"type":"text","text":"The type of the trip warning."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarning\/tripWarningType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tripWarningType"}],"url":"\/documentation\/fairmaticsdk\/tripwarning\/tripwarningtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarningType\/title","value":"FairmaticTripWarningType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarningType\/fragments","value":[{"kind":"identifier","text":"FairmaticTripWarningType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarning~1tripWarningType\/title","value":"tripWarningType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarning~1tripWarningType\/fragments","value":[{"kind":"identifier","text":"tripWarningType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}