{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedTripDuration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/tripwarningtype\/unexpectedtripduration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/tripwarningtype\/unexpectedtripduration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType\/unexpectedTripDuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The trip duration is unexpectedly large and signifies a possible integration issue."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedTripDuration"}],"title":"TripWarningType.unexpectedTripDuration","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticTripWarningType@FairmaticTripWarningTypeUnexpectedTripDuration","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticTripWarningTypeUnexpectedTripDuration"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarningType":{"role":"symbol","title":"TripWarningType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TripWarningType"}],"abstract":[{"type":"text","text":"The value return from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarning\/tripWarningType"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Enum representing warnings detected for the current drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TripWarningType"}],"url":"\/documentation\/fairmaticsdk\/tripwarningtype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarningType/unexpectedTripDuration":{"role":"symbol","title":"TripWarningType.unexpectedTripDuration","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedTripDuration"}],"abstract":[{"type":"text","text":"The trip duration is unexpectedly large and signifies a possible integration issue."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarningType\/unexpectedTripDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticTripWarningTypeUnexpectedTripDuration"}],"url":"\/documentation\/fairmaticsdk\/tripwarningtype\/unexpectedtripduration"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarning/tripWarningType":{"role":"symbol","title":"tripWarningType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tripWarningType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TripWarningType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticTripWarningType"}],"abstract":[{"type":"text","text":"The type of the trip warning."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarning\/tripWarningType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tripWarningType"}],"url":"\/documentation\/fairmaticsdk\/tripwarning\/tripwarningtype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticTripWarningTypeUnexpectedTripDuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticTripWarningTypeUnexpectedTripDuration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticTripWarningTypeUnexpectedTripDuration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarningType\/title","value":"FairmaticTripWarningType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarningType\/fragments","value":[{"kind":"identifier","text":"FairmaticTripWarningType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarningType~1unexpectedTripDuration\/title","value":"FairmaticTripWarningTypeUnexpectedTripDuration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarningType~1unexpectedTripDuration\/fragments","value":[{"kind":"identifier","text":"FairmaticTripWarningTypeUnexpectedTripDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarning~1tripWarningType\/title","value":"tripWarningType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarning~1tripWarningType\/fragments","value":[{"kind":"identifier","text":"tripWarningType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}