{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/mockaccidentconfig\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a Fairmatic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig"},{"type":"text","text":" object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig(im)init","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig":{"role":"symbol","title":"MockAccidentConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockAccidentConfig"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)"},{"type":"text","text":" for testing accident flow."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockAccidentConfig"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticTest/raiseMockAccident(using:)":{"role":"symbol","title":"raiseMockAccident(using:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"raiseMockAccident"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockAccidentConfig","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticMockAccidentConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to test "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" Accident detection integration. Works only in DEBUG mode,"},{"type":"text","text":" "},{"type":"text","text":"disabled in RELEASE mode."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticTest\/raiseMockAccident(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"raiseMockAccidentUsing:"}],"url":"\/documentation\/fairmaticsdk\/fairmatictest\/raisemockaccident(using:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/MockAccidentConfig/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Creates a Fairmatic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/MockAccidentConfig\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/init()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig\/title","value":"FairmaticMockAccidentConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig\/fragments","value":[{"kind":"identifier","text":"FairmaticMockAccidentConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/title","value":"raiseMockAccidentUsing:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticTest~1raiseMockAccident(using:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"raiseMockAccidentUsing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1MockAccidentConfig~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}