{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticRegion","text":"Region"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Application will not be allowed to change the region post Fairmatic SDK setup."},{"type":"text","text":" "},{"type":"text","text":"To change region application should call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)"},{"type":"text","text":" API first."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/configuration\/region"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/configuration\/region"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration\/region","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This field is OPTIONAL."},{"type":"text","text":" "},{"type":"text","text":"Default value is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region\/us"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Region","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticRegion"}],"title":"region","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration(py)region","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"region"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/fairmaticsdk\/configuration"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Configuration/region":{"role":"symbol","title":"region","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Region","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticRegion"}],"abstract":[{"type":"text","text":"This field is OPTIONAL."},{"type":"text","text":" "},{"type":"text","text":"Default value is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region\/us"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Configuration\/region","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"region"}],"url":"\/documentation\/fairmaticsdk\/configuration\/region"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Region":{"role":"symbol","title":"Region","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Region"}],"abstract":[{"type":"text","text":"Dictates the region where user’s data will reside."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Region"}],"url":"\/documentation\/fairmaticsdk\/region"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/wipeOut(completion:)":{"role":"symbol","title":"wipeOut(completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wipeOut"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Wipe out all the data that Fairmatic keeps locally on the device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wipeOutWithCompletion:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/wipeout(completion:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Region/us":{"role":"symbol","title":"Region.us","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us"}],"abstract":[{"type":"text","text":"Indicates that the user’s data will reside in US region."},{"type":"text","text":" "},{"type":"text","text":"This is the default region."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region\/us","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticRegionUs"}],"url":"\/documentation\/fairmaticsdk\/region\/us"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"region"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"region"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Region","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticRegion","text":"FairmaticRegion"},{"kind":"text","text":" "},{"kind":"identifier","text":"region"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration~1region\/title","value":"region"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Configuration~1region\/fragments","value":[{"kind":"identifier","text":"region"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Region\/title","value":"FairmaticRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Region\/fragments","value":[{"kind":"identifier","text":"FairmaticRegion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1wipeOut(completion:)\/title","value":"wipeOutWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1wipeOut(completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"wipeOutWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Region~1us\/title","value":"FairmaticRegionUs"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Region~1us\/fragments","value":[{"kind":"identifier","text":"FairmaticRegionUs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}