{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overSpeeding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/eventtype\/overspeeding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/eventtype\/overspeeding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This denotes the aggressive behavior of speeding more than allowed."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" in this case."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overSpeeding"}],"title":"EventType.overSpeeding","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticventType@FairmaticventTypeOverSpeeding","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType/overSpeeding":{"role":"symbol","title":"EventType.overSpeeding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overSpeeding"}],"abstract":[{"type":"text","text":"This denotes the aggressive behavior of speeding more than allowed."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" in this case."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/overspeeding"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventType":{"role":"symbol","title":"eventType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"}],"abstract":[{"type":"text","text":"The type of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventType"}],"url":"\/documentation\/fairmaticsdk\/event\/eventtype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/speedingData":{"role":"symbol","title":"speedingData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedingData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpeedingData","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSpeedingData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional data in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":", will be nil otherwise."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speedingData"}],"url":"\/documentation\/fairmaticsdk\/event\/speedingdata"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType":{"role":"symbol","title":"EventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventType"}],"abstract":[{"type":"text","text":"The event type as specified in "},{"type":"codeVoice","code":"Event.eventType"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventType"}],"url":"\/documentation\/fairmaticsdk\/eventtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticventTypeOverSpeeding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/title","value":"FairmaticventTypeOverSpeeding"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/title","value":"eventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/fragments","value":[{"kind":"identifier","text":"eventType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/title","value":"speedingData"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/fragments","value":[{"kind":"identifier","text":"speedingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType\/title","value":"FairmaticventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType\/fragments","value":[{"kind":"identifier","text":"FairmaticventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}