{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundProcessing"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/sdkhealthreason\/backgroundprocessing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/sdkhealthreason\/backgroundprocessing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason\/backgroundProcessing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates the SDK health will recorded due to background processing"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundProcessing"}],"title":"SDKHealthReason.backgroundProcessing","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticSDKHealthReason@FairmaticSDKHealthReasonBackgroundProcessing","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SDKHealthReason/backgroundProcessing":{"role":"symbol","title":"SDKHealthReason.backgroundProcessing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundProcessing"}],"abstract":[{"type":"text","text":"Indicates the SDK health will recorded due to background processing"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason\/backgroundProcessing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/backgroundprocessing"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SDKHealthReason":{"role":"symbol","title":"SDKHealthReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKHealthReason"}],"abstract":[{"type":"text","text":"Dictates the reason for is logging SDK Health"},{"type":"text","text":" "},{"type":"text","text":"The SDK health will be recorded when there is any update in permission from last recorded SDK health."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKHealthReason"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSDKHealthReasonBackgroundProcessing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason~1backgroundProcessing\/title","value":"FairmaticSDKHealthReasonBackgroundProcessing"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason~1backgroundProcessing\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonBackgroundProcessing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason\/title","value":"FairmaticSDKHealthReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}