{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentPushNotification"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/sdkhealthreason\/silentpushnotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/sdkhealthreason\/silentpushnotification"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason\/silentPushNotification","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates the SDK health will recorded due to silent push notification"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentPushNotification"}],"title":"SDKHealthReason.silentPushNotification","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticSDKHealthReason@FairmaticSDKHealthReasonSilentPushNotification","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SDKHealthReason/silentPushNotification":{"role":"symbol","title":"SDKHealthReason.silentPushNotification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentPushNotification"}],"abstract":[{"type":"text","text":"Indicates the SDK health will recorded due to silent push notification"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason\/silentPushNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason\/silentpushnotification"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SDKHealthReason":{"role":"symbol","title":"SDKHealthReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKHealthReason"}],"abstract":[{"type":"text","text":"Dictates the reason for is logging SDK Health"},{"type":"text","text":" "},{"type":"text","text":"The SDK health will be recorded when there is any update in permission from last recorded SDK health."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SDKHealthReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKHealthReason"}],"url":"\/documentation\/fairmaticsdk\/sdkhealthreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSDKHealthReasonSilentPushNotification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason~1silentPushNotification\/title","value":"FairmaticSDKHealthReasonSilentPushNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason~1silentPushNotification\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReasonSilentPushNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason\/title","value":"FairmaticSDKHealthReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SDKHealthReason\/fragments","value":[{"kind":"identifier","text":"FairmaticSDKHealthReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}