{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventRatings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEventRatings","text":"EventRatings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/eventratings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/eventratings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/eventRatings","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The ratings of individual events for this trip"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventRatings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventRatings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEventRatings"}],"title":"eventRatings","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveInfo(py)eventRatings","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"eventRatings"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings":{"role":"symbol","title":"EventRatings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventRatings"}],"abstract":[{"type":"text","text":"Represents ratings associated with the various event types for a trip. Higher rating for an event"},{"type":"text","text":" "},{"type":"text","text":"represents safe driving behaviour with respect to that event. For cases where rating is absent,"},{"type":"text","text":" "},{"type":"text","text":"``StarRating\/NA` is reported."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventRatings"}],"url":"\/documentation\/fairmaticsdk\/eventratings"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/eventRatings":{"role":"symbol","title":"eventRatings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventRatings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventRatings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEventRatings"}],"abstract":[{"type":"text","text":"The ratings of individual events for this trip"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/eventRatings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventRatings"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/eventratings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"eventRatings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"eventRatings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEventRatings","text":"FairmaticEventRatings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eventRatings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventRatings\/title","value":"FairmaticEventRatings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventRatings\/fragments","value":[{"kind":"identifier","text":"FairmaticEventRatings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1eventRatings\/title","value":"eventRatings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1eventRatings\/fragments","value":[{"kind":"identifier","text":"eventRatings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}