{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"five"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/starrating\/five"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/starrating\/five"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/five","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates best rating."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"five"}],"title":"StarRating.five","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticStarRating@FairmaticStarRatingFive","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingFive"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating":{"role":"symbol","title":"StarRating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StarRating"}],"abstract":[{"type":"text","text":"Fairmatic follows the star rating system, under which five star defined as the best rating with"},{"type":"text","text":" "},{"type":"text","text":"one being the worst."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StarRating"}],"url":"\/documentation\/fairmaticsdk\/starrating"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/five":{"role":"symbol","title":"StarRating.five","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"five"}],"abstract":[{"type":"text","text":"Indicates best rating."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/five","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingFive"}],"url":"\/documentation\/fairmaticsdk\/starrating\/five"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticStarRatingFive"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingFive"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticStarRatingFive"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating\/title","value":"FairmaticStarRating"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRating"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1five\/title","value":"FairmaticStarRatingFive"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1five\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingFive"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}