{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationServiceOff"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/settingserrortype\/locationserviceoff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/settingserrortype\/locationserviceoff"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationServiceOff","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The location service is turned off."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationServiceOff"}],"title":"SettingsErrorType.locationServiceOff","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticSettingsErrorType@FairmaticSettingsErrorTypeLocationServiceOff","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType/locationServiceOff":{"role":"symbol","title":"SettingsErrorType.locationServiceOff","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationServiceOff"}],"abstract":[{"type":"text","text":"The location service is turned off."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType\/locationServiceOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype\/locationserviceoff"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsError":{"role":"symbol","title":"SettingsError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsError"}],"abstract":[{"type":"text","text":"This class represent an error in device or application settings that is affecting"},{"type":"text","text":" "},{"type":"text","text":"the ability of the SDK to detect trips."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsError"}],"url":"\/documentation\/fairmaticsdk\/settingserror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/SettingsErrorType":{"role":"symbol","title":"SettingsErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsErrorType"}],"abstract":[{"type":"text","text":"Error type for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsError"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/SettingsErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsErrorType"}],"url":"\/documentation\/fairmaticsdk\/settingserrortype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSettingsErrorTypeLocationServiceOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationServiceOff\/title","value":"FairmaticSettingsErrorTypeLocationServiceOff"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType~1locationServiceOff\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorTypeLocationServiceOff"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsError\/title","value":"FairmaticSettingsError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsError\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType\/title","value":"FairmaticSettingsErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1SettingsErrorType\/fragments","value":[{"kind":"identifier","text":"FairmaticSettingsErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}