{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aggressiveAccelerationRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating","text":"StarRating"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/eventratings\/aggressiveaccelerationrating"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/aggressiveAccelerationRating","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents rating associated with aggressively accelerating while driving."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aggressiveAccelerationRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"title":"aggressiveAccelerationRating","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:12FairmaticSDK12EventRatingsC28aggressiveAccelerationRatingAA04StarG0Ovp","modules":[{"name":"FairmaticSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings/aggressiveAccelerationRating":{"role":"symbol","title":"aggressiveAccelerationRating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aggressiveAccelerationRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"abstract":[{"type":"text","text":"Represents rating associated with aggressively accelerating while driving."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/aggressiveAccelerationRating","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventratings\/aggressiveaccelerationrating"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings":{"role":"symbol","title":"EventRatings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventRatings"}],"abstract":[{"type":"text","text":"Represents ratings associated with the various event types for a trip. Higher rating for an event"},{"type":"text","text":" "},{"type":"text","text":"represents safe driving behaviour with respect to that event. For cases where rating is absent,"},{"type":"text","text":" "},{"type":"text","text":"``StarRating\/NA` is reported."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventRatings"}],"url":"\/documentation\/fairmaticsdk\/eventratings"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating":{"role":"symbol","title":"StarRating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StarRating"}],"abstract":[{"type":"text","text":"Fairmatic follows the star rating system, under which five star defined as the best rating with"},{"type":"text","text":" "},{"type":"text","text":"one being the worst."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StarRating"}],"url":"\/documentation\/fairmaticsdk\/starrating"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventRatings\/title","value":"FairmaticEventRatings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventRatings\/fragments","value":[{"kind":"identifier","text":"FairmaticEventRatings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating\/title","value":"FairmaticStarRating"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRating"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}