{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/scannedbeaconinfo\/init(uuid:major:minor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/scannedbeaconinfo\/init(uuid:major:minor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize the beacon with UUID, major, minor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"title":"init(uuid:major:minor:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo(im)initWithUuid:major:minor:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUuid:major:minor:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo/init(uuid:major:minor:)":{"role":"symbol","title":"init(uuid:major:minor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize the beacon with UUID, major, minor."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo\/init(uuid:major:minor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUuid:major:minor:"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo\/init(uuid:major:minor:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ScannedBeaconInfo":{"role":"symbol","title":"ScannedBeaconInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScannedBeaconInfo"}],"abstract":[{"type":"text","text":"Wrapper for beacons scanned using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ScannedBeaconInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScannedBeaconInfo"}],"url":"\/documentation\/fairmaticsdk\/scannedbeaconinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getNearbyBeacons(uuid:major:minor:completionHandler:)":{"role":"symbol","title":"getNearbyBeacons(uuid:major:minor:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNearbyBeacons"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scannedBeacons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScannedBeaconInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get all the beacons which are in the device’s range."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getnearbybeacons(uuid:major:minor:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithUuid:major:minor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUuid:major:minor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUuid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"uuid"},{"kind":"text","text":" "},{"kind":"identifier","text":"major:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int32_t","preciseIdentifier":"c:@T@int32_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"major"},{"kind":"text","text":" "},{"kind":"identifier","text":"minor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int32_t","preciseIdentifier":"c:@T@int32_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(uuid:major:minor:)\/title","value":"initWithUuid:major:minor:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo~1init(uuid:major:minor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUuid:major:minor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo\/title","value":"FairmaticScannedBeaconInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ScannedBeaconInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticScannedBeaconInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/title","value":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}