{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticAccidentConfidence) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentconfidence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentconfidence"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH","doc:\/\/com.fairmatic.FairmaticSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"title":"AccidentConfidence","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/invalid","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/low"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/Equatable-Implementations","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/invalid":{"role":"symbol","title":"AccidentConfidence.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Confidence of an invalidating callback. This might be sent only when the application has opted into multiple accident callbacks"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceInvalid"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence\/invalid"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/accidentconfidence\/init(rawvalue:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/low":{"role":"symbol","title":"AccidentConfidence.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[{"type":"text","text":"Accident was detected, but with a low confidence. The application might ask"},{"type":"text","text":" "},{"type":"text","text":"the user for feedback before notifying any emergency services."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence\/low"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SY"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/accidentconfidence\/rawrepresentable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/accidentconfidence\/equatable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/high":{"role":"symbol","title":"AccidentConfidence.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"Accident was detected with a high confidence. The application might inform"},{"type":"text","text":" "},{"type":"text","text":"emergency services directly after waiting for some time for user feedback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence\/high"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/high","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/invalid","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/low"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticAccidentConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1invalid\/title","value":"FairmaticAccidentConfidenceInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1low\/title","value":"FairmaticAccidentConfidenceLow"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1low\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1high\/title","value":"FairmaticAccidentConfidenceHigh"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1high\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceHigh"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}