{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticCollisionSeverity) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollisionSeverity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/collisionseverity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/collisionseverity"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH","doc:\/\/com.fairmatic.FairmaticSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Collision severity of the detected accident."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollisionSeverity"}],"title":"CollisionSeverity","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CollisionSeverity"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/high","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/low","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/Equatable-Implementations","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/collisionseverity\/rawrepresentable-implementations"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/collisionseverity\/init(rawvalue:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/low":{"role":"symbol","title":"CollisionSeverity.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[{"type":"text","text":"Low severity collision"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity\/low"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity":{"role":"symbol","title":"CollisionSeverity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollisionSeverity"}],"abstract":[{"type":"text","text":"Collision severity of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollisionSeverity"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/unknown":{"role":"symbol","title":"CollisionSeverity.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown severity collision."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity\/unknown"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SY"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/collisionseverity\/equatable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity/high":{"role":"symbol","title":"CollisionSeverity.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"High severity collision."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticCollisionSeverityHigh"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity\/high"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticCollisionSeverity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverity"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticCollisionSeverity"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/high","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/low","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticCollisionSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1low\/title","value":"FairmaticCollisionSeverityLow"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1low\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityLow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity\/title","value":"FairmaticCollisionSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1unknown\/title","value":"FairmaticCollisionSeverityUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1unknown\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1high\/title","value":"FairmaticCollisionSeverityHigh"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity~1high\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverityHigh"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}