{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriveCategory) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveCategory"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivecategory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/drivecategory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The category that best indicates the type of trip"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveCategory"}],"title":"DriveCategory","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticDriveCategory","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriveCategory"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/bicycle","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/bus","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/car","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/carDriver","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/carPassenger","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/flight","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/foot","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/invalid","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/motorcycle","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/notCar","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/other","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/train","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/transit"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/drivecategory\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/motorcycle":{"role":"symbol","title":"DriveCategory.motorcycle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"motorcycle"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken on a motorcycle"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/motorcycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryMotorcycle"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/motorcycle"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/flight":{"role":"symbol","title":"DriveCategory.flight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"flight"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken using some form of air travel"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/flight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryFlight"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/flight"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/carPassenger":{"role":"symbol","title":"DriveCategory.carPassenger","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"carPassenger"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken in a car and the user was a passenger"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/carPassenger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryCarPassenger"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/carpassenger"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/drivecategory\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/carDriver":{"role":"symbol","title":"DriveCategory.carDriver","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"carDriver"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken in a car and the user was the driver"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/carDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryCarDriver"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/cardriver"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/bus":{"role":"symbol","title":"DriveCategory.bus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bus"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken in a bus"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/bus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryBus"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/bus"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/drivecategory\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/transit":{"role":"symbol","title":"DriveCategory.transit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken using some form of public transit"},{"type":"text","text":" "},{"type":"text","text":"(bus\/train\/subway\/tram etc)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/transit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryTransit"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/transit"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/invalid":{"role":"symbol","title":"DriveCategory.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Indicates that there wasn’t enough movement and this shouldn’t have been"},{"type":"text","text":" "},{"type":"text","text":"detected as a trip"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/invalid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory":{"role":"symbol","title":"DriveCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveCategory"}],"abstract":[{"type":"text","text":"The category that best indicates the type of trip"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveCategory"}],"url":"\/documentation\/fairmaticsdk\/drivecategory"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/car":{"role":"symbol","title":"DriveCategory.car","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"car"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken in a car"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/car","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryCar"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/car"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/bicycle":{"role":"symbol","title":"DriveCategory.bicycle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bicycle"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken on a bicycle"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/bicycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryBicycle"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/bicycle"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/other":{"role":"symbol","title":"DriveCategory.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"abstract":[{"type":"text","text":"Fallback when the above options do not cover the use case."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryOther"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/other"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/train":{"role":"symbol","title":"DriveCategory.train","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"train"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken in a train or a subway"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/train","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryTrain"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/train"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/notCar":{"role":"symbol","title":"DriveCategory.notCar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notCar"}],"abstract":[{"type":"text","text":"Indicates that the trip was not taken in a car. This includes everything"},{"type":"text","text":" "},{"type":"text","text":"other than "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/car"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/notCar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryNotCar"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/notcar"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveCategory/foot":{"role":"symbol","title":"DriveCategory.foot","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"foot"}],"abstract":[{"type":"text","text":"Indicates that the trip was taken on foot (either walking or running)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/foot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveCategoryFoot"}],"url":"\/documentation\/fairmaticsdk\/drivecategory\/foot"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveCategory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriveCategory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/bicycle","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/bus","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/car","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/carDriver","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/carPassenger","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/flight","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/foot","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/invalid","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/motorcycle","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/notCar","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/other","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/train","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveCategory\/transit"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriveCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1motorcycle\/title","value":"FairmaticDriveCategoryMotorcycle"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1motorcycle\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryMotorcycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1flight\/title","value":"FairmaticDriveCategoryFlight"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1flight\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryFlight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1carPassenger\/title","value":"FairmaticDriveCategoryCarPassenger"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1carPassenger\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryCarPassenger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1carDriver\/title","value":"FairmaticDriveCategoryCarDriver"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1carDriver\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryCarDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1bus\/title","value":"FairmaticDriveCategoryBus"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1bus\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryBus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1transit\/title","value":"FairmaticDriveCategoryTransit"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1transit\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryTransit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1invalid\/title","value":"FairmaticDriveCategoryInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory\/title","value":"FairmaticDriveCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1car\/title","value":"FairmaticDriveCategoryCar"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1car\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryCar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1bicycle\/title","value":"FairmaticDriveCategoryBicycle"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1bicycle\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryBicycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1other\/title","value":"FairmaticDriveCategoryOther"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1other\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryOther"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1train\/title","value":"FairmaticDriveCategoryTrain"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1train\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryTrain"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1notCar\/title","value":"FairmaticDriveCategoryNotCar"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1notCar\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryNotCar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1foot\/title","value":"FairmaticDriveCategoryFoot"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveCategory~1foot\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveCategoryFoot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}