{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriveResumeInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveResumeInfo"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is called after the drive recording resumes after a gap. The gap may occur due to"},{"type":"text","text":" "},{"type":"text","text":"an application restart by the OS, application kill and restart by a user, an application crash"},{"type":"text","text":" "},{"type":"text","text":"etc."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveresumeinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveresumeinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Information about a drive that was resumed in the "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveResumeInfo"}],"title":"DriveResumeInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriveResumeInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/distance","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveGapEndTimestampMillis","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveGapStartTimestampMillis","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/insurancePeriod","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/sessionId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/startTimestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/trackingId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/waypoints"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/startTimestamp":{"role":"symbol","title":"startTimestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The start timestamp of trip in milliseconds since epoch."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/startTimestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTimestamp"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/starttimestamp"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/LocationPoint":{"role":"symbol","title":"LocationPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationPoint"}],"abstract":[{"type":"text","text":"Represents a geographical coordinate."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/LocationPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationPoint"}],"url":"\/documentation\/fairmaticsdk\/locationpoint"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/driveId":{"role":"symbol","title":"driveId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The unique Id for this drive"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveId"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/driveid"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/driveGapStartTimestampMillis":{"role":"symbol","title":"driveGapStartTimestampMillis","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveGapStartTimestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The start timestamp of the gap in drive recording in milliseconds."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveGapStartTimestampMillis","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveGapStartTimestampMillis"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/drivegapstarttimestampmillis"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/trackingId":{"role":"symbol","title":"trackingId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Tracking id is specified by the enclosing application when it"},{"type":"text","text":" "},{"type":"text","text":"wants to start a drive manually by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(_:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/trackingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingId"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/trackingid"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location"},{"type":"text","text":" "},{"type":"text","text":"and last to trip end location."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/waypoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waypoints"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/waypoints"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/insurancePeriod":{"role":"symbol","title":"insurancePeriod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insurancePeriod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsurancePeriod","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod"}],"abstract":[{"type":"text","text":"The insurance period for this drive"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/insurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/insuranceperiod"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/driveGapEndTimestampMillis":{"role":"symbol","title":"driveGapEndTimestampMillis","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveGapEndTimestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The end timestamp of the gap in drive recording in milliseconds."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveGapEndTimestampMillis","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveGapEndTimestampMillis"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/drivegapendtimestampmillis"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/startSession(_:)":{"role":"symbol","title":"startSession(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start a session in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSession:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startsession(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/sessionId":{"role":"symbol","title":"sessionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Session id is specified by the enclosing application when it wants to"},{"type":"text","text":" "},{"type":"text","text":"record a session using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/sessionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionId"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/sessionid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/startManualDrive(_:completionHandler:)":{"role":"symbol","title":"startManualDrive(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDrive:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(_:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo":{"role":"symbol","title":"DriveResumeInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveResumeInfo"}],"abstract":[{"type":"text","text":"Information about a drive that was resumed in the "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveResumeInfo"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveResumeInfo/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance of the trip in metres"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/distance"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveResumeInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveResumeInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriveResumeInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/distance","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveGapEndTimestampMillis","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveGapStartTimestampMillis","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/driveId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/insurancePeriod","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/sessionId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/startTimestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/trackingId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveResumeInfo\/waypoints"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriveResumeInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1startTimestamp\/title","value":"startTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1startTimestamp\/fragments","value":[{"kind":"identifier","text":"startTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1LocationPoint\/title","value":"FairmaticLocationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1LocationPoint\/fragments","value":[{"kind":"identifier","text":"FairmaticLocationPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1driveId\/title","value":"driveId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1driveId\/fragments","value":[{"kind":"identifier","text":"driveId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1driveGapStartTimestampMillis\/title","value":"driveGapStartTimestampMillis"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1driveGapStartTimestampMillis\/fragments","value":[{"kind":"identifier","text":"driveGapStartTimestampMillis"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1trackingId\/title","value":"trackingId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1trackingId\/fragments","value":[{"kind":"identifier","text":"trackingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1waypoints\/title","value":"waypoints"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1waypoints\/fragments","value":[{"kind":"identifier","text":"waypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1insurancePeriod\/title","value":"insurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1insurancePeriod\/fragments","value":[{"kind":"identifier","text":"insurancePeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1driveGapEndTimestampMillis\/title","value":"driveGapEndTimestampMillis"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1driveGapEndTimestampMillis\/fragments","value":[{"kind":"identifier","text":"driveGapEndTimestampMillis"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/title","value":"startSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1sessionId\/title","value":"sessionId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1sessionId\/fragments","value":[{"kind":"identifier","text":"sessionId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(_:completionHandler:)\/title","value":"startManualDrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo\/title","value":"FairmaticDriveResumeInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveResumeInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveResumeInfo~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}