{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticEvent) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/event"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/event"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject","doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP","doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a driving behavior event like phone use, aggressive acceleration etc."},{"type":"text","text":" "},{"type":"text","text":"It is part of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" object of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"title":"Event","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticEvent","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Event"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/endTime","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventSeverity","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/startLocation","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/startTime","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/stopLocation","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection"]}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/startTime":{"role":"symbol","title":"startTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Epoch timestamp of the start of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/startTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"url":"\/documentation\/fairmaticsdk\/event\/starttime"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/endTime":{"role":"symbol","title":"endTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Epoch timestamp of the end of the event;"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/endTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endTime"}],"url":"\/documentation\/fairmaticsdk\/event\/endtime"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/stopLocation":{"role":"symbol","title":"stopLocation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"}],"abstract":[{"type":"text","text":"Stop location of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/stopLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopLocation"}],"url":"\/documentation\/fairmaticsdk\/event\/stoplocation"},"doc://com.fairmatic.FairmaticSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType/overSpeeding":{"role":"symbol","title":"EventType.overSpeeding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overSpeeding"}],"abstract":[{"type":"text","text":"This denotes the aggressive behavior of speeding more than allowed."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" in this case."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/overspeeding"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/startLocation":{"role":"symbol","title":"startLocation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"}],"abstract":[{"type":"text","text":"Start location of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/startLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLocation"}],"url":"\/documentation\/fairmaticsdk\/event\/startlocation"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processEnd(ofDrive:)":{"role":"symbol","title":"processEnd(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EstimatedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEstimatedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate on the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a drive to have been completed."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processEndOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processend(ofdrive:)"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/turnDirection":{"role":"symbol","title":"turnDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TurnDirection","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticTurnDirection"}],"abstract":[{"type":"text","text":"Denotes the turn direction of a hard turn whether a left or right turn."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnDirection"}],"url":"\/documentation\/fairmaticsdk\/event\/turndirection"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/speedingData":{"role":"symbol","title":"speedingData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedingData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpeedingData","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSpeedingData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional data in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":", will be nil otherwise."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speedingData"}],"url":"\/documentation\/fairmaticsdk\/event\/speedingdata"},"doc://com.fairmatic.FairmaticSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventSeverity":{"role":"symbol","title":"eventSeverity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticEventSeverity"}],"abstract":[{"type":"text","text":"The severity of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventSeverity"}],"url":"\/documentation\/fairmaticsdk\/event\/eventseverity"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event":{"role":"symbol","title":"Event","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"abstract":[{"type":"text","text":"Represents a driving behavior event like phone use, aggressive acceleration etc."},{"type":"text","text":" "},{"type":"text","text":"It is part of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" object of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"url":"\/documentation\/fairmaticsdk\/event"},"doc://com.fairmatic.FairmaticSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"},"doc://com.fairmatic.FairmaticSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventType":{"role":"symbol","title":"eventType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"}],"abstract":[{"type":"text","text":"The type of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventType"}],"url":"\/documentation\/fairmaticsdk\/event\/eventtype"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/endTime","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventSeverity","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/startLocation","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/startTime","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/stopLocation","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1startTime\/title","value":"startTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1startTime\/fragments","value":[{"kind":"identifier","text":"startTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1endTime\/title","value":"endTime"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1endTime\/fragments","value":[{"kind":"identifier","text":"endTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1stopLocation\/title","value":"stopLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1stopLocation\/fragments","value":[{"kind":"identifier","text":"stopLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/title","value":"FairmaticventTypeOverSpeeding"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1startLocation\/title","value":"startLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1startLocation\/fragments","value":[{"kind":"identifier","text":"startLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/title","value":"processEndOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processEndOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1turnDirection\/title","value":"turnDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1turnDirection\/fragments","value":[{"kind":"identifier","text":"turnDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/title","value":"speedingData"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/fragments","value":[{"kind":"identifier","text":"speedingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventSeverity\/title","value":"eventSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventSeverity\/fragments","value":[{"kind":"identifier","text":"eventSeverity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event\/title","value":"FairmaticEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event\/fragments","value":[{"kind":"identifier","text":"FairmaticEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/title","value":"eventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/fragments","value":[{"kind":"identifier","text":"eventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}