{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticPauseReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticpausereason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticpausereason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/businessHours","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/notPaused","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/user"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticPauseReason"}],"title":"FairmaticPauseReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticPauseReason","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReason"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticpausereason\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason/user":{"role":"symbol","title":"FairmaticPauseReason.user","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/user","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReasonUser"}],"url":"\/documentation\/fairmaticsdk\/fairmaticpausereason\/user"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason/businessHours":{"role":"symbol","title":"FairmaticPauseReason.businessHours","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"businessHours"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/businessHours","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReasonBusinessHours"}],"url":"\/documentation\/fairmaticsdk\/fairmaticpausereason\/businesshours"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason":{"role":"symbol","title":"FairmaticPauseReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticPauseReason"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReason"}],"url":"\/documentation\/fairmaticsdk\/fairmaticpausereason"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticpausereason\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason/notPaused":{"role":"symbol","title":"FairmaticPauseReason.notPaused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notPaused"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/notPaused","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReasonNotPaused"}],"url":"\/documentation\/fairmaticsdk\/fairmaticpausereason\/notpaused"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticpausereason\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticPauseReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticPauseReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/businessHours","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/notPaused","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason\/user"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticPauseReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason~1user\/title","value":"FairmaticPauseReasonUser"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason~1user\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReasonUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason~1businessHours\/title","value":"FairmaticPauseReasonBusinessHours"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason~1businessHours\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReasonBusinessHours"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason\/title","value":"FairmaticPauseReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason~1notPaused\/title","value":"FairmaticPauseReasonNotPaused"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason~1notPaused\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReasonNotPaused"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}