{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticFeedback) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticFeedback"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticfeedback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticfeedback"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Class for providing feedback back to "},{"type":"codeVoice","code":"Fairmatic"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticFeedback"}],"title":"FairmaticFeedback","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticFeedback","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticFeedback"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addDriveCategory(driveId:driveCategory:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback/addDriveCategory(driveId:driveCategory:)":{"role":"symbol","title":"addDriveCategory(driveId:driveCategory:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDriveCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveCategory","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveCategory"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Help "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" improve by providing feedback for a drive detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addDriveCategory(driveId:driveCategory:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDriveCategoryWithDriveId:driveCategory:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback\/adddrivecategory(driveid:drivecategory:)"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback":{"role":"symbol","title":"FairmaticFeedback","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticFeedback"}],"abstract":[{"type":"text","text":"Class for providing feedback back to "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticFeedback"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback\/init"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)":{"role":"symbol","title":"addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventOccurrence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"occurrence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Help "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" improve by providing information about whether an"},{"type":"text","text":" "},{"type":"text","text":"event detected by the SDK occurred or not."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback\/addeventoccurrence(driveid:eventtimestamp:eventtype:occurrence:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticFeedback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticFeedback"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticFeedback"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addDriveCategory(driveId:driveCategory:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticFeedback"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addDriveCategory(driveId:driveCategory:)\/title","value":"addDriveCategoryWithDriveId:driveCategory:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addDriveCategory(driveId:driveCategory:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addDriveCategoryWithDriveId:driveCategory:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback\/title","value":"FairmaticFeedback"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback\/fragments","value":[{"kind":"identifier","text":"FairmaticFeedback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)\/title","value":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}