{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(Fairmatic) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmatic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmatic"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject","doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP","doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Fairmatic API."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"role":"symbol","title":"Fairmatic","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)Fairmatic","modules":[{"name":"FairmaticSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/buildVersion","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getEventSupportForDevice","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isAccidentDetectionSupportedByDevice","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isSDKSetup"]},{"title":"Type Methods","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getDriveDetectionMode()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getSettings()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/logSDKHealth(_:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDelegate(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDriveWithPeriod1(completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopPeriod(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopSession()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/teardown(completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/uploadAllDebugDataAndLogs()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)"]}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/stopPeriod(_:)":{"role":"symbol","title":"stopPeriod(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopPeriod"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Stop currently ongoing Fairmatic insurance period if any."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopPeriod(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopPeriod:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/stopperiod(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/fairmaticsdk\/configuration"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/teardown(completionHandler:)":{"role":"symbol","title":"teardown(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"teardown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Stops driving data collection. The application can disable the Fairmatic SDK"},{"type":"text","text":" "},{"type":"text","text":"by invoking this method. This method is asynchronous."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/teardown(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"teardownWithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/teardown(completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod3:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod3:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod3"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 3 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod3:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode":{"role":"symbol","title":"DriveDetectionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveDetectionMode"}],"abstract":[{"type":"text","text":"Dictates the functioning of Fairmatic’s drive detection."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/getDriveDetectionMode()":{"role":"symbol","title":"getDriveDetectionMode()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDriveDetectionMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"abstract":[{"type":"text","text":"The drive detection mode controls how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getDriveDetectionMode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDriveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/getdrivedetectionmode()"},"doc://com.fairmatic.FairmaticSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/activeDriveInfo":{"role":"symbol","title":"activeDriveInfo","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeDriveInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActiveDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get info on the currently active drive. If sdk is not setup or if"},{"type":"text","text":" "},{"type":"text","text":"no drive is in progress, nil is returned."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activeDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/activedriveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType":{"role":"symbol","title":"EventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventType"}],"abstract":[{"type":"text","text":"The event type as specified in "},{"type":"codeVoice","code":"Event.eventType"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventType"}],"url":"\/documentation\/fairmaticsdk\/eventtype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/logSDKHealth(_:completionHandler:)":{"role":"symbol","title":"logSDKHealth(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logSDKHealth"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDKHealthReason","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticSDKHealthReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Logs all the critical permissions required by the SDK"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/logSDKHealth(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logSDKHealth:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/logsdkhealth(_:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setDriveDetectionMode(_:completionHandler:)":{"role":"symbol","title":"setDriveDetectionMode(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDriveDetectionMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Change the drive detection mode to control how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details. This will override the mode sent"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setdrivedetectionmode(_:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/isAccidentDetectionSupportedByDevice":{"role":"symbol","title":"isAccidentDetectionSupportedByDevice","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAccidentDetectionSupportedByDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns a boolean indicating whether Fairmatic SDK can detect accidents"},{"type":"text","text":" "},{"type":"text","text":"on this devices or not."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isAccidentDetectionSupportedByDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAccidentDetectionSupportedByDevice"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/isaccidentdetectionsupportedbydevice"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/getEventSupportForDevice":{"role":"symbol","title":"getEventSupportForDevice","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEventSupportForDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"}],"abstract":[{"type":"text","text":"Returns a NSDictionary with keys as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType"},{"type":"text","text":" and values being Bool which represent"},{"type":"text","text":" "},{"type":"text","text":"if a particular event will be detected by the SDK on this device."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getEventSupportForDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getEventSupportForDevice"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/geteventsupportfordevice"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/buildVersion":{"role":"symbol","title":"buildVersion","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns an identifier which can be used to identify this SDK build."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/buildVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildVersion"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/buildversion"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/getSettings()":{"role":"symbol","title":"getSettings()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSettings"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/getsettings()"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/isSDKSetup":{"role":"symbol","title":"isSDKSetup","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSDKSetup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the Fairmatic SDK is already setup. Else "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isSDKSetup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isSDKSetup"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/issdksetup"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/isValidInputParameter(_:)":{"role":"symbol","title":"isValidInputParameter(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidInputParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this method to check whether the parameter string passed"},{"type":"text","text":" "},{"type":"text","text":"to the SDK is valid."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isValidInputParameter:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/isvalidinputparameter(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/stopSession()":{"role":"symbol","title":"stopSession()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopSession"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stop currently ongoing session. No-op if no session is ongoing. Trips that"},{"type":"text","text":" "},{"type":"text","text":"start after this call do not belong to the session. Ongoing trips at the time of this"},{"type":"text","text":" "},{"type":"text","text":"call will continue to belong to the session that was just stopped. Also see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopSession()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopSession"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/stopsession()"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDriveWithPeriod1(completionHandler:)":{"role":"symbol","title":"startDriveWithPeriod1(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDriveWithPeriod1"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 1 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDriveWithPeriod1(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod1WithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrivewithperiod1(completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setup(with:delegate:completionHandler:)":{"role":"symbol","title":"setup(with:delegate:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDelegate","preciseIdentifier":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Initializes the Fairmatic SDK to automatically detect driving and collect"},{"type":"text","text":" "},{"type":"text","text":"data. Client code should call this method before anything else in the Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setup(with:delegate:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setDelegate(_:)":{"role":"symbol","title":"setDelegate(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FairmaticDelegate","preciseIdentifier":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set delegate to receive callbacks for various events from Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate"},{"type":"text","text":" for further details."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDelegate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setdelegate(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/stopManualDrive(completionHandler:)":{"role":"symbol","title":"stopManualDrive(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This should be called to indicate the end of a drive started by invoking"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopManualDriveWithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/stopmanualdrive(completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/wipeOut(completion:)":{"role":"symbol","title":"wipeOut(completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wipeOut"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Wipe out all the data that Fairmatic keeps locally on the device."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wipeOutWithCompletion:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/wipeout(completion:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startSession(_:)":{"role":"symbol","title":"startSession(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start a session in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSession:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startsession(_:)"},"doc://com.fairmatic.FairmaticSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod2:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod2:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 2 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod2:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/uploadAllDebugDataAndLogs()":{"role":"symbol","title":"uploadAllDebugDataAndLogs()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Send a debug report of the current driver to Fairmatic."},{"type":"text","text":" "},{"type":"text","text":"The Fairmatic SDK will create a background task to ensure the"},{"type":"text","text":" "},{"type":"text","text":"completion of this upload task."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/uploadAllDebugDataAndLogs()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uploadAllDebugDataAndLogs"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/uploadalldebugdataandlogs()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Fairmatic"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/activeDriveInfo","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/buildVersion","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getEventSupportForDevice","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isAccidentDetectionSupportedByDevice","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isSDKSetup"]},{"title":"Type Methods","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getDriveDetectionMode()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/getSettings()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/logSDKHealth(_:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDelegate(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDriveWithPeriod1(completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopManualDrive(completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopPeriod(_:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/stopSession()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/teardown(completionHandler:)","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/uploadAllDebugDataAndLogs()","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/wipeOut(completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopPeriod(_:)\/title","value":"stopPeriod:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopPeriod(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopPeriod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1teardown(completionHandler:)\/title","value":"teardownWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1teardown(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"teardownWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/title","value":"startDriveWithPeriod3:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/title","value":"FairmaticDriveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getDriveDetectionMode()\/title","value":"getDriveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getDriveDetectionMode()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDriveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1activeDriveInfo\/title","value":"activeDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1activeDriveInfo\/fragments","value":[{"kind":"identifier","text":"activeDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType\/title","value":"FairmaticventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType\/fragments","value":[{"kind":"identifier","text":"FairmaticventType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1logSDKHealth(_:completionHandler:)\/title","value":"logSDKHealth:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1logSDKHealth(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logSDKHealth:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/title","value":"setDriveDetectionMode:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isAccidentDetectionSupportedByDevice\/title","value":"isAccidentDetectionSupportedByDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isAccidentDetectionSupportedByDevice\/fragments","value":[{"kind":"identifier","text":"isAccidentDetectionSupportedByDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getEventSupportForDevice\/title","value":"getEventSupportForDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getEventSupportForDevice\/fragments","value":[{"kind":"identifier","text":"getEventSupportForDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1buildVersion\/title","value":"buildVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1buildVersion\/fragments","value":[{"kind":"identifier","text":"buildVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getSettings()\/title","value":"getSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1getSettings()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isSDKSetup\/title","value":"isSDKSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isSDKSetup\/fragments","value":[{"kind":"identifier","text":"isSDKSetup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/title","value":"isValidInputParameter:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isValidInputParameter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopSession()\/title","value":"stopSession"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopSession()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDriveWithPeriod1(completionHandler:)\/title","value":"startDriveWithPeriod1WithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDriveWithPeriod1(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod1WithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/title","value":"setupWith:delegate:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDelegate(_:)\/title","value":"setDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDelegate(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopManualDrive(completionHandler:)\/title","value":"stopManualDriveWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1stopManualDrive(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopManualDriveWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1wipeOut(completion:)\/title","value":"wipeOutWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1wipeOut(completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"wipeOutWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/title","value":"startSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod2:completionHandler:)\/title","value":"startDriveWithPeriod2:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod2:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1uploadAllDebugDataAndLogs()\/title","value":"uploadAllDebugDataAndLogs"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1uploadAllDebugDataAndLogs()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"uploadAllDebugDataAndLogs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}