{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticVehicleTaggingError) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/10Foundation14LocalizedErrorP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/s5ErrorP","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY","doc:\/\/com.fairmatic.Fairmatic\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error returned as code to NSError from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"},{"type":"text","text":" public APIs"},{"type":"text","text":" "},{"type":"text","text":"in case of failures."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"title":"FairmaticVehicleTaggingError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticVehicleTaggingError","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/associatedVehicleConflict","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/associatedVehiclesLimitExceeded","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/beaconScanTimeout","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleInfo","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/notSetup","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/vehicleNotAssociated"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/Error-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/LocalizedError-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/localizederror-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getNearbyBeacons(uuid:major:minor:completionHandler:)":{"role":"symbol","title":"getNearbyBeacons(uuid:major:minor:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNearbyBeacons"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scannedBeacons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScannedBeaconInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticScannedBeaconInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get all the beacons which are in the device’s range."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getnearbybeacons(uuid:major:minor:completionhandler:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/associatedVehiclesLimitExceeded":{"role":"symbol","title":"FairmaticVehicleTaggingError.associatedVehiclesLimitExceeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"associatedVehiclesLimitExceeded"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/associateVehicle(_:)"},{"type":"text","text":" called for more than two vehicles."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/associatedVehiclesLimitExceeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorAssociatedVehiclesLimitExceeded"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/associatedvehicleslimitexceeded"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo":{"role":"symbol","title":"VehicleInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError":{"role":"symbol","title":"FairmaticVehicleTaggingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"abstract":[{"type":"text","text":"Error returned as code to NSError from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"},{"type":"text","text":" public APIs"},{"type":"text","text":" "},{"type":"text","text":"in case of failures."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/invalidVehicleId":{"role":"symbol","title":"FairmaticVehicleTaggingError.invalidVehicleId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVehicleId"}],"abstract":[{"type":"text","text":"vehicleId passed to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/dissociateVehicle(_:)"},{"type":"text","text":" "},{"type":"text","text":"is invalid because of one of the following reasons:-"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleId"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/invalidvehicleid"},"doc://com.fairmatic.Fairmatic/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.fairmatic.Fairmatic\/10Foundation14LocalizedErrorP"},"doc://com.fairmatic.Fairmatic/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s5ErrorP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/vehicleNotAssociated":{"role":"symbol","title":"FairmaticVehicleTaggingError.vehicleNotAssociated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleNotAssociated"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/dissociateVehicle(_:)"},{"type":"text","text":" called for an unassociated vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/vehicleNotAssociated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorVehicleNotAssociated"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/vehiclenotassociated"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/associateVehicle(_:)":{"role":"symbol","title":"associateVehicle(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"associateVehicle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Associates the vehicle to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/associateVehicle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"associateVehicle:error:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/associatevehicle(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/beaconScanTimeout":{"role":"symbol","title":"FairmaticVehicleTaggingError.beaconScanTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"beaconScanTimeout"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getNearbyBeacons(uuid:major:minor:completionHandler:)"},{"type":"text","text":" failed to scan for beacons."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/beaconScanTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorBeaconScanTimeout"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/beaconscantimeout"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/dissociateVehicle(_:)":{"role":"symbol","title":"dissociateVehicle(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dissociateVehicle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Dissociates the vehicle from Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/dissociateVehicle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dissociateVehicle:error:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/dissociatevehicle(_:)"},"doc://com.fairmatic.Fairmatic/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s8SendableP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/error-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/associatedVehicleConflict":{"role":"symbol","title":"FairmaticVehicleTaggingError.associatedVehicleConflict","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"associatedVehicleConflict"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/associateVehicle(_:)"},{"type":"text","text":" called for vehicle whose "},{"type":"codeVoice","code":"vehicleId"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"bluetoothId"},{"type":"text","text":" or both conflicts with an already associated vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/associatedVehicleConflict","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorAssociatedVehicleConflict"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/associatedvehicleconflict"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/invalidVehicleInfo":{"role":"symbol","title":"FairmaticVehicleTaggingError.invalidVehicleInfo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVehicleInfo"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo"},{"type":"text","text":" object passed to ``FairmaticVehicleTagging\/associateVehicle(_:)`"},{"type":"text","text":" "},{"type":"text","text":"is invalid because of one of the following reasons:-"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/invalidvehicleinfo"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError/notSetup":{"role":"symbol","title":"FairmaticVehicleTaggingError.notSetup","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"abstract":[{"type":"text","text":"Fairmatic SDK is not setup. This error is also returned in case SDK setup"},{"type":"text","text":" "},{"type":"text","text":"has started but completion handler for setup is not called yet."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/notSetup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/notsetup"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticVehicleTaggingError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/associatedVehicleConflict","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/associatedVehiclesLimitExceeded","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/beaconScanTimeout","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/invalidVehicleInfo","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/notSetup","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/vehicleNotAssociated"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/title","value":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getNearbyBeacons(uuid:major:minor:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getNearbyBeaconsWithUuid:major:minor:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1associatedVehiclesLimitExceeded\/title","value":"FairmaticVehicleTaggingErrorAssociatedVehiclesLimitExceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1associatedVehiclesLimitExceeded\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorAssociatedVehiclesLimitExceeded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/title","value":"FairmaticVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/title","value":"FairmaticVehicleTaggingError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1invalidVehicleId\/title","value":"FairmaticVehicleTaggingErrorInvalidVehicleId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1invalidVehicleId\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1vehicleNotAssociated\/title","value":"FairmaticVehicleTaggingErrorVehicleNotAssociated"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1vehicleNotAssociated\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorVehicleNotAssociated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1associateVehicle(_:)\/title","value":"associateVehicle:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1associateVehicle(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"associateVehicle:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1beaconScanTimeout\/title","value":"FairmaticVehicleTaggingErrorBeaconScanTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1beaconScanTimeout\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorBeaconScanTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1dissociateVehicle(_:)\/title","value":"dissociateVehicle:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1dissociateVehicle(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"dissociateVehicle:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1associatedVehicleConflict\/title","value":"FairmaticVehicleTaggingErrorAssociatedVehicleConflict"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1associatedVehicleConflict\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorAssociatedVehicleConflict"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1invalidVehicleInfo\/title","value":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1invalidVehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorInvalidVehicleInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1notSetup\/title","value":"FairmaticVehicleTaggingErrorNotSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1notSetup\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}