{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"title":"FairmaticDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/businessHoursChanged(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processPotentialAccidentDetected(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processResume(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/settingsChanged(_:)"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processResume(ofDrive:)":{"role":"symbol","title":"processResume(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processResume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveResumeInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK resumes a"},{"type":"text","text":" "},{"type":"text","text":"drive after a gap."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processResume(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processResumeOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processresume(ofdrive:)"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processAccidentDetected(_:)":{"role":"symbol","title":"processAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is fired on the main thread when an accident is detected by"},{"type":"text","text":" "},{"type":"text","text":"the SDK during a drive. Any ongoing auto-detected\/manual drives will be stopped"},{"type":"text","text":" "},{"type":"text","text":"after this point."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAccidentDetected:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processStart(ofDrive:)":{"navigatorTitle":[{"kind":"identifier","text":"processStartOfDrive:"}],"role":"symbol","title":"processStart(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveStartInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a potential"},{"type":"text","text":" "},{"type":"text","text":"start of a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processstart(ofdrive:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processAnalysis(ofDrive:)":{"role":"symbol","title":"processAnalysis(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK finishes"},{"type":"text","text":" "},{"type":"text","text":"full analysis of all valid drives returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAnalysisOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processPotentialAccidentDetected(_:)":{"role":"symbol","title":"processPotentialAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processPotentialAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"[Disabled by default]"},{"type":"text","text":" "},{"type":"text","text":"This callback is fired on the main thread when a potential accident is detected by the SDK during a drive."},{"type":"text","text":" "},{"type":"text","text":"This is a preliminary callback of a potential collision. This collision is confirmed or invalidated by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processPotentialAccidentDetected(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processPotentialAccidentDetected:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processpotentialaccidentdetected(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/settingsChanged(_:)":{"role":"symbol","title":"settingsChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Settings","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSettings"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback gives information about errors in device or application settings that"},{"type":"text","text":" "},{"type":"text","text":"may be affecting Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/settingsChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"settingsChanged:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/settingschanged(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processEnd(ofDrive:)":{"role":"symbol","title":"processEnd(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EstimatedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEstimatedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate on the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a drive to have been completed."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processEndOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processend(ofdrive:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/businessHoursChanged(_:)":{"role":"symbol","title":"businessHoursChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"businessHoursChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ShiftDetail","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is fired when the SDK detects a change in the business hours set by the fleet manager and the current"},{"type":"text","text":" "},{"type":"text","text":"business hours applied on the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/businessHoursChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"businessHoursChanged:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/businesshourschanged(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/businessHoursChanged(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processPotentialAccidentDetected(_:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processResume(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/settingsChanged(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processResume(ofDrive:)\/title","value":"processResumeOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processResume(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processResumeOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/title","value":"processAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processStart(ofDrive:)\/title","value":"processStartOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processStart(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processStartOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/title","value":"processAnalysisOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAnalysisOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processPotentialAccidentDetected(_:)\/title","value":"processPotentialAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processPotentialAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processPotentialAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1settingsChanged(_:)\/title","value":"settingsChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1settingsChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"settingsChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/title","value":"processEndOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processEndOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1businessHoursChanged(_:)\/title","value":"businessHoursChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1businessHoursChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"businessHoursChanged:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}