{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticStarRating) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StarRating"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/starrating"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/starrating"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH","doc:\/\/com.fairmatic.Fairmatic\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fairmatic follows the star rating system, under which five star defined as the best rating with"},{"type":"text","text":" "},{"type":"text","text":"one being the worst."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StarRating"}],"title":"StarRating","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticStarRating","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"StarRating"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/NA","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/five","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/four","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/one","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/three","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/two"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/Equatable-Implementations","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/three":{"role":"symbol","title":"StarRating.three","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"three"}],"abstract":[{"type":"text","text":"Indicates an average rating."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/three","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingThree"}],"url":"\/documentation\/fairmaticsdk\/starrating\/three"},"doc://com.fairmatic.Fairmatic/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SY"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/starrating\/rawrepresentable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/five":{"role":"symbol","title":"StarRating.five","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"five"}],"abstract":[{"type":"text","text":"Indicates best rating."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/five","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingFive"}],"url":"\/documentation\/fairmaticsdk\/starrating\/five"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/NA":{"role":"symbol","title":"StarRating.NA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NA"}],"abstract":[{"type":"text","text":"Reported when rating is absent."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/NA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingNA"}],"url":"\/documentation\/fairmaticsdk\/starrating\/na"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/four":{"role":"symbol","title":"StarRating.four","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"four"}],"abstract":[{"type":"text","text":"Indicates good rating."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/four","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingFour"}],"url":"\/documentation\/fairmaticsdk\/starrating\/four"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/starrating\/init(rawvalue:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/one":{"role":"symbol","title":"StarRating.one","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"one"}],"abstract":[{"type":"text","text":"Indicates worst rating."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/one","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingOne"}],"url":"\/documentation\/fairmaticsdk\/starrating\/one"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/starrating\/equatable-implementations"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating":{"role":"symbol","title":"StarRating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StarRating"}],"abstract":[{"type":"text","text":"Fairmatic follows the star rating system, under which five star defined as the best rating with"},{"type":"text","text":" "},{"type":"text","text":"one being the worst."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StarRating"}],"url":"\/documentation\/fairmaticsdk\/starrating"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/StarRating/two":{"role":"symbol","title":"StarRating.two","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"two"}],"abstract":[{"type":"text","text":"Indicates bad rating."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/two","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticStarRatingTwo"}],"url":"\/documentation\/fairmaticsdk\/starrating\/two"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticStarRating"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRating"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticStarRating"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/NA","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/five","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/four","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/one","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/three","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/StarRating\/two"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticStarRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1three\/title","value":"FairmaticStarRatingThree"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1three\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingThree"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1five\/title","value":"FairmaticStarRatingFive"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1five\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingFive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1NA\/title","value":"FairmaticStarRatingNA"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1NA\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingNA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1four\/title","value":"FairmaticStarRatingFour"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1four\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingFour"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1one\/title","value":"FairmaticStarRatingOne"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1one\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingOne"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating\/title","value":"FairmaticStarRating"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRating"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1two\/title","value":"FairmaticStarRatingTwo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1StarRating~1two\/fragments","value":[{"kind":"identifier","text":"FairmaticStarRatingTwo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}