{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extrapolationDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ExtrapolationDetails","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticExtrapolationDetails","text":"ExtrapolationDetails"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/extrapolationdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/extrapolationdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/extrapolationDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The extrapolated details for a drive."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is not "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" then it will be set to nil."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extrapolationDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExtrapolationDetails","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticExtrapolationDetails"},{"kind":"text","text":"?"}],"title":"extrapolationDetails","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveInfo(py)extrapolationDetails","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"extrapolationDetails"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleType":{"role":"symbol","title":"VehicleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleType"}],"abstract":[{"type":"text","text":"Type of vehicle used in the drive recorded by the Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"A default vehicle type can be set using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The detected type is returned to the application in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType"},{"type":"text","text":" "},{"type":"text","text":"field of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleType"}],"url":"\/documentation\/fairmaticsdk\/vehicletype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveType/drive":{"role":"symbol","title":"DriveType.drive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"drive"}],"abstract":[{"type":"text","text":"This trip was taken in a valid "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/drive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/drive"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/extrapolationDetails":{"role":"symbol","title":"extrapolationDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extrapolationDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExtrapolationDetails","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticExtrapolationDetails"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The extrapolated details for a drive."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is not "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" then it will be set to nil."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/extrapolationDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"extrapolationDetails"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/extrapolationdetails"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ExtrapolationDetails":{"role":"symbol","title":"ExtrapolationDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExtrapolationDetails"}],"abstract":[{"type":"text","text":"Wrapper for extrapolated details for a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ExtrapolationDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExtrapolationDetails"}],"url":"\/documentation\/fairmaticsdk\/extrapolationdetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"extrapolationDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"extrapolationDetails"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ExtrapolationDetails","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticExtrapolationDetails","text":"FairmaticExtrapolationDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"extrapolationDetails"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleType\/title","value":"FairmaticVehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleType\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1drive\/title","value":"FairmaticDriveTypeDrive"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1drive\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1extrapolationDetails\/title","value":"extrapolationDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1extrapolationDetails\/fragments","value":[{"kind":"identifier","text":"extrapolationDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ExtrapolationDetails\/title","value":"FairmaticExtrapolationDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ExtrapolationDetails\/fragments","value":[{"kind":"identifier","text":"FairmaticExtrapolationDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}