{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode","text":"UserMode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Driver\/Passenger detection is disabled by default. Talk to your"},{"type":"text","text":" "},{"type":"text","text":"contact in "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" to enable this feature. Only present when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" and the SDK was able to determine with confidence"},{"type":"text","text":" "},{"type":"text","text":"whether the user was a driver or a passenger."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the SDK was not able to determine the user mode, this field is"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/UserMode\/unavailable"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/usermode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveinfo\/usermode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/userMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether the user was a driver or a passenger."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode"}],"title":"userMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveInfo(py)userMode","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"userMode"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/userMode":{"role":"symbol","title":"userMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode"}],"abstract":[{"type":"text","text":"Whether the user was a driver or a passenger."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/userMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userMode"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/usermode"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleType":{"role":"symbol","title":"VehicleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleType"}],"abstract":[{"type":"text","text":"Type of vehicle used in the drive recorded by the Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"A default vehicle type can be set using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriverAttributes"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The detected type is returned to the application in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType"},{"type":"text","text":" "},{"type":"text","text":"field of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleType"}],"url":"\/documentation\/fairmaticsdk\/vehicletype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/UserMode":{"role":"symbol","title":"UserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMode"}],"abstract":[{"type":"text","text":"The value return from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/userMode"},{"type":"text","text":". Indicates whether user"},{"type":"text","text":" "},{"type":"text","text":"was a driver or passenger."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/UserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMode"}],"url":"\/documentation\/fairmaticsdk\/usermode"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/UserMode/unavailable":{"role":"symbol","title":"UserMode.unavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"abstract":[{"type":"text","text":"Indicates that either "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is not"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" was not able to determine user mode."},{"type":"text","text":" "},{"type":"text","text":"All values in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" will be set."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/UserMode\/unavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}],"url":"\/documentation\/fairmaticsdk\/usermode\/unavailable"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveType/drive":{"role":"symbol","title":"DriveType.drive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"drive"}],"abstract":[{"type":"text","text":"This trip was taken in a valid "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/drive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/drive"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"userMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode","text":"FairmaticUserMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/title","value":"userMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/fragments","value":[{"kind":"identifier","text":"userMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleType\/title","value":"FairmaticVehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleType\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1UserMode\/title","value":"FairmaticUserMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1UserMode\/fragments","value":[{"kind":"identifier","text":"FairmaticUserMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1UserMode~1unavailable\/title","value":"FairmaticUserModeUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1UserMode~1unavailable\/fragments","value":[{"kind":"identifier","text":"FairmaticUserModeUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1drive\/title","value":"FairmaticDriveTypeDrive"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1drive\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}