{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/notsetup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/notsetup"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/notSetup","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fairmatic SDK is not setup. This error is also returned in case SDK setup has started but completion handler for setup is not called yet."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"title":"FairmaticVehicleTaggingError.notSetup","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticVehicleTaggingError@FairmaticVehicleTaggingErrorNotSetup","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError"]]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)"]}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticVehicleTaggingError":{"role":"symbol","title":"FairmaticVehicleTaggingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"abstract":[{"type":"text","text":"Error returned as code to "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"},{"type":"text","text":" public APIs in case of failures."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticVehicleTaggingError/notSetup":{"role":"symbol","title":"FairmaticVehicleTaggingError.notSetup","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSetup"}],"abstract":[{"type":"text","text":"Fairmatic SDK is not setup. This error is also returned in case SDK setup has started but completion handler for setup is not called yet."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError\/notSetup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror\/notsetup"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setup(with:delegate:completionHandler:)":{"role":"symbol","title":"setup(with:delegate:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticDelegate","preciseIdentifier":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Initializes the Fairmatic SDK to automatically detect driving and collect"},{"type":"text","text":" "},{"type":"text","text":"data. Client code should call this method before anything else in the Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setup(with:delegate:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticVehicleTaggingErrorNotSetup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setup(with:delegate:completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/title","value":"FairmaticVehicleTaggingError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1notSetup\/title","value":"FairmaticVehicleTaggingErrorNotSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError~1notSetup\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingErrorNotSetup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/title","value":"setupWith:delegate:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setup(with:delegate:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWith:delegate:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}