{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventOccurrence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType","text":"EventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"occurrence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"driveId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"As returned at the end of drive in "},{"type":"codeVoice","code":"DriveInfo"},{"type":"text","text":" which"},{"type":"text","text":" "},{"type":"text","text":"this event is part of"}]}]},{"name":"eventTimestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"As returned in "},{"type":"codeVoice","code":"Event.startTime"}]}]},{"name":"eventType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"As returned in "},{"type":"codeVoice","code":"Event.eventType"}]}]},{"name":"occurrence","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the event occurred or not"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticfeedback\/addeventoccurrence(driveid:eventtimestamp:eventtype:occurrence:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticfeedback\/addeventoccurrence(driveid:eventtimestamp:eventtype:occurrence:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Help "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" improve by providing information about whether an"},{"type":"text","text":" "},{"type":"text","text":"event detected by the SDK occurred or not."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventOccurrence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"occurrence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticFeedback(cm)addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)":{"role":"symbol","title":"addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventOccurrence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"occurrence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Help "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" improve by providing information about whether an"},{"type":"text","text":" "},{"type":"text","text":"event detected by the SDK occurred or not."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback\/addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback\/addeventoccurrence(driveid:eventtimestamp:eventtype:occurrence:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticFeedback":{"role":"symbol","title":"FairmaticFeedback","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticFeedback"}],"abstract":[{"type":"text","text":"Class for providing feedback back to "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticFeedback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticFeedback"}],"url":"\/documentation\/fairmaticsdk\/fairmaticfeedback"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventType":{"role":"symbol","title":"EventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventType"}],"abstract":[{"type":"text","text":"The event type as specified in "},{"type":"codeVoice","code":"Event.eventType"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventType"}],"url":"\/documentation\/fairmaticsdk\/eventtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addEventOccurrenceWithDriveId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"driveId"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"eventTimestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType","text":"FairmaticventType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"eventType"},{"kind":"text","text":" "},{"kind":"identifier","text":"occurrence:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"occurrence"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)\/title","value":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback~1addEventOccurrence(driveId:eventTimestamp:eventType:occurrence:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addEventOccurrenceWithDriveId:eventTimestamp:eventType:occurrence:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback\/title","value":"FairmaticFeedback"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticFeedback\/fragments","value":[{"kind":"identifier","text":"FairmaticFeedback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventType\/title","value":"FairmaticventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventType\/fragments","value":[{"kind":"identifier","text":"FairmaticventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}