{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shiftdetail\/timezone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shiftdetail\/timezone"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail\/timezone","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Timezone object which specifies the timezone of the shift."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"}],"title":"timezone","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail(py)timezone","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"timezone"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail":{"role":"symbol","title":"ShiftDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftDetail"}],"abstract":[{"type":"text","text":"Represents a shift comprising of shift intervals over the week."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftDetail"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail/timezone":{"role":"symbol","title":"timezone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"}],"abstract":[{"type":"text","text":"A Timezone object which specifies the timezone of the shift."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail\/timezone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timezone"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail\/timezone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timezone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"timezone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSTimeZone","preciseIdentifier":"c:objc(cs)NSTimeZone"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timezone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/title","value":"FairmaticShiftDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftDetail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail~1timezone\/title","value":"timezone"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail~1timezone\/fragments","value":[{"kind":"identifier","text":"timezone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}