{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadside"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/directionofimpact\/broadside"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/directionofimpact\/broadside"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DirectionOfImpact\/broadside","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates a broadside direction of impact"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadside"}],"title":"DirectionOfImpact.broadside","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact@FairmaticDirectionOfImpactBroadside","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DirectionOfImpact"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DirectionOfImpact":{"role":"symbol","title":"DirectionOfImpact","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"abstract":[{"type":"text","text":"Direction of impact detected by SDK at the time of the accident"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DirectionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DirectionOfImpact/broadside":{"role":"symbol","title":"DirectionOfImpact.broadside","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadside"}],"abstract":[{"type":"text","text":"Indicates a broadside direction of impact"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DirectionOfImpact\/broadside","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/broadside"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDirectionOfImpactBroadside"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DirectionOfImpact\/title","value":"FairmaticDirectionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DirectionOfImpact\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DirectionOfImpact~1broadside\/title","value":"FairmaticDirectionOfImpactBroadside"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DirectionOfImpact~1broadside\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}