{"variants":[{"paths":["\/documentation\/fairmaticsdk\/turndirection\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"FairmaticSDK"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/turnDirection":{"role":"symbol","title":"turnDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TurnDirection","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticTurnDirection"}],"abstract":[{"type":"text","text":"Denotes the turn direction of a hard turn whether a left or right turn."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnDirection"}],"url":"\/documentation\/fairmaticsdk\/event\/turndirection"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType/hardTurn":{"role":"symbol","title":"EventType.hardTurn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardTurn"}],"abstract":[{"type":"text","text":"This denotes a hard turn as detected by Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/hardTurn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeHardTurn"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/hardturn"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/turndirection\/!=(_:_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection":{"role":"symbol","title":"TurnDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TurnDirection"}],"abstract":[{"type":"text","text":"This is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection"},{"type":"text","text":", it represents the turn direction for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/hardTurn"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TurnDirection"}],"url":"\/documentation\/fairmaticsdk\/turndirection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1turnDirection\/title","value":"turnDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1turnDirection\/fragments","value":[{"kind":"identifier","text":"turnDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1hardTurn\/title","value":"FairmaticventTypeHardTurn"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1hardTurn\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeHardTurn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection\/title","value":"FairmaticTurnDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection\/fragments","value":[{"kind":"identifier","text":"FairmaticTurnDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}