{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentconfidence\/low"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentconfidence\/low"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/low","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Accident was detected, but with a low confidence. The application might ask"},{"type":"text","text":" "},{"type":"text","text":"the user for feedback before notifying any emergency services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"title":"AccidentConfidence.low","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence@FairmaticAccidentConfidenceLow","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence/low":{"role":"symbol","title":"AccidentConfidence.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[{"type":"text","text":"Accident was detected, but with a low confidence. The application might ask"},{"type":"text","text":" "},{"type":"text","text":"the user for feedback before notifying any emergency services."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence\/low"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticAccidentConfidenceLow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1low\/title","value":"FairmaticAccidentConfidenceLow"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence~1low\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidenceLow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}