{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shiftName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shiftId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shiftIntervals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval","text":"ShiftInterval"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shiftdetail\/init(shiftname:shiftid:timezone:shiftintervals:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shiftdetail\/init(shiftname:shiftid:timezone:shiftintervals:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail\/init(shiftName:shiftId:timezone:shiftIntervals:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize the shift details object with shiftName, shiftId, timezone and shiftIntervals."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shiftName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shiftId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shiftIntervals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ShiftInterval","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval"},{"kind":"text","text":"])"}],"title":"init(shiftName:shiftId:timezone:shiftIntervals:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail(im)initWithShiftName:shiftId:timezone:shiftIntervals:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithShiftName:shiftId:timezone:shiftIntervals:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval":{"role":"symbol","title":"ShiftInterval","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftInterval"}],"abstract":[{"type":"text","text":"Wrapper for a single business hour interval."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftInterval"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail/init(shiftName:shiftId:timezone:shiftIntervals:)":{"role":"symbol","title":"init(shiftName:shiftId:timezone:shiftIntervals:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shiftName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shiftId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shiftIntervals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ShiftInterval","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Initialize the shift details object with shiftName, shiftId, timezone and shiftIntervals."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail\/init(shiftName:shiftId:timezone:shiftIntervals:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithShiftName:shiftId:timezone:shiftIntervals:"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail\/init(shiftname:shiftid:timezone:shiftintervals:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail":{"role":"symbol","title":"ShiftDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftDetail"}],"abstract":[{"type":"text","text":"Represents a shift comprising of shift intervals over the week."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftDetail"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithShiftName:shiftId:timezone:shiftIntervals:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShiftName:shiftId:timezone:shiftIntervals:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithShiftName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"shiftName"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"shiftId"},{"kind":"text","text":" "},{"kind":"identifier","text":"timezone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeZone","preciseIdentifier":"c:objc(cs)NSTimeZone"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"timezone"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftIntervals:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<FairmaticShiftInterval *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"shiftIntervals"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/title","value":"FairmaticShiftInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail~1init(shiftName:shiftId:timezone:shiftIntervals:)\/title","value":"initWithShiftName:shiftId:timezone:shiftIntervals:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail~1init(shiftName:shiftId:timezone:shiftIntervals:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShiftName:shiftId:timezone:shiftIntervals:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/title","value":"FairmaticShiftDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftDetail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}