{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftIntervals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval","text":"ShiftInterval"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/shiftdetail\/shiftintervals"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/shiftdetail\/shiftintervals"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail\/shiftIntervals","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shift intervals specify the intervals when the SDK should be active."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftIntervals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ShiftInterval","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval"},{"kind":"text","text":"]"}],"title":"shiftIntervals","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftDetail(py)shiftIntervals","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"shiftIntervals"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftInterval":{"role":"symbol","title":"ShiftInterval","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftInterval"}],"abstract":[{"type":"text","text":"Wrapper for a single business hour interval."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftInterval"}],"url":"\/documentation\/fairmaticsdk\/shiftinterval"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail/shiftIntervals":{"role":"symbol","title":"shiftIntervals","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shiftIntervals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ShiftInterval","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticShiftInterval"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Shift intervals specify the intervals when the SDK should be active."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail\/shiftIntervals","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shiftIntervals"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail\/shiftintervals"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ShiftDetail":{"role":"symbol","title":"ShiftDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShiftDetail"}],"abstract":[{"type":"text","text":"Represents a shift comprising of shift intervals over the week."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ShiftDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShiftDetail"}],"url":"\/documentation\/fairmaticsdk\/shiftdetail"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shiftIntervals"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shiftIntervals"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<FairmaticShiftInterval *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shiftIntervals"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/title","value":"FairmaticShiftInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftInterval\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail~1shiftIntervals\/title","value":"shiftIntervals"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail~1shiftIntervals\/fragments","value":[{"kind":"identifier","text":"shiftIntervals"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/title","value":"FairmaticShiftDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ShiftDetail\/fragments","value":[{"kind":"identifier","text":"FairmaticShiftDetail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}