{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo","text":"DriveStartInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"startInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Info about drive start. Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo"},{"type":"text","text":" for further details."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processstart(ofdrive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticdelegate\/processstart(ofdrive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a potential"},{"type":"text","text":" "},{"type":"text","text":"start of a drive."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"processStartOfDrive:"}],"role":"symbol","title":"processStart(ofDrive:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveStartInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(pl)FairmaticDelegate(im)processStartOfDrive:","modules":[{"name":"FairmaticSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processStart(ofDrive:)":{"role":"symbol","title":"processStart(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveStartInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a potential"},{"type":"text","text":" "},{"type":"text","text":"start of a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processStart(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processStartOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processstart(ofdrive:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate":{"role":"symbol","title":"FairmaticDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDelegate"}],"abstract":[{"type":"text","text":"Delegate for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDelegate"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo":{"role":"symbol","title":"DriveStartInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveStartInfo"}],"abstract":[{"type":"text","text":"Information about start of a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveStartInfo"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"processStartOfDrive:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processStartOfDrive:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"processStartOfDrive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo","text":"FairmaticDriveStartInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"startInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processStart(ofDrive:)\/title","value":"processStartOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processStart(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processStartOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/title","value":"FairmaticDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate\/fragments","value":[{"kind":"identifier","text":"FairmaticDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo\/title","value":"FairmaticDriveStartInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveStartInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}