{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticActiveDriveInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveDriveInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/activedriveinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/activedriveinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Information about the active drive if any."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveDriveInfo"}],"title":"ActiveDriveInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticActiveDriveInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ActiveDriveInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/currentSpeed","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/distance","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/driveId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/insurancePeriod","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/sessionId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/startTimestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/trackingId"]}],"references":{"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/startSession(_:)":{"role":"symbol","title":"startSession(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start a session in the SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSession:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startsession(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/trackingId":{"role":"symbol","title":"trackingId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Tracking id is specified by the enclosing application when it"},{"type":"text","text":" "},{"type":"text","text":"wants to start a drive manually by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(_:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/trackingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingId"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/trackingid"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/driveId":{"role":"symbol","title":"driveId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The unique Id for this drive"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/driveId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveId"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/driveid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic/startManualDrive(_:completionHandler:)":{"role":"symbol","title":"startManualDrive(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDrive:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(_:completionhandler:)"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/startTimestamp":{"role":"symbol","title":"startTimestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The start timestamp of trip in milliseconds since epoch."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/startTimestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTimestamp"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/starttimestamp"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance covered so far in this trip in meters."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/distance"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/currentSpeed":{"role":"symbol","title":"currentSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The current speed of vehicle in metres\/second."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/currentSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentSpeed"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/currentspeed"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/insurancePeriod":{"role":"symbol","title":"insurancePeriod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insurancePeriod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsurancePeriod","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod"}],"abstract":[{"type":"text","text":"The insurance period for this drive"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/insurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/insuranceperiod"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo":{"role":"symbol","title":"ActiveDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveDriveInfo"}],"abstract":[{"type":"text","text":"Information about the active drive if any."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/ActiveDriveInfo/sessionId":{"role":"symbol","title":"sessionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Session id is specified by the enclosing application when it wants to"},{"type":"text","text":" "},{"type":"text","text":"record a session using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/sessionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionId"}],"url":"\/documentation\/fairmaticsdk\/activedriveinfo\/sessionid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticActiveDriveInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticActiveDriveInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticActiveDriveInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/currentSpeed","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/distance","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/driveId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/insurancePeriod","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/sessionId","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/startTimestamp","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/ActiveDriveInfo\/trackingId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticActiveDriveInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/title","value":"startSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1trackingId\/title","value":"trackingId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1trackingId\/fragments","value":[{"kind":"identifier","text":"trackingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1driveId\/title","value":"driveId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1driveId\/fragments","value":[{"kind":"identifier","text":"driveId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(_:completionHandler:)\/title","value":"startManualDrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1startTimestamp\/title","value":"startTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1startTimestamp\/fragments","value":[{"kind":"identifier","text":"startTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1currentSpeed\/title","value":"currentSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1currentSpeed\/fragments","value":[{"kind":"identifier","text":"currentSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1insurancePeriod\/title","value":"insurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1insurancePeriod\/fragments","value":[{"kind":"identifier","text":"insurancePeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo\/title","value":"FairmaticActiveDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticActiveDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1sessionId\/title","value":"sessionId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1ActiveDriveInfo~1sessionId\/fragments","value":[{"kind":"identifier","text":"sessionId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}