{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticEventRatings) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventRatings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/eventratings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/eventratings"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject","doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP","doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.Fairmatic\/SQ","doc:\/\/com.fairmatic.Fairmatic\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents ratings associated with the various event types for a trip. Higher rating for an event"},{"type":"text","text":" "},{"type":"text","text":"represents safe driving behaviour with respect to that event. For cases where rating is absent,"},{"type":"text","text":" "},{"type":"text","text":"``StarRating\/NA` is reported."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventRatings"}],"title":"EventRatings","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticEventRatings","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"EventRatings"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/aggressiveAccelerationRating","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/hardBrakeRating","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/hardTurnRating","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/phoneHandlingRating","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/speedingRating"]}],"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings/hardTurnRating":{"role":"symbol","title":"hardTurnRating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardTurnRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"abstract":[{"type":"text","text":"Represents rating associated with hard turning while driving."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/hardTurnRating","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventratings\/hardturnrating"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings/hardBrakeRating":{"role":"symbol","title":"hardBrakeRating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardBrakeRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"abstract":[{"type":"text","text":"Represents rating associated with hard braking while driving."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/hardBrakeRating","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventratings\/hardbrakerating"},"doc://com.fairmatic.Fairmatic/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SH"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings/speedingRating":{"role":"symbol","title":"speedingRating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedingRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"abstract":[{"type":"text","text":"Represents rating associated with speeding while driving."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/speedingRating","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventratings\/speedingrating"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings":{"role":"symbol","title":"EventRatings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventRatings"}],"abstract":[{"type":"text","text":"Represents ratings associated with the various event types for a trip. Higher rating for an event"},{"type":"text","text":" "},{"type":"text","text":"represents safe driving behaviour with respect to that event. For cases where rating is absent,"},{"type":"text","text":" "},{"type":"text","text":"``StarRating\/NA` is reported."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventRatings"}],"url":"\/documentation\/fairmaticsdk\/eventratings"},"doc://com.fairmatic.Fairmatic/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(pl)NSObject"},"doc://com.fairmatic.Fairmatic/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"},"doc://com.fairmatic.Fairmatic/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings/aggressiveAccelerationRating":{"role":"symbol","title":"aggressiveAccelerationRating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aggressiveAccelerationRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"abstract":[{"type":"text","text":"Represents rating associated with aggressively accelerating while driving."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/aggressiveAccelerationRating","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventratings\/aggressiveaccelerationrating"},"doc://com.fairmatic.Fairmatic/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.Fairmatic\/SQ"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventRatings/phoneHandlingRating":{"role":"symbol","title":"phoneHandlingRating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneHandlingRating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StarRating","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticStarRating"}],"abstract":[{"type":"text","text":"Represents rating associated with phone handling behavior while driving."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventRatings\/phoneHandlingRating","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/eventratings\/phonehandlingrating"},"doc://com.fairmatic.Fairmatic/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s7CVarArgP"},"doc://com.fairmatic.Fairmatic/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.Fairmatic\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticEventRatings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticEventRatings"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticEventRatings"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.Fairmatic\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticEventRatings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventRatings\/title","value":"FairmaticEventRatings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventRatings\/fragments","value":[{"kind":"identifier","text":"FairmaticEventRatings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}