{"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticerror\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/hashValue"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"FairmaticSDK"}],"role":"collectionGroup","title":"RawRepresentable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError":{"role":"symbol","title":"FairmaticError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticError"}],"abstract":[{"type":"text","text":"Error returned as code of "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" public APIs in case of"},{"type":"text","text":" "},{"type":"text","text":"failures."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticerror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticError/hashValue":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticError\/hashValue","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticerror\/hashvalue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError\/title","value":"FairmaticError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticError\/fragments","value":[{"kind":"identifier","text":"FairmaticError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}