{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"AccidentConfidence"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/confidence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/confidence"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/confidence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The confidence of detected accident."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"}],"title":"confidence","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo(py)confidence","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"confidence"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo":{"role":"symbol","title":"AccidentInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to an accident detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentInfo"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo/confidence":{"role":"symbol","title":"confidence","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"}],"abstract":[{"type":"text","text":"The confidence of detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/confidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confidence"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo\/confidence"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"confidence"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confidence"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"FairmaticAccidentConfidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/title","value":"FairmaticAccidentInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1confidence\/title","value":"confidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1confidence\/fragments","value":[{"kind":"identifier","text":"confidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}