{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/timestamp","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The timestamp of the accident in milliseconds since epoch."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"title":"timestamp","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo(py)timestamp","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"timestamp"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo":{"role":"symbol","title":"AccidentInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to an accident detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentInfo"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo/timestamp":{"role":"symbol","title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The timestamp of the accident in milliseconds since epoch."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/timestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo\/timestamp"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timestamp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/title","value":"FairmaticAccidentInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}