{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode","text":"DriveDetectionMode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Applications which do not want the SDK to continuously track drives in"},{"type":"text","text":" "},{"type":"text","text":"background should set this value to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoOFF"},{"type":"text","text":". With this, the application needs to call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" method to record drives. In case the application wants to enable auto drive detection only for a fixed duration (like when the driver is on-duty), use method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)"},{"type":"text","text":" "},{"type":"text","text":"to change the mode to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON"},{"type":"text","text":" for that period and set it back to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoOFF"},{"type":"text","text":" (once the driver goes off-duty)."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/configuration\/drivedetectionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/configuration\/drivedetectionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use this mode to control the SDK’s behaviour for detecting drives"},{"type":"text","text":" "},{"type":"text","text":"automatically. This mode can be changed at a later point using"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)"},{"type":"text","text":" method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"title":"driveDetectionMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration(py)driveDetectionMode","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"driveDetectionMode"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/autoOFF":{"role":"symbol","title":"DriveDetectionMode.autoOFF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoOFF"}],"abstract":[{"type":"text","text":"In this mode auto drive-detection is disabled. All other APIs on "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" "},{"type":"text","text":"can be invoked independent of this mode. For recording trips in this mode, the"},{"type":"text","text":" "},{"type":"text","text":"application has to explicitly invoke the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoOFF","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoOFF"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/autooff"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode":{"role":"symbol","title":"DriveDetectionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveDetectionMode"}],"abstract":[{"type":"text","text":"Dictates the functioning of Fairmatic’s drive detection."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setDriveDetectionMode(_:completionHandler:)":{"role":"symbol","title":"setDriveDetectionMode(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDriveDetectionMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Change the drive detection mode to control how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details. This will override the mode sent"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setdrivedetectionmode(_:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/fairmaticsdk\/configuration"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/driveDetectionMode":{"role":"symbol","title":"driveDetectionMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"abstract":[{"type":"text","text":"Use this mode to control the SDK’s behaviour for detecting drives"},{"type":"text","text":" "},{"type":"text","text":"automatically. This mode can be changed at a later point using"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/configuration\/drivedetectionmode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/autoON":{"role":"symbol","title":"DriveDetectionMode.autoON","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoON"}],"abstract":[{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK will automatically track drives in background in"},{"type":"text","text":" "},{"type":"text","text":"this mode once the SDK is setup. At the same time, the application can invoke"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" to explicitly start recording a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoON"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/autoon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"driveDetectionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"driveDetectionMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode","text":"FairmaticDriveDetectionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveDetectionMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoOFF\/title","value":"FairmaticDriveDetectionModeAutoOFF"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoOFF\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoOFF"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/title","value":"FairmaticDriveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/title","value":"setDriveDetectionMode:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driveDetectionMode\/title","value":"driveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driveDetectionMode\/fragments","value":[{"kind":"identifier","text":"driveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoON\/title","value":"FairmaticDriveDetectionModeAutoON"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoON\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoON"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}