{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sdkKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes","text":"DriverAttributes"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"sdkKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK key to be used to initialize the SDK. Refer "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/sdkKey"},{"type":"text","text":" for more details"}]}]},{"name":"driverId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The driver identifer. Refer "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverId"},{"type":"text","text":" for more details."}]}]},{"name":"driverAttributes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The additional attributes for the driver."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/configuration\/init(sdkkey:driverid:driverattributes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/configuration\/init(sdkkey:driverid:driverattributes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/init(sdkKey:driverId:driverAttributes:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a Fairmatic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sdkKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriverAttributes","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes"},{"kind":"text","text":")"}],"title":"init(sdkKey:driverId:driverAttributes:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration(im)initWithSdkKey:driverId:driverAttributes:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSdkKey:driverId:driverAttributes:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/init(sdkKey:driverId:driverAttributes:)":{"role":"symbol","title":"init(sdkKey:driverId:driverAttributes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sdkKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriverAttributes","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a Fairmatic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/init(sdkKey:driverId:driverAttributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSdkKey:driverId:driverAttributes:"}],"url":"\/documentation\/fairmaticsdk\/configuration\/init(sdkkey:driverid:driverattributes:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/driverId":{"role":"symbol","title":"driverId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Unique ID for the current user. This can be any ID used by your app to"},{"type":"text","text":" "},{"type":"text","text":"identify its users."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)"},{"type":"text","text":" to verify that userId is valid."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverId"}],"url":"\/documentation\/fairmaticsdk\/configuration\/driverid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriverAttributes":{"role":"symbol","title":"DriverAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributes"}],"abstract":[{"type":"text","text":"Additional attributes of a "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" driver."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriverAttributes"}],"url":"\/documentation\/fairmaticsdk\/driverattributes"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/fairmaticsdk\/configuration"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/isValidInputParameter(_:)":{"role":"symbol","title":"isValidInputParameter(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidInputParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this method to check whether the parameter string passed"},{"type":"text","text":" "},{"type":"text","text":"to the SDK is valid."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isValidInputParameter:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/isvalidinputparameter(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/sdkKey":{"role":"symbol","title":"sdkKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Your SDK key."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/sdkKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sdkKey"}],"url":"\/documentation\/fairmaticsdk\/configuration\/sdkkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSdkKey:driverId:driverAttributes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSdkKey:driverId:driverAttributes:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSdkKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sdkKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"driverId"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes","text":"FairmaticDriverAttributes"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"driverAttributes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1init(sdkKey:driverId:driverAttributes:)\/title","value":"initWithSdkKey:driverId:driverAttributes:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1init(sdkKey:driverId:driverAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSdkKey:driverId:driverAttributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driverId\/title","value":"driverId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driverId\/fragments","value":[{"kind":"identifier","text":"driverId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes\/title","value":"FairmaticDriverAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/title","value":"isValidInputParameter:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isValidInputParameter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1sdkKey\/title","value":"sdkKey"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1sdkKey\/fragments","value":[{"kind":"identifier","text":"sdkKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}