{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pausedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticPauseReason","text":"FairmaticPauseReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/pausedreason\/pausedreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/pausedreason\/pausedreason"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason\/pausedReason","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pausedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticPauseReason","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticPauseReason"}],"title":"pausedReason","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticPausedReason(py)pausedReason","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"pausedReason"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/PausedReason/pausedReason":{"role":"symbol","title":"pausedReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pausedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FairmaticPauseReason","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticPauseReason"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason\/pausedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pausedReason"}],"url":"\/documentation\/fairmaticsdk\/pausedreason\/pausedreason"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticPauseReason":{"role":"symbol","title":"FairmaticPauseReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticPauseReason"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticPauseReason"}],"url":"\/documentation\/fairmaticsdk\/fairmaticpausereason"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/PausedReason":{"role":"symbol","title":"PausedReason","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PausedReason"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/PausedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PausedReason"}],"url":"\/documentation\/fairmaticsdk\/pausedreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pausedReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pausedReason"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticPauseReason","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticPauseReason","text":"FairmaticPauseReason"},{"kind":"text","text":" "},{"kind":"identifier","text":"pausedReason"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1PausedReason~1pausedReason\/title","value":"pausedReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1PausedReason~1pausedReason\/fragments","value":[{"kind":"identifier","text":"pausedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason\/title","value":"FairmaticPauseReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticPauseReason\/fragments","value":[{"kind":"identifier","text":"FairmaticPauseReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1PausedReason\/title","value":"FairmaticPausedReason"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1PausedReason\/fragments","value":[{"kind":"identifier","text":"FairmaticPausedReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}