{"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivetype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"FairmaticSDK"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType":{"role":"symbol","title":"DriveType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveType"}],"abstract":[{"type":"text","text":"The type of the drive returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveType"}],"url":"\/documentation\/fairmaticsdk\/drivetype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/drivetype\/!=(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType\/title","value":"FairmaticDriveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}