{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivetype\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/drivetype\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/invalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sometimes, the SDK detects that a trip is invalid after it has been started."},{"type":"text","text":" "},{"type":"text","text":"In these cases, the values for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed"},{"type":"text","text":" "},{"type":"text","text":"will have invalid values."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"title":"DriveType.invalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticDriveType@FairmaticDriveTypeInvalid","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/LocationPoint":{"role":"symbol","title":"LocationPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationPoint"}],"abstract":[{"type":"text","text":"Represents a geographical coordinate."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationPoint"}],"url":"\/documentation\/fairmaticsdk\/locationpoint"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType":{"role":"symbol","title":"DriveType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveType"}],"abstract":[{"type":"text","text":"The type of the drive returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveType"}],"url":"\/documentation\/fairmaticsdk\/drivetype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event":{"role":"symbol","title":"Event","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"abstract":[{"type":"text","text":"Represents a driving behavior event like phone use, aggressive acceleration etc."},{"type":"text","text":" "},{"type":"text","text":"It is part of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" object of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"url":"\/documentation\/fairmaticsdk\/event"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/averageSpeed":{"role":"symbol","title":"averageSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The average speed of trip in metres\/second"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"averageSpeed"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/averagespeed"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location"},{"type":"text","text":" "},{"type":"text","text":"and last to trip end location."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waypoints"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/waypoints"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/maxSpeed":{"role":"symbol","title":"maxSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The maximum speed of trip in metres\/second"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxSpeed"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/maxspeed"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/events":{"role":"symbol","title":"events","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"events"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEvent"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event"},{"type":"text","text":" objects for this trip in increasing order of timestamp."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"events"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/events"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType/invalid":{"role":"symbol","title":"DriveType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Sometimes, the SDK detects that a trip is invalid after it has been started."},{"type":"text","text":" "},{"type":"text","text":"In these cases, the values for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed"},{"type":"text","text":" "},{"type":"text","text":"will have invalid values."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/invalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveTypeInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/title","value":"FairmaticLocationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/fragments","value":[{"kind":"identifier","text":"FairmaticLocationPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType\/title","value":"FairmaticDriveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event\/title","value":"FairmaticEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event\/fragments","value":[{"kind":"identifier","text":"FairmaticEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1averageSpeed\/title","value":"averageSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1averageSpeed\/fragments","value":[{"kind":"identifier","text":"averageSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1waypoints\/title","value":"waypoints"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1waypoints\/fragments","value":[{"kind":"identifier","text":"waypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1maxSpeed\/title","value":"maxSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1maxSpeed\/fragments","value":[{"kind":"identifier","text":"maxSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1events\/title","value":"events"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1events\/fragments","value":[{"kind":"identifier","text":"events"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1invalid\/title","value":"FairmaticDriveTypeInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}