{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject","doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP","doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"Configuration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticConfiguration","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/init(sdkKey:driverId:driverAttributes:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverAttributes","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/implementsMultipleAccidentCallbacks","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/sdkKey"]}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"This class contains parameters required by "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/fairmaticsdk\/configuration"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/implementsMultipleAccidentCallbacks":{"role":"symbol","title":"implementsMultipleAccidentCallbacks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"implementsMultipleAccidentCallbacks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Developers have to set this property to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the app implements multiple accident callbacks -"},{"type":"text","text":" "},{"type":"text","text":"potential callback and final callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/implementsMultipleAccidentCallbacks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"implementsMultipleAccidentCallbacks"}],"url":"\/documentation\/fairmaticsdk\/configuration\/implementsmultipleaccidentcallbacks"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/isValidInputParameter(_:)":{"role":"symbol","title":"isValidInputParameter(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidInputParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this method to check whether the parameter string passed"},{"type":"text","text":" "},{"type":"text","text":"to the SDK is valid."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isValidInputParameter:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/isvalidinputparameter(_:)"},"doc://com.fairmatic.FairmaticSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/driverId":{"role":"symbol","title":"driverId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Unique ID for the current user. This can be any ID used by your app to"},{"type":"text","text":" "},{"type":"text","text":"identify its users."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/isValidInputParameter(_:)"},{"type":"text","text":" to verify that userId is valid."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverId"}],"url":"\/documentation\/fairmaticsdk\/configuration\/driverid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/driveDetectionMode":{"role":"symbol","title":"driveDetectionMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"}],"abstract":[{"type":"text","text":"Use this mode to control the SDK’s behaviour for detecting drives"},{"type":"text","text":" "},{"type":"text","text":"automatically. This mode can be changed at a later point using"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/configuration\/drivedetectionmode"},"doc://com.fairmatic.FairmaticSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/init(sdkKey:driverId:driverAttributes:)":{"role":"symbol","title":"init(sdkKey:driverId:driverAttributes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sdkKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driverAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriverAttributes","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a Fairmatic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/init(sdkKey:driverId:driverAttributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSdkKey:driverId:driverAttributes:"}],"url":"\/documentation\/fairmaticsdk\/configuration\/init(sdkkey:driverid:driverattributes:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/driverAttributes":{"role":"symbol","title":"driverAttributes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriverAttributes","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticDriverAttributes"}],"abstract":[{"type":"text","text":"Attributes for the current user. These attributes are stored on the server"},{"type":"text","text":" "},{"type":"text","text":"and are provided in Fairmatic’s APIs. Any existing attributes would be overwritten"},{"type":"text","text":" "},{"type":"text","text":"on the server when a non-nil value for this param is passed. Passing nil is a no-op."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driverAttributes"}],"url":"\/documentation\/fairmaticsdk\/configuration\/driverattributes"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Configuration/sdkKey":{"role":"symbol","title":"sdkKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Your SDK key."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/sdkKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sdkKey"}],"url":"\/documentation\/fairmaticsdk\/configuration\/sdkkey"},"doc://com.fairmatic.FairmaticSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/setDriveDetectionMode(_:completionHandler:)":{"role":"symbol","title":"setDriveDetectionMode(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDriveDetectionMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DriveDetectionMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Change the drive detection mode to control how Fairmatic SDK detects drives."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode"},{"type":"text","text":" for further details. This will override the mode sent"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration"},{"type":"text","text":" during setup."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/setDriveDetectionMode(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/setdrivedetectionmode(_:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driveDetectionMode","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverAttributes","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/driverId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/implementsMultipleAccidentCallbacks","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/sdkKey"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Configuration\/init(sdkKey:driverId:driverAttributes:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/title","value":"FairmaticConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"FairmaticConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1implementsMultipleAccidentCallbacks\/title","value":"implementsMultipleAccidentCallbacks"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1implementsMultipleAccidentCallbacks\/fragments","value":[{"kind":"identifier","text":"implementsMultipleAccidentCallbacks"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/title","value":"isValidInputParameter:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1isValidInputParameter(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isValidInputParameter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driverId\/title","value":"driverId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driverId\/fragments","value":[{"kind":"identifier","text":"driverId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driveDetectionMode\/title","value":"driveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driveDetectionMode\/fragments","value":[{"kind":"identifier","text":"driveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1init(sdkKey:driverId:driverAttributes:)\/title","value":"initWithSdkKey:driverId:driverAttributes:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1init(sdkKey:driverId:driverAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSdkKey:driverId:driverAttributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driverAttributes\/title","value":"driverAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1driverAttributes\/fragments","value":[{"kind":"identifier","text":"driverAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1sdkKey\/title","value":"sdkKey"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Configuration~1sdkKey\/fragments","value":[{"kind":"identifier","text":"sdkKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/title","value":"setDriveDetectionMode:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1setDriveDetectionMode(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDriveDetectionMode:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}