{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDirectionOfImpact) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/directionofimpact"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/directionofimpact"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH","doc:\/\/com.fairmatic.FairmaticSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Direction of impact detected by SDK at the time of the accident"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"title":"DirectionOfImpact","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DirectionOfImpact"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/broadside","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/front","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/rear","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/Equatable-Implementations","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/unknown":{"role":"symbol","title":"DirectionOfImpact.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Indicates an unknown direction of impact"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactUnknown"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/unknown"},"doc://com.fairmatic.FairmaticSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SY"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/broadside":{"role":"symbol","title":"DirectionOfImpact.broadside","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadside"}],"abstract":[{"type":"text","text":"Indicates a broadside direction of impact"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/broadside","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/broadside"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/directionofimpact\/init(rawvalue:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact":{"role":"symbol","title":"DirectionOfImpact","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"abstract":[{"type":"text","text":"Direction of impact detected by SDK at the time of the accident"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/directionofimpact\/rawrepresentable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/rear":{"role":"symbol","title":"DirectionOfImpact.rear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"abstract":[{"type":"text","text":"Indicates a rear direction of impact"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/rear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/rear"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/directionofimpact\/equatable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact/front":{"role":"symbol","title":"DirectionOfImpact.front","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"abstract":[{"type":"text","text":"Indicates a front direction of impact"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/front","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDirectionOfImpactFront"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact\/front"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDirectionOfImpact"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/broadside","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/front","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/rear","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDirectionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1unknown\/title","value":"FairmaticDirectionOfImpactUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1unknown\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1broadside\/title","value":"FairmaticDirectionOfImpactBroadside"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1broadside\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactBroadside"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/title","value":"FairmaticDirectionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1rear\/title","value":"FairmaticDirectionOfImpactRear"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1rear\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactRear"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1front\/title","value":"FairmaticDirectionOfImpactFront"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact~1front\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpactFront"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}