{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriveInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EstimatedDriveInfo"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject","doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP","doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"title":"DriveInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/distance","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/endTimestamp","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/extrapolationDetails","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/insurancePeriod","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/phonePosition","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/sessionId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/startTimestamp","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/trackingId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/tripWarnings","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"]}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event":{"role":"symbol","title":"Event","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"abstract":[{"type":"text","text":"Represents a driving behavior event like phone use, aggressive acceleration etc."},{"type":"text","text":" "},{"type":"text","text":"It is part of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo"},{"type":"text","text":" object of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"url":"\/documentation\/fairmaticsdk\/event"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location"},{"type":"text","text":" "},{"type":"text","text":"and last to trip end location."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waypoints"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/waypoints"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/events":{"role":"symbol","title":"events","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"events"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEvent"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event"},{"type":"text","text":" objects for this trip in increasing order of timestamp."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"events"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/events"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/averageSpeed":{"role":"symbol","title":"averageSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The average speed of trip in metres\/second"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"averageSpeed"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/averagespeed"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/insurancePeriod":{"role":"symbol","title":"insurancePeriod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insurancePeriod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsurancePeriod","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod"}],"abstract":[{"type":"text","text":"The insurance period for this drive"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/insurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/insuranceperiod"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance of the trip in metres"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/distance"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType/drive":{"role":"symbol","title":"DriveType.drive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"drive"}],"abstract":[{"type":"text","text":"This trip was taken in a valid "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/drive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/drive"},"doc://com.fairmatic.FairmaticSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processAnalysis(ofDrive:)":{"role":"symbol","title":"processAnalysis(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK finishes"},{"type":"text","text":" "},{"type":"text","text":"full analysis of all valid drives returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAnalysisOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/LocationPoint":{"role":"symbol","title":"LocationPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationPoint"}],"abstract":[{"type":"text","text":"Represents a geographical coordinate."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationPoint"}],"url":"\/documentation\/fairmaticsdk\/locationpoint"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processEnd(ofDrive:)":{"navigatorTitle":[{"kind":"identifier","text":"processEndOfDrive:"}],"role":"symbol","title":"processEnd(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EstimatedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticEstimatedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate on the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK detects a drive to have been completed."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processend(ofdrive:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveType/invalid":{"role":"symbol","title":"DriveType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Sometimes, the SDK detects that a trip is invalid after it has been started."},{"type":"text","text":" "},{"type":"text","text":"In these cases, the values for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed"},{"type":"text","text":" "},{"type":"text","text":"will have invalid values."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/invalid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/userMode":{"role":"symbol","title":"userMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMode","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticUserMode"}],"abstract":[{"type":"text","text":"Whether the user was a driver or a passenger."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userMode"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/usermode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/extrapolationDetails":{"role":"symbol","title":"extrapolationDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extrapolationDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExtrapolationDetails","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticExtrapolationDetails"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The extrapolated details for a drive."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" is not "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/drive"},{"type":"text","text":" then it will be set to nil."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/extrapolationDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"extrapolationDetails"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/extrapolationdetails"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/sessionId":{"role":"symbol","title":"sessionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Session id is specified by the enclosing application when it wants to"},{"type":"text","text":" "},{"type":"text","text":"record a session using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/sessionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionId"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/sessionid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/tripWarnings":{"role":"symbol","title":"tripWarnings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tripWarnings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TripWarning","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticTripWarning"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarning"},{"type":"text","text":" objects for this trip."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/tripWarnings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tripWarnings"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/tripwarnings"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TripWarning":{"role":"symbol","title":"TripWarning","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TripWarning"}],"abstract":[{"type":"text","text":"Represents a single warning that might have occurred during your trip."},{"type":"text","text":" "},{"type":"text","text":"A collection of these warnings are provided using the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TripWarning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TripWarning"}],"url":"\/documentation\/fairmaticsdk\/tripwarning"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/endTimestamp":{"role":"symbol","title":"endTimestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The end timestamp of trip in milliseconds since epoch"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/endTimestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endTimestamp"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/endtimestamp"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startSession(_:)":{"role":"symbol","title":"startSession(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start a session in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSession:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startsession(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/startTimestamp":{"role":"symbol","title":"startTimestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The start timestamp of trip in milliseconds since epoch."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/startTimestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTimestamp"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/starttimestamp"},"doc://com.fairmatic.FairmaticSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo":{"role":"symbol","title":"DriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveInfo"}],"url":"\/documentation\/fairmaticsdk\/driveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EstimatedDriveInfo":{"role":"symbol","title":"EstimatedDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EstimatedDriveInfo"}],"abstract":[{"type":"text","text":"This contains the best estimated results for a drive, this is returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EstimatedDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EstimatedDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/estimateddriveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/driveId":{"role":"symbol","title":"driveId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The unique Id for this drive"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveId"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/driveid"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/vehicleType":{"role":"symbol","title":"vehicleType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"}],"abstract":[{"type":"text","text":"The type of vehicle."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicleType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/vehicletype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/maxSpeed":{"role":"symbol","title":"maxSpeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The maximum speed of trip in metres\/second"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxSpeed"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/maxspeed"},"doc://com.fairmatic.FairmaticSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"},"doc://com.fairmatic.FairmaticSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AnalyzedDriveInfo":{"role":"symbol","title":"AnalyzedDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyzedDriveInfo"}],"abstract":[{"type":"text","text":"This contains the fully analyzed results for a drive, this is returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback for all the trips with the value of"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" not set to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveType\/invalid"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnalyzedDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/analyzeddriveinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/trackingId":{"role":"symbol","title":"trackingId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Tracking id is specified by the enclosing application when it"},{"type":"text","text":" "},{"type":"text","text":"wants to start a drive manually by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/trackingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingId"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/trackingid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/phonePosition":{"role":"symbol","title":"phonePosition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phonePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PhonePosition","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticPhonePosition"}],"abstract":[{"type":"text","text":"The position of the phone during this trip."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/phonePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phonePosition"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/phoneposition"},"doc://com.fairmatic.FairmaticSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/distance","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/driveType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/endTimestamp","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/events","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/extrapolationDetails","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/insurancePeriod","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/phonePosition","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/sessionId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/startTimestamp","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/trackingId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/tripWarnings","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/userMode","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EstimatedDriveInfo"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriveInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event\/title","value":"FairmaticEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event\/fragments","value":[{"kind":"identifier","text":"FairmaticEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1waypoints\/title","value":"waypoints"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1waypoints\/fragments","value":[{"kind":"identifier","text":"waypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1events\/title","value":"events"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1events\/fragments","value":[{"kind":"identifier","text":"events"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1averageSpeed\/title","value":"averageSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1averageSpeed\/fragments","value":[{"kind":"identifier","text":"averageSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1insurancePeriod\/title","value":"insurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1insurancePeriod\/fragments","value":[{"kind":"identifier","text":"insurancePeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1drive\/title","value":"FairmaticDriveTypeDrive"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1drive\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeDrive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/title","value":"processAnalysisOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAnalysisOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/title","value":"FairmaticLocationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/fragments","value":[{"kind":"identifier","text":"FairmaticLocationPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/title","value":"processEndOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processEnd(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processEndOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1invalid\/title","value":"FairmaticDriveTypeInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveType~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/title","value":"userMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1userMode\/fragments","value":[{"kind":"identifier","text":"userMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1extrapolationDetails\/title","value":"extrapolationDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1extrapolationDetails\/fragments","value":[{"kind":"identifier","text":"extrapolationDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1sessionId\/title","value":"sessionId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1sessionId\/fragments","value":[{"kind":"identifier","text":"sessionId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1tripWarnings\/title","value":"tripWarnings"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1tripWarnings\/fragments","value":[{"kind":"identifier","text":"tripWarnings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarning\/title","value":"FairmaticTripWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TripWarning\/fragments","value":[{"kind":"identifier","text":"FairmaticTripWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1endTimestamp\/title","value":"endTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1endTimestamp\/fragments","value":[{"kind":"identifier","text":"endTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/title","value":"startSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1startTimestamp\/title","value":"startTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1startTimestamp\/fragments","value":[{"kind":"identifier","text":"startTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/title","value":"FairmaticDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EstimatedDriveInfo\/title","value":"FairmaticEstimatedDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EstimatedDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticEstimatedDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveId\/title","value":"driveId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1driveId\/fragments","value":[{"kind":"identifier","text":"driveId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1vehicleType\/title","value":"vehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1vehicleType\/fragments","value":[{"kind":"identifier","text":"vehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1maxSpeed\/title","value":"maxSpeed"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1maxSpeed\/fragments","value":[{"kind":"identifier","text":"maxSpeed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AnalyzedDriveInfo\/title","value":"FairmaticAnalyzedDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AnalyzedDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAnalyzedDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1trackingId\/title","value":"trackingId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1trackingId\/fragments","value":[{"kind":"identifier","text":"trackingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1phonePosition\/title","value":"phonePosition"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1phonePosition\/fragments","value":[{"kind":"identifier","text":"phonePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}