{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriveDetectionMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveDetectionMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivedetectionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/drivedetectionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH","doc:\/\/com.fairmatic.FairmaticSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Dictates the functioning of Fairmatic’s drive detection."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveDetectionMode"}],"title":"DriveDetectionMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticDriveDetectionMode","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriveDetectionMode"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoOFF","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/insurance"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/Equatable-Implementations","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.FairmaticSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SY"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/autoOFF":{"role":"symbol","title":"DriveDetectionMode.autoOFF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoOFF"}],"abstract":[{"type":"text","text":"In this mode auto drive-detection is disabled. All other APIs on "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" "},{"type":"text","text":"can be invoked independent of this mode. For recording trips in this mode, the"},{"type":"text","text":" "},{"type":"text","text":"application has to explicitly invoke the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoOFF","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoOFF"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/autooff"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic":{"role":"symbol","title":"Fairmatic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fairmatic"}],"abstract":[{"type":"text","text":"The Fairmatic API."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fairmatic"}],"url":"\/documentation\/fairmaticsdk\/fairmatic"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/rawrepresentable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/autoON":{"role":"symbol","title":"DriveDetectionMode.autoON","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoON"}],"abstract":[{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK will automatically track drives in background in"},{"type":"text","text":" "},{"type":"text","text":"this mode once the SDK is setup. At the same time, the application can invoke"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"},{"type":"text","text":" to explicitly start recording a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoON"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/autoon"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode":{"role":"symbol","title":"DriveDetectionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveDetectionMode"}],"abstract":[{"type":"text","text":"Dictates the functioning of Fairmatic’s drive detection."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveDetectionMode"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/init(rawvalue:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/insurance":{"role":"symbol","title":"DriveDetectionMode.insurance","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insurance"}],"abstract":[{"type":"text","text":"In this mode drive detection is controlled by Insurance period APIs present in"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" class. Only insurance related APIs should be used in this mode to control "},{"type":"codeVoice","code":"FairmaticSDK"},{"type":"text","text":" behavior."},{"type":"text","text":" "},{"type":"text","text":"This is the Default mode."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/insurance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveDetectionModeInsurance"}],"url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/insurance"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveDetectionMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/drivedetectionmode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveDetectionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriveDetectionMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoOFF","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/autoON","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveDetectionMode\/insurance"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriveDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoOFF\/title","value":"FairmaticDriveDetectionModeAutoOFF"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoOFF\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoOFF"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/title","value":"Fairmatic"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic\/fragments","value":[{"kind":"identifier","text":"Fairmatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoON\/title","value":"FairmaticDriveDetectionModeAutoON"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1autoON\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionModeAutoON"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/title","value":"FairmaticDriveDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1insurance\/title","value":"FairmaticDriveDetectionModeInsurance"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveDetectionMode~1insurance\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveDetectionModeInsurance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}