{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticDriveStartInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveStartInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/drivestartinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/drivestartinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject","doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP","doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Information about start of a drive."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveStartInfo"}],"title":"DriveStartInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveStartInfo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DriveStartInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/distance","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/driveId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/insurancePeriod","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/sessionId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/startTimestamp","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/trackingId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/waypoints"]}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/startTimestamp":{"role":"symbol","title":"startTimestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The start timestamp of trip in milliseconds since epoch"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/startTimestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTimestamp"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/starttimestamp"},"doc://com.fairmatic.FairmaticSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/waypoints":{"role":"symbol","title":"waypoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waypoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint"},{"type":"text","text":" objects corresponding to this trip in"},{"type":"text","text":" "},{"type":"text","text":"increasing order of timestamp. The first point corresponds to trip start location."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/waypoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waypoints"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/waypoints"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/trackingId":{"role":"symbol","title":"trackingId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Tracking id is specified by the enclosing application when it"},{"type":"text","text":" "},{"type":"text","text":"wants to start a drive manually by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/trackingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingId"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/trackingid"},"doc://com.fairmatic.FairmaticSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/LocationPoint":{"role":"symbol","title":"LocationPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationPoint"}],"abstract":[{"type":"text","text":"Represents a geographical coordinate."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationPoint"}],"url":"\/documentation\/fairmaticsdk\/locationpoint"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startManualDrive(trackingId:completionHandler:)":{"role":"symbol","title":"startManualDrive(trackingId:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startManualDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"This API allows application to override Fairmatic’s auto drive detection"},{"type":"text","text":" "},{"type":"text","text":"algorithm."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startManualDrive(trackingId:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startmanualdrive(trackingid:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/driveId":{"role":"symbol","title":"driveId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The unique Id for this drive"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/driveId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveId"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/driveid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/sessionId":{"role":"symbol","title":"sessionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Session id is specified by the enclosing application when it wants to"},{"type":"text","text":" "},{"type":"text","text":"record a session using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/sessionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionId"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/sessionid"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startSession(_:)":{"role":"symbol","title":"startSession(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start a session in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startSession(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSession:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startsession(_:)"},"doc://com.fairmatic.FairmaticSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo":{"role":"symbol","title":"DriveStartInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveStartInfo"}],"abstract":[{"type":"text","text":"Information about start of a drive."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveStartInfo"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance of the trip in metres"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/distance"},"doc://com.fairmatic.FairmaticSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveStartInfo/insurancePeriod":{"role":"symbol","title":"insurancePeriod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insurancePeriod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsurancePeriod","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod"}],"abstract":[{"type":"text","text":"The insurance period for this drive"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/insurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/drivestartinfo\/insuranceperiod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticDriveStartInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveStartInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticDriveStartInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/distance","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/driveId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/insurancePeriod","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/sessionId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/startTimestamp","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/trackingId","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveStartInfo\/waypoints"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticDriveStartInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1startTimestamp\/title","value":"startTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1startTimestamp\/fragments","value":[{"kind":"identifier","text":"startTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1waypoints\/title","value":"waypoints"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1waypoints\/fragments","value":[{"kind":"identifier","text":"waypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1trackingId\/title","value":"trackingId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1trackingId\/fragments","value":[{"kind":"identifier","text":"trackingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/title","value":"FairmaticLocationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/fragments","value":[{"kind":"identifier","text":"FairmaticLocationPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/title","value":"startManualDriveWithTrackingId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startManualDrive(trackingId:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startManualDriveWithTrackingId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1driveId\/title","value":"driveId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1driveId\/fragments","value":[{"kind":"identifier","text":"driveId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1sessionId\/title","value":"sessionId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1sessionId\/fragments","value":[{"kind":"identifier","text":"sessionId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/title","value":"startSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startSession(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo\/title","value":"FairmaticDriveStartInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveStartInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1insurancePeriod\/title","value":"insurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveStartInfo~1insurancePeriod\/fragments","value":[{"kind":"identifier","text":"insurancePeriod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}