{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticInsurancePeriod) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InsurancePeriod"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each drive belongs to exactly one of these insurance periods."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/insuranceperiod"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH","doc:\/\/com.fairmatic.FairmaticSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The types of insurance period in "},{"type":"codeVoice","code":"Fairmatic"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InsurancePeriod"}],"title":"InsurancePeriod","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticInsurancePeriod","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"InsurancePeriod"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/noPeriod","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period1","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period2","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period3"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/Equatable-Implementations","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/insuranceperiod\/equatable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/insuranceperiod\/rawrepresentable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod":{"role":"symbol","title":"InsurancePeriod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InsurancePeriod"}],"abstract":[{"type":"text","text":"The types of insurance period in "},{"type":"codeVoice","code":"Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InsurancePeriod"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/period1":{"role":"symbol","title":"InsurancePeriod.period1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period1"}],"abstract":[{"type":"text","text":"Drives detected in insurance period 1 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDriveWithPeriod1(completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/period1"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod3:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod3:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod3"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 3 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod3:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SY"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/noPeriod":{"role":"symbol","title":"InsurancePeriod.noPeriod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPeriod"}],"abstract":[{"type":"text","text":"Applications that do not use insurance APIs will have drives with"},{"type":"text","text":" "},{"type":"text","text":"this value for insurance period"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/noPeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/noperiod"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/period3":{"role":"symbol","title":"InsurancePeriod.period3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period3"}],"abstract":[{"type":"text","text":"Drives undertaken with insurance period 3 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod3:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/period3"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDrive(withPeriod2:completionHandler:)":{"role":"symbol","title":"startDrive(withPeriod2:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDrive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPeriod2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 2 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrive(withperiod2:completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/insuranceperiod\/init(rawvalue:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Fairmatic/startDriveWithPeriod1(completionHandler:)":{"role":"symbol","title":"startDriveWithPeriod1(completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDriveWithPeriod1"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsuranceAPICompletionHandler","preciseIdentifier":"s:12FairmaticSDK29InsuranceAPICompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Start Fairmatic insurance period 1 in the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDriveWithPeriod1(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDriveWithPeriod1WithCompletionHandler:"}],"url":"\/documentation\/fairmaticsdk\/fairmatic\/startdrivewithperiod1(completionhandler:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/InsurancePeriod/period2":{"role":"symbol","title":"InsurancePeriod.period2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"period2"}],"abstract":[{"type":"text","text":"Drives undertaken with insurance period 2 will have this value."},{"type":"text","text":" "},{"type":"text","text":"Refer: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic\/startDrive(withPeriod2:completionHandler:)"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod2"}],"url":"\/documentation\/fairmaticsdk\/insuranceperiod\/period2"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticInsurancePeriod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriod"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticInsurancePeriod"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/noPeriod","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period1","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period2","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/InsurancePeriod\/period3"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticInsurancePeriod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod\/title","value":"FairmaticInsurancePeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period1\/title","value":"FairmaticInsurancePeriodPeriod1"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period1\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod1"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/title","value":"startDriveWithPeriod3:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod3:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod3:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1noPeriod\/title","value":"FairmaticInsurancePeriodNoPeriod"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1noPeriod\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodNoPeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period3\/title","value":"FairmaticInsurancePeriodPeriod3"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period3\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod3"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod2:completionHandler:)\/title","value":"startDriveWithPeriod2:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDrive(withPeriod2:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod2:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDriveWithPeriod1(completionHandler:)\/title","value":"startDriveWithPeriod1WithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Fairmatic~1startDriveWithPeriod1(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startDriveWithPeriod1WithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period2\/title","value":"FairmaticInsurancePeriodPeriod2"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1InsurancePeriod~1period2\/fragments","value":[{"kind":"identifier","text":"FairmaticInsurancePeriodPeriod2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}