{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticSpeedingData) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpeedingData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/speedingdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/speedingdata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject","doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP","doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP","doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A valid object of this class is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" "},{"type":"text","text":"whenever "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is equal to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpeedingData"}],"title":"SpeedingData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticSpeedingData","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SpeedingData"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/maxUserSpeedMPS","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/speedLimitMPS","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/userSpeedMPS"]}],"references":{"doc://com.fairmatic.FairmaticSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s28CustomDebugStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SpeedingData/speedLimitMPS":{"role":"symbol","title":"speedLimitMPS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedLimitMPS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The speed limit in metres per second."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/speedLimitMPS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speedLimitMPS"}],"url":"\/documentation\/fairmaticsdk\/speedingdata\/speedlimitmps"},"doc://com.fairmatic.FairmaticSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SpeedingData":{"role":"symbol","title":"SpeedingData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpeedingData"}],"abstract":[{"type":"text","text":"A valid object of this class is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" "},{"type":"text","text":"whenever "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is equal to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpeedingData"}],"url":"\/documentation\/fairmaticsdk\/speedingdata"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SpeedingData/maxUserSpeedMPS":{"role":"symbol","title":"maxUserSpeedMPS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxUserSpeedMPS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Maximum speed of the user during this speeding event duration in metres per second."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/maxUserSpeedMPS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxUserSpeedMPS"}],"url":"\/documentation\/fairmaticsdk\/speedingdata\/maxuserspeedmps"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType/overSpeeding":{"role":"symbol","title":"EventType.overSpeeding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overSpeeding"}],"abstract":[{"type":"text","text":"This denotes the aggressive behavior of speeding more than allowed."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData"},{"type":"text","text":" in this case."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/overspeeding"},"doc://com.fairmatic.FairmaticSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s23CustomStringConvertibleP"},"doc://com.fairmatic.FairmaticSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/s7CVarArgP"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/speedingData":{"role":"symbol","title":"speedingData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speedingData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpeedingData","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticSpeedingData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional data in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/overSpeeding"},{"type":"text","text":", will be nil otherwise."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/speedingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speedingData"}],"url":"\/documentation\/fairmaticsdk\/event\/speedingdata"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/objc(pl)NSObject"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/SpeedingData/userSpeedMPS":{"role":"symbol","title":"userSpeedMPS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSpeedMPS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The average speed of the user during this speeding event duration in metres per second."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/userSpeedMPS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userSpeedMPS"}],"url":"\/documentation\/fairmaticsdk\/speedingdata\/userspeedmps"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventType":{"role":"symbol","title":"eventType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"}],"abstract":[{"type":"text","text":"The type of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventType"}],"url":"\/documentation\/fairmaticsdk\/event\/eventtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticSpeedingData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticSpeedingData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticSpeedingData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/maxUserSpeedMPS","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/speedLimitMPS","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/SpeedingData\/userSpeedMPS"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticSpeedingData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1speedLimitMPS\/title","value":"speedLimitMPS"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1speedLimitMPS\/fragments","value":[{"kind":"identifier","text":"speedLimitMPS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData\/title","value":"FairmaticSpeedingData"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData\/fragments","value":[{"kind":"identifier","text":"FairmaticSpeedingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1maxUserSpeedMPS\/title","value":"maxUserSpeedMPS"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1maxUserSpeedMPS\/fragments","value":[{"kind":"identifier","text":"maxUserSpeedMPS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/title","value":"FairmaticventTypeOverSpeeding"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1overSpeeding\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeOverSpeeding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/title","value":"speedingData"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1speedingData\/fragments","value":[{"kind":"identifier","text":"speedingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1userSpeedMPS\/title","value":"userSpeedMPS"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1SpeedingData~1userSpeedMPS\/fragments","value":[{"kind":"identifier","text":"userSpeedMPS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/title","value":"eventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/fragments","value":[{"kind":"identifier","text":"eventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}