{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FairmaticTurnDirection) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TurnDirection"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/turndirection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/turndirection"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/SQ","doc:\/\/com.fairmatic.FairmaticSDK\/SH","doc:\/\/com.fairmatic.FairmaticSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection"},{"type":"text","text":", it represents the turn direction for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/hardTurn"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TurnDirection"}],"title":"TurnDirection","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@FairmaticSDK@E@FairmaticTurnDirection","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TurnDirection"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/left","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/notAvailable","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/right"]},{"title":"Initializers","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/Equatable-Implementations","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/right":{"role":"symbol","title":"TurnDirection.right","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"abstract":[{"type":"text","text":"Indicates that the turn direction of the event was right."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/right","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticTurnDirectionRight"}],"url":"\/documentation\/fairmaticsdk\/turndirection\/right"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/EventType/hardTurn":{"role":"symbol","title":"EventType.hardTurn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardTurn"}],"abstract":[{"type":"text","text":"This denotes a hard turn as detected by Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/hardTurn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeHardTurn"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/hardturn"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/turndirection\/equatable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/notAvailable":{"role":"symbol","title":"TurnDirection.notAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAvailable"}],"abstract":[{"type":"text","text":"This is returned for all "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType"},{"type":"text","text":" values other than "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/hardTurn"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/notAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticTurnDirectionNotAvailable"}],"url":"\/documentation\/fairmaticsdk\/turndirection\/notavailable"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk\/turndirection\/init(rawvalue:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SY"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/left":{"role":"symbol","title":"TurnDirection.left","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"abstract":[{"type":"text","text":"Indicates that the turn direction of the event was Left."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/left","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticTurnDirectionLeft"}],"url":"\/documentation\/fairmaticsdk\/turndirection\/left"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/turnDirection":{"role":"symbol","title":"turnDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TurnDirection","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticTurnDirection"}],"abstract":[{"type":"text","text":"Denotes the turn direction of a hard turn whether a left or right turn."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnDirection"}],"url":"\/documentation\/fairmaticsdk\/event\/turndirection"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fairmaticsdk\/turndirection\/rawrepresentable-implementations"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/TurnDirection":{"role":"symbol","title":"TurnDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TurnDirection"}],"abstract":[{"type":"text","text":"This is returned in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/turnDirection"},{"type":"text","text":", it represents the turn direction for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/EventType\/hardTurn"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TurnDirection"}],"url":"\/documentation\/fairmaticsdk\/turndirection"},"doc://com.fairmatic.FairmaticSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SH"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/Event/eventType":{"role":"symbol","title":"eventType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticventType"}],"abstract":[{"type":"text","text":"The type of the event."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Event\/eventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventType"}],"url":"\/documentation\/fairmaticsdk\/event\/eventtype"},"doc://com.fairmatic.FairmaticSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticTurnDirection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticTurnDirection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FairmaticTurnDirection"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/left","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/notAvailable","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/TurnDirection\/right"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticTurnDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection~1right\/title","value":"FairmaticTurnDirectionRight"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection~1right\/fragments","value":[{"kind":"identifier","text":"FairmaticTurnDirectionRight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1hardTurn\/title","value":"FairmaticventTypeHardTurn"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1EventType~1hardTurn\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeHardTurn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection~1notAvailable\/title","value":"FairmaticTurnDirectionNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection~1notAvailable\/fragments","value":[{"kind":"identifier","text":"FairmaticTurnDirectionNotAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection~1left\/title","value":"FairmaticTurnDirectionLeft"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection~1left\/fragments","value":[{"kind":"identifier","text":"FairmaticTurnDirectionLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1turnDirection\/title","value":"turnDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1turnDirection\/fragments","value":[{"kind":"identifier","text":"turnDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection\/title","value":"FairmaticTurnDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1TurnDirection\/fragments","value":[{"kind":"identifier","text":"FairmaticTurnDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/title","value":"eventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1Event~1eventType\/fragments","value":[{"kind":"identifier","text":"eventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}