{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"associateVehicle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vehicleInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo","text":"VehicleInfo"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"vehicleInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"VehicleInfo"},{"type":"text","text":" object to associate."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After successful association of vehicle information, whenever Fairmatic SDK will detect"},{"type":"text","text":" "},{"type":"text","text":"a connection to this bluetooth device while the user is driving, it will include this vehicleId"},{"type":"text","text":" "},{"type":"text","text":"in the tags array of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/AnalyzedDriveInfo"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the user connect to bluetooth of multiple associated vehicles during the drive"},{"type":"text","text":" "},{"type":"text","text":"the latest vehicleId will be used as tag.  Maximum of two vehicles can be associated."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bluetooth device of the associated vehicle needs to be the audio route for some"},{"type":"text","text":" "},{"type":"text","text":"duration of the drive for tagging to happen."}]}],"type":"aside","name":"Note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError"},{"type":"text","text":" to get details on the errors thrown by this method."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"type":"codeListing","syntax":"swift","code":["let vehicleInfo = VehicleInfo(vehicleId: \"vehicleId\",","                              bluetoothId: \"14:0F:C7:62:F8:9E\")","try FairmaticVehicleTagging.associateVehicle(vehicleInfo)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Bluetooth stereos in automobiles are primarily classic Bluetooth devices, which might not be discoverable from your app."},{"type":"text","text":" "},{"type":"text","text":"When you associate the user’s vehicle, ask the user to connect their stereo and play audio."},{"type":"text","text":" "},{"type":"text","text":"Then, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getActiveBluetoothDevice()"},{"type":"text","text":" to determine the active bluetooth connection and get the identifier"},{"type":"text","text":" "},{"type":"text","text":"of the device."},{"type":"text","text":" "},{"type":"text","text":"Start with this code:"}]},{"type":"codeListing","syntax":"swift","code":[" if let bluetoothDevice = FairmaticVehicleTagging.getActiveBluetoothDevice() {","    let vehicleInfo = VehicleInfo(vehicleId: \"vehicleId\",","                                  bluetoothId: bluetoothDevice.identifier)","    try FairmaticVehicleTagging.associateVehicle(vehicleInfo)"," }"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/associatevehicle(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/associatevehicle(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/associateVehicle(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Associates the vehicle to Fairmatic SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"associateVehicle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"associateVehicle(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleTagging(cm)associateVehicle:error:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"associateVehicle:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processAnalysis(ofDrive:)":{"role":"symbol","title":"processAnalysis(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK finishes"},{"type":"text","text":" "},{"type":"text","text":"full analysis of all valid drives returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAnalysisOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveType/invalid":{"role":"symbol","title":"DriveType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Sometimes, the SDK detects that a trip is invalid after it has been started."},{"type":"text","text":" "},{"type":"text","text":"In these cases, the values for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/waypoints"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/events"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/score"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/maxSpeed"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/averageSpeed"},{"type":"text","text":" "},{"type":"text","text":"will have invalid values."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}],"url":"\/documentation\/fairmaticsdk\/drivetype\/invalid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleInfo":{"role":"symbol","title":"VehicleInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to a vehicle."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleInfo"}],"url":"\/documentation\/fairmaticsdk\/vehicleinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTaggingError":{"role":"symbol","title":"FairmaticVehicleTaggingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"abstract":[{"type":"text","text":"Error returned as code to NSError from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"},{"type":"text","text":" public APIs"},{"type":"text","text":" "},{"type":"text","text":"in case of failures."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTaggingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletaggingerror"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/AnalyzedDriveInfo":{"role":"symbol","title":"AnalyzedDriveInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyzedDriveInfo"}],"abstract":[{"type":"text","text":"This contains the fully analyzed results for a drive, this is returned from"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback for all the trips with the value of"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType"},{"type":"text","text":" not set to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveType\/invalid"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/AnalyzedDriveInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnalyzedDriveInfo"}],"url":"\/documentation\/fairmaticsdk\/analyzeddriveinfo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getActiveBluetoothDevice()":{"role":"symbol","title":"getActiveBluetoothDevice()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getActiveBluetoothDevice"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"BluetoothDevice","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticBluetoothDevice"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the active bluetooth device, if there is any, otherwise returns nil."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getActiveBluetoothDevice()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getActiveBluetoothDevice"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getactivebluetoothdevice()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/associateVehicle(_:)":{"role":"symbol","title":"associateVehicle(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"associateVehicle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Associates the vehicle to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/associateVehicle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"associateVehicle:error:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/associatevehicle(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/DriveInfo/driveType":{"role":"symbol","title":"driveType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DriveType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDriveType"}],"abstract":[{"type":"text","text":"The type of the drive. This decides what other info parameters will be populated."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/DriveInfo\/driveType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"driveType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/drivetype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"associateVehicle:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"associateVehicle:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"associateVehicle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleInfo","text":"FairmaticVehicleInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"vehicleInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/title","value":"processAnalysisOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAnalysisOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1invalid\/title","value":"FairmaticDriveTypeInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveType~1invalid\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveTypeInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/title","value":"FairmaticVehicleInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/title","value":"FairmaticVehicleTaggingError"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTaggingError\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1AnalyzedDriveInfo\/title","value":"FairmaticAnalyzedDriveInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1AnalyzedDriveInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAnalyzedDriveInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getActiveBluetoothDevice()\/title","value":"getActiveBluetoothDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getActiveBluetoothDevice()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getActiveBluetoothDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1associateVehicle(_:)\/title","value":"associateVehicle:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1associateVehicle(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"associateVehicle:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/title","value":"driveType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1DriveInfo~1driveType\/fragments","value":[{"kind":"identifier","text":"driveType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}