{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getActiveBluetoothDevice"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticBluetoothDevice","text":"BluetoothDevice"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The active bluetooth device is the one through which audio will play."},{"type":"text","text":" "},{"type":"text","text":"Example: You may be connected to both car’s stereo and airpods but only"},{"type":"text","text":" "},{"type":"text","text":"one of them will be active, the one through which audio is playing or"},{"type":"text","text":" "},{"type":"text","text":"will play."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the user does not have multiple connected audio devices"},{"type":"text","text":" "},{"type":"text","text":"like headphones, airpods etc, then the connected car’s stereo is the"},{"type":"text","text":" "},{"type":"text","text":"active device."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getactivebluetoothdevice()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getactivebluetoothdevice()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getActiveBluetoothDevice()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the active bluetooth device, if there is any, otherwise returns nil."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getActiveBluetoothDevice"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"BluetoothDevice","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticBluetoothDevice"},{"kind":"text","text":"?"}],"title":"getActiveBluetoothDevice()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleTagging(cm)getActiveBluetoothDevice","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getActiveBluetoothDevice"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/BluetoothDevice":{"role":"symbol","title":"BluetoothDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothDevice"}],"abstract":[{"type":"text","text":"Wrapper to describe a bluetooth device."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BluetoothDevice"}],"url":"\/documentation\/fairmaticsdk\/bluetoothdevice"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging/getActiveBluetoothDevice()":{"role":"symbol","title":"getActiveBluetoothDevice()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getActiveBluetoothDevice"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"BluetoothDevice","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticBluetoothDevice"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the active bluetooth device, if there is any, otherwise returns nil."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging\/getActiveBluetoothDevice()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getActiveBluetoothDevice"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging\/getactivebluetoothdevice()"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticVehicleTagging":{"role":"symbol","title":"FairmaticVehicleTagging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FairmaticVehicleTagging"}],"abstract":[{"type":"text","text":"This class manages association and dissociation of vehicles to Fairmatic SDK."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticVehicleTagging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticVehicleTagging"}],"url":"\/documentation\/fairmaticsdk\/fairmaticvehicletagging"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getActiveBluetoothDevice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getActiveBluetoothDevice"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/BluetoothDevice","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticBluetoothDevice","text":"FairmaticBluetoothDevice"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getActiveBluetoothDevice"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice\/title","value":"FairmaticBluetoothDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1BluetoothDevice\/fragments","value":[{"kind":"identifier","text":"FairmaticBluetoothDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getActiveBluetoothDevice()\/title","value":"getActiveBluetoothDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging~1getActiveBluetoothDevice()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getActiveBluetoothDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/title","value":"FairmaticVehicleTagging"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticVehicleTagging\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTagging"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}