{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accident"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/eventtype\/accident"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/eventtype\/accident"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType\/accident","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This denotes a collision as detected by Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"},{"type":"text","text":" "},{"type":"text","text":"in realtime for this event."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accident"}],"title":"EventType.accident","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FairmaticSDK@E@FairmaticventType@FairmaticventTypeAccident","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeAccident"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventType/accident":{"role":"symbol","title":"EventType.accident","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accident"}],"abstract":[{"type":"text","text":"This denotes a collision as detected by Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"You will also receive "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)"},{"type":"text","text":" "},{"type":"text","text":"in realtime for this event."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType\/accident","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FairmaticventTypeAccident"}],"url":"\/documentation\/fairmaticsdk\/eventtype\/accident"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/FairmaticDelegate/processAccidentDetected(_:)":{"role":"symbol","title":"processAccidentDetected(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAccidentDetected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AccidentInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is fired on the main thread when an accident is detected by"},{"type":"text","text":" "},{"type":"text","text":"the SDK during a drive. Any ongoing auto-detected\/manual drives will be stopped"},{"type":"text","text":" "},{"type":"text","text":"after this point."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAccidentDetected(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAccidentDetected:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processaccidentdetected(_:)"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/EventType":{"role":"symbol","title":"EventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventType"}],"abstract":[{"type":"text","text":"The event type as specified in "},{"type":"codeVoice","code":"Event.eventType"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/EventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventType"}],"url":"\/documentation\/fairmaticsdk\/eventtype"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FairmaticventTypeAccident"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeAccident"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FairmaticventTypeAccident"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventType~1accident\/title","value":"FairmaticventTypeAccident"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventType~1accident\/fragments","value":[{"kind":"identifier","text":"FairmaticventTypeAccident"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/title","value":"processAccidentDetected:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAccidentDetected(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAccidentDetected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventType\/title","value":"FairmaticventType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1EventType\/fragments","value":[{"kind":"identifier","text":"FairmaticventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}