{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTaggedByBluetoothStereo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/vehicletaggingdetails\/istaggedbybluetoothstereo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/vehicletaggingdetails\/istaggedbybluetoothstereo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBluetoothStereo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This flag determines if vehicle is tagged using bluetooth stereo"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTaggedByBluetoothStereo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isTaggedByBluetoothStereo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleTaggingDetails(py)isTaggedByBluetoothStereo","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isTaggedByBluetoothStereo"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails":{"role":"symbol","title":"VehicleTaggingDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleTaggingDetails"}],"abstract":[{"type":"text","text":"Wrapper for vehicle tagging details for a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleTaggingDetails"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails/isTaggedByBluetoothStereo":{"role":"symbol","title":"isTaggedByBluetoothStereo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTaggedByBluetoothStereo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This flag determines if vehicle is tagged using bluetooth stereo"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/isTaggedByBluetoothStereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isTaggedByBluetoothStereo"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails\/istaggedbybluetoothstereo"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isTaggedByBluetoothStereo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isTaggedByBluetoothStereo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTaggedByBluetoothStereo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails\/title","value":"FairmaticVehicleTaggingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1isTaggedByBluetoothStereo\/title","value":"isTaggedByBluetoothStereo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1isTaggedByBluetoothStereo\/fragments","value":[{"kind":"identifier","text":"isTaggedByBluetoothStereo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}