{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/vehicletaggingdetails\/vehicleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/vehicletaggingdetails\/vehicleid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/vehicleId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The vehicleId of the tagged vehicle"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"vehicleId","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticVehicleTaggingDetails(py)vehicleId","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"vehicleId"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails"]]},"references":{"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails/vehicleId":{"role":"symbol","title":"vehicleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The vehicleId of the tagged vehicle"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails\/vehicleId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicleId"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails\/vehicleid"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.Fairmatic/documentation/FairmaticSDK/VehicleTaggingDetails":{"role":"symbol","title":"VehicleTaggingDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleTaggingDetails"}],"abstract":[{"type":"text","text":"Wrapper for vehicle tagging details for a drive."}],"identifier":"doc:\/\/com.fairmatic.Fairmatic\/documentation\/FairmaticSDK\/VehicleTaggingDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleTaggingDetails"}],"url":"\/documentation\/fairmaticsdk\/vehicletaggingdetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"vehicleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"vehicleId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"vehicleId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1vehicleId\/title","value":"vehicleId"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails~1vehicleId\/fragments","value":[{"kind":"identifier","text":"vehicleId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails\/title","value":"FairmaticVehicleTaggingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.Fairmatic~1documentation~1FairmaticSDK~1VehicleTaggingDetails\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleTaggingDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}