{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: A confidence number of 0 indicated that it was "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" an accident."},{"type":"text","text":" "},{"type":"text","text":"0 confidence number can be sent as a part of potential accident callback"},{"type":"text","text":" "},{"type":"text","text":"to invalidate the previous callback final accident callback for the same accident."},{"type":"text","text":" "},{"type":"text","text":"0 confidence number will never come as a part of potential accident callback."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Checkout "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()"},{"type":"text","text":" to test this scenario during development."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/confidencenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/confidencenumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/confidenceNumber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Measures an approximate precision of the detected collision. Ranges between 0 to 100."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"confidenceNumber","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo(py)confidenceNumber","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"confidenceNumber"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/MockAccidentConfig/invalidateFinalCallback()":{"role":"symbol","title":"invalidateFinalCallback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateFinalCallback"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method causes the final callback to invalidate the potential callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/MockAccidentConfig\/invalidateFinalCallback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateFinalCallback"}],"url":"\/documentation\/fairmaticsdk\/mockaccidentconfig\/invalidatefinalcallback()"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo":{"role":"symbol","title":"AccidentInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to an accident detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentInfo"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo/confidenceNumber":{"role":"symbol","title":"confidenceNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Measures an approximate precision of the detected collision. Ranges between 0 to 100."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/confidenceNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confidenceNumber"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo\/confidencenumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"confidenceNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confidenceNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceNumber"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1invalidateFinalCallback()\/title","value":"invalidateFinalCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1MockAccidentConfig~1invalidateFinalCallback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateFinalCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/title","value":"FairmaticAccidentInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1confidenceNumber\/title","value":"confidenceNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1confidenceNumber\/fragments","value":[{"kind":"identifier","text":"confidenceNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}