{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint","text":"LocationPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"AccidentConfidence"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accidentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vehicleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType","text":"VehicleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"collisionSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity","text":"CollisionSeverity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact","text":"DirectionOfImpact"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"AccidentInfo"},{"type":"text","text":" object"}]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The location of the accident"}]}]},{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp of the accident in milliseconds since epoch"}]}]},{"name":"trackingId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tracking id of the ongoing drive when the accident occured"}]}]},{"name":"sessionId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The session that was in progress when the accident"},{"type":"text","text":" "},{"type":"text","text":"occured, if a session was started in the SDK"}]}]},{"name":"confidence","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Confidence measure of the detected accident"}]}]},{"name":"confidenceNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Confidence number of the detected accident"}]}]},{"name":"accidentId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique identifier of this accident"}]}]},{"name":"driveId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique Id of drive during which the accident occured"}]}]},{"name":"vehicleType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Vehicle type detected by SDK at the time of the accident"}]}]},{"name":"collisionSeverity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Collision Severity detected by SDK at the time of the accident"}]}]},{"name":"directionOfImpact","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Direction Of Impact detected by SDK at the time of the accident"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/init(location:timestamp:trackingid:sessionid:confidence:confidencenumber:accidentid:driveid:vehicletype:collisionseverity:directionofimpact:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/accidentinfo\/init(location:timestamp:trackingid:sessionid:confidence:confidencenumber:accidentid:driveid:vehicletype:collisionseverity:directionofimpact:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializer for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accidentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vehicleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"collisionSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollisionSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact"},{"kind":"text","text":")"}],"title":"init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticAccidentInfo(im)initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/VehicleType":{"role":"symbol","title":"VehicleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VehicleType"}],"abstract":[{"type":"text","text":"Type of vehicle used in the drive recorded by the Fairmatic SDK."},{"type":"text","text":" "},{"type":"text","text":"A default vehicle type can be set using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes"},{"type":"text","text":". The detected type is returned to the application in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType"},{"type":"text","text":" "},{"type":"text","text":"field of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VehicleType"}],"url":"\/documentation\/fairmaticsdk\/vehicletype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo/init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)":{"role":"symbol","title":"init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confidenceNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accidentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"driveId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vehicleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"collisionSeverity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollisionSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"directionOfImpact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializer for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo\/init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo\/init(location:timestamp:trackingid:sessionid:confidence:confidencenumber:accidentid:driveid:vehicletype:collisionseverity:directionofimpact:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriverAttributes/setVehicleType(_:)":{"role":"symbol","title":"setVehicleType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVehicleType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the vehicle type for the driver."},{"type":"text","text":" "},{"type":"text","text":"To enable the feature for any vehicle type other than "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType\/car"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"please reach out to your contact at Fairmatic"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes\/setVehicleType(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVehicleType:"}],"url":"\/documentation\/fairmaticsdk\/driverattributes\/setvehicletype(_:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/CollisionSeverity":{"role":"symbol","title":"CollisionSeverity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollisionSeverity"}],"abstract":[{"type":"text","text":"Collision severity of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollisionSeverity"}],"url":"\/documentation\/fairmaticsdk\/collisionseverity"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DirectionOfImpact":{"role":"symbol","title":"DirectionOfImpact","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionOfImpact"}],"abstract":[{"type":"text","text":"Direction of impact detected by SDK at the time of the accident"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionOfImpact"}],"url":"\/documentation\/fairmaticsdk\/directionofimpact"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/FairmaticDelegate/processAnalysis(ofDrive:)":{"role":"symbol","title":"processAnalysis(ofDrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAnalysis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofDrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyzedDriveInfo","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticAnalyzedDriveInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on the delegate in the main thread when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/Fairmatic"},{"type":"text","text":" SDK finishes"},{"type":"text","text":" "},{"type":"text","text":"full analysis of all valid drives returned from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processEnd(ofDrive:)"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/FairmaticDelegate\/processAnalysis(ofDrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAnalysisOfDrive:"}],"url":"\/documentation\/fairmaticsdk\/fairmaticdelegate\/processanalysis(ofdrive:)"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentInfo":{"role":"symbol","title":"AccidentInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentInfo"}],"abstract":[{"type":"text","text":"Wrapper for meta-information related to an accident detected by the SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentInfo"}],"url":"\/documentation\/fairmaticsdk\/accidentinfo"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/LocationPoint":{"role":"symbol","title":"LocationPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationPoint"}],"abstract":[{"type":"text","text":"Represents a geographical coordinate."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationPoint"}],"url":"\/documentation\/fairmaticsdk\/locationpoint"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveInfo/vehicleType":{"role":"symbol","title":"vehicleType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType"}],"abstract":[{"type":"text","text":"The type of vehicle."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveInfo\/vehicleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicleType"}],"url":"\/documentation\/fairmaticsdk\/driveinfo\/vehicletype"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriverAttributes":{"role":"symbol","title":"DriverAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriverAttributes"}],"abstract":[{"type":"text","text":"Additional attributes of a "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" driver."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriverAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriverAttributes"}],"url":"\/documentation\/fairmaticsdk\/driverattributes"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/AccidentConfidence":{"role":"symbol","title":"AccidentConfidence","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccidentConfidence"}],"abstract":[{"type":"text","text":"Confidence measure of the detected accident."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccidentConfidence"}],"url":"\/documentation\/fairmaticsdk\/accidentconfidence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLocation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/LocationPoint","preciseIdentifier":"c:@M@FairmaticSDK@objc(cs)FairmaticLocationPoint","text":"FairmaticLocationPoint"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"location"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"trackingId"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sessionId"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/AccidentConfidence","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticAccidentConfidence","text":"FairmaticAccidentConfidence"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confidenceNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"accidentId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accidentId"},{"kind":"text","text":" "},{"kind":"identifier","text":"driveId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"driveId"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/VehicleType","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticVehicleType","text":"FairmaticVehicleType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"vehicleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"collisionSeverity:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/CollisionSeverity","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticCollisionSeverity","text":"FairmaticCollisionSeverity"},{"kind":"text","text":")"},{"kind":"internalParam","text":"collisionSeverity"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionOfImpact:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DirectionOfImpact","preciseIdentifier":"c:@M@FairmaticSDK@E@FairmaticDirectionOfImpact","text":"FairmaticDirectionOfImpact"},{"kind":"text","text":")"},{"kind":"internalParam","text":"directionOfImpact"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1VehicleType\/title","value":"FairmaticVehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1VehicleType\/fragments","value":[{"kind":"identifier","text":"FairmaticVehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)\/title","value":"initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo~1init(location:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:timestamp:trackingId:sessionId:confidence:confidenceNumber:accidentId:driveId:vehicleType:collisionSeverity:directionOfImpact:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes~1setVehicleType(_:)\/title","value":"setVehicleType:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes~1setVehicleType(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVehicleType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity\/title","value":"FairmaticCollisionSeverity"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1CollisionSeverity\/fragments","value":[{"kind":"identifier","text":"FairmaticCollisionSeverity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/title","value":"FairmaticDirectionOfImpact"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DirectionOfImpact\/fragments","value":[{"kind":"identifier","text":"FairmaticDirectionOfImpact"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/title","value":"processAnalysisOfDrive:"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1FairmaticDelegate~1processAnalysis(ofDrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processAnalysisOfDrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/title","value":"FairmaticAccidentInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/title","value":"FairmaticLocationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1LocationPoint\/fragments","value":[{"kind":"identifier","text":"FairmaticLocationPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1vehicleType\/title","value":"vehicleType"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveInfo~1vehicleType\/fragments","value":[{"kind":"identifier","text":"vehicleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes\/title","value":"FairmaticDriverAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriverAttributes\/fragments","value":[{"kind":"identifier","text":"FairmaticDriverAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/title","value":"FairmaticAccidentConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1AccidentConfidence\/fragments","value":[{"kind":"identifier","text":"FairmaticAccidentConfidence"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}