{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fairmaticsdk\/driveresumeinfo\/distance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fairmaticsdk\/driveresumeinfo\/distance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo\/distance","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The distance of the trip in metres"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"distance","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FairmaticSDK@objc(cs)FairmaticDriveResumeInfo(py)distance","modules":[{"name":"FairmaticSDK"}],"navigatorTitle":[{"kind":"identifier","text":"distance"}]},"hierarchy":{"paths":[["doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo"]]},"references":{"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK":{"role":"collection","title":"FairmaticSDK","abstract":[{"type":"text","text":"The Fairmatic SDK for iOS"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK","kind":"symbol","type":"topic","url":"\/documentation\/fairmaticsdk"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveResumeInfo/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance of the trip in metres"}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo\/distance"},"doc://com.fairmatic.FairmaticSDK/documentation/FairmaticSDK/DriveResumeInfo":{"role":"symbol","title":"DriveResumeInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DriveResumeInfo"}],"abstract":[{"type":"text","text":"Information about a drive that was resumed in the "},{"type":"codeVoice","code":"Fairmatic"},{"type":"text","text":" SDK."}],"identifier":"doc:\/\/com.fairmatic.FairmaticSDK\/documentation\/FairmaticSDK\/DriveResumeInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DriveResumeInfo"}],"url":"\/documentation\/fairmaticsdk\/driveresumeinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"distance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveResumeInfo~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveResumeInfo~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveResumeInfo\/title","value":"FairmaticDriveResumeInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.fairmatic.FairmaticSDK~1documentation~1FairmaticSDK~1DriveResumeInfo\/fragments","value":[{"kind":"identifier","text":"FairmaticDriveResumeInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}